/**
 * PlanDetail API client functions
 * Generated by enhanced entity generator script V3
 */

import type {
  CreatePlanDetailInput,
  ImportPlanDetailResult,
  PlanDetailListParamsWithOwner,
  PlanDetailResponse,
  PlanDetailsResponse,
  PlanDetailStatsResponse,
  UpdatePlanDetailInput,
} from '@/types/plandetail';

const API_BASE = '/api/plandetails';

/**
 * Fetch plan details with pagination and filtering
 */
export async function fetchPlanDetails(params: PlanDetailListParamsWithOwner): Promise<PlanDetailsResponse> {
  const searchParams = new URLSearchParams();

  if (params.page) {
    searchParams.append('page', params.page.toString());
  }
  if (params.limit) {
    searchParams.append('limit', params.limit.toString());
  }
  if (params.search) {
    searchParams.append('search', params.search);
  }
  if (params.sortBy) {
    searchParams.append('sortBy', params.sortBy);
  }
  if (params.sortOrder) {
    searchParams.append('sortOrder', params.sortOrder);
  }
  if (params.showAll) {
    searchParams.append('showAll', params.showAll.toString());
  }
  if (params.includeRelations) {
    searchParams.append('includeRelations', params.includeRelations.toString());
  }

  const response = await fetch(`${API_BASE}?${searchParams.toString()}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to fetch plan details');
  }

  return response.json();
}

/**
 * Fetch a single plan detail by ID
 */
export async function fetchPlanDetail(id: number): Promise<PlanDetailResponse> {
  const response = await fetch(`${API_BASE}/${id}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to fetch plan detail');
  }

  return response.json();
}

/**
 * Create a new plan detail
 */
export async function createPlanDetail(data: CreatePlanDetailInput): Promise<PlanDetailResponse> {
  const response = await fetch(API_BASE, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to create plan detail');
  }

  return response.json();
}

/**
 * Update an existing plan detail
 */
export async function updatePlanDetail(id: number, data: UpdatePlanDetailInput): Promise<PlanDetailResponse> {
  const response = await fetch(`${API_BASE}/${id}`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to update plan detail');
  }

  return response.json();
}

/**
 * Delete a plan detail
 */
export async function deletePlanDetail(id: number): Promise<{ success: boolean; message: string }> {
  const response = await fetch(`${API_BASE}/${id}`, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to delete plan detail');
  }

  return response.json();
}

/**
 * Get plan detail statistics
 */
export async function fetchPlanDetailStats(): Promise<PlanDetailStatsResponse> {
  const response = await fetch(`${API_BASE}/stats`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to fetch plan detail stats');
  }

  return response.json();
}

/**
 * Export plan details to Excel
 */
export async function exportPlanDetails(params: PlanDetailListParamsWithOwner): Promise<Blob> {
  const searchParams = new URLSearchParams();

  if (params.page) {
    searchParams.append('page', params.page.toString());
  }
  if (params.limit) {
    searchParams.append('limit', params.limit.toString());
  }
  if (params.search) {
    searchParams.append('search', params.search);
  }
  if (params.sortBy) {
    searchParams.append('sortBy', params.sortBy);
  }
  if (params.sortOrder) {
    searchParams.append('sortOrder', params.sortOrder);
  }
  if (params.showAll) {
    searchParams.append('showAll', params.showAll.toString());
  }

  const response = await fetch(`${API_BASE}/export?${searchParams.toString()}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to export plan details');
  }

  return response.blob();
}

/**
 * Import plan details from Excel
 */
export async function importPlanDetails(file: File): Promise<ImportPlanDetailResult> {
  const formData = new FormData();
  formData.append('file', file);

  const response = await fetch(`${API_BASE}/import`, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error || 'Failed to import plan details');
  }

  return response.json();
}
