/**
 * EmployeeSalaryEntry Database Schema with Complex Features
 * Generated by enhanced entity generator script V4
 * 🆕 Features: Text FKs, Decimal Precision, Complex Indexes, Check Constraints
 */

import { relations, sql } from 'drizzle-orm';
import {
  check,
  date,
  decimal,
  index,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/pg-core';

import { planSchema } from './plan';
import { productionStepDetailSchema } from './productionStepDetail';
// Import related schemas
import { userSyncSchema } from './userSync';
// 🆕 Import productSchema for new foreign key
import { productSchema } from '../Schema';

export const employeeSalaryEntrySchema = pgTable('employee_salary_entry', {
  id: serial('id').primaryKey(),

  // Regular fields
  work_date: date('work_date').notNull(),
  entry_date: date('entry_date').defaultNow(),
  actual_quantity: integer('actual_quantity'),
  planned_quantity: integer('planned_quantity'),
  limit_quantity: integer('limit_quantity'),
  previous_entered_quantity: integer('previous_entered_quantity'),
  unit_price: decimal('unit_price', { precision: 10, scale: 2 }),
  total_amount: decimal('total_amount', { precision: 12, scale: 2 }),
  salary_note: text('salary_note'),
  status: text('status'),
  approved_by: text('approved_by'),
  approved_at: timestamp('approved_at', { mode: 'date' }),
  start_time: timestamp('start_time', { mode: 'date' }),
  end_time: timestamp('end_time', { mode: 'date' }),
  work_duration_minutes: integer('work_duration_minutes'),
  owner_id: varchar('owner_id', { length: 50 }).notNull(),

  // Foreign key fields
  user_id: text('user_id').notNull().references(() => userSyncSchema.userId, { onDelete: 'cascade' }),
  production_step_detail_id: integer('production_step_detail_id').notNull().references(() => productionStepDetailSchema.id, { onDelete: 'cascade' }),
  plan_id: integer('plan_id').notNull().references(() => planSchema.id, { onDelete: 'cascade' }),
  // 🆕 Add product foreign key
  product_id: integer('product_id').notNull().references(() => productSchema.id, { onDelete: 'cascade' }),

  // Standard timestamps with enhanced configuration
  created_at: timestamp('created_at', { mode: 'date' }).defaultNow().notNull(),
  updated_at: timestamp('updated_at', { mode: 'date' })
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
}, (table) => {
  return {
    // 🆕 V4: Complex unique indexes - updated to include product_id
    employeeWorkUniqueIdx: uniqueIndex('employeeWorkUniqueIdx').on(table.user_id, table.production_step_detail_id, table.plan_id, table.product_id, table.work_date, table.owner_id),

    // 🆕 V4: Composite indexes for performance
    employeeIdIdx: index('employeeIdIdx').on(table.user_id),
    planIdIdx: index('planIdIdx').on(table.plan_id),
    productIdIdx: index('productIdIdx').on(table.product_id), // 🆕 Add product index
    workDateIdx: index('workDateIdx').on(table.work_date),
    statusIdx: index('statusIdx').on(table.status),
    entryDateIdx: index('entryDateIdx').on(table.entry_date),
    userPlanIdx: index('userPlanIdx').on(table.user_id, table.plan_id),
    planDateIdx: index('planDateIdx').on(table.plan_id, table.work_date),
    productDateIdx: index('productDateIdx').on(table.product_id, table.work_date), // 🆕 Add product-date index

    // 🆕 V4: Check constraints for data integrity
    actualQuantityCheck: check('actualQuantityCheck', sql`actual_quantity >= 0`),
    plannedQuantityCheck: check('plannedQuantityCheck', sql`planned_quantity >= 0`),
    limitQuantityCheck: check('limitQuantityCheck', sql`limit_quantity >= 0`),
    unitPriceCheck: check('unitPriceCheck', sql`unit_price >= 0`),
    totalAmountCheck: check('totalAmountCheck', sql`total_amount >= 0`),
    workDurationCheck: check('workDurationCheck', sql`work_duration_minutes >= 0`),
  };
});

// Relations configuration
export const employeeSalaryEntryRelations = relations(employeeSalaryEntrySchema, ({ one }) => ({
  userSync: one(userSyncSchema, {
    fields: [employeeSalaryEntrySchema.user_id],
    references: [userSyncSchema.userId],
    relationName: 'employeeSalaryEntry_userSync',
  }),
  productionStepDetail: one(productionStepDetailSchema, {
    fields: [employeeSalaryEntrySchema.production_step_detail_id],
    references: [productionStepDetailSchema.id],
    relationName: 'employeeSalaryEntry_productionStepDetail',
  }),
  plan: one(planSchema, {
    fields: [employeeSalaryEntrySchema.plan_id],
    references: [planSchema.id],
    relationName: 'employeeSalaryEntry_plan',
  }),
  // 🆕 Add product relation
  product: one(productSchema, {
    fields: [employeeSalaryEntrySchema.product_id],
    references: [productSchema.id],
    relationName: 'employeeSalaryEntry_product',
  }),
}));
