/**
 * OutsourceOrder Database Schema with Relations
 * Generated by enhanced entity generator script V4 (improved)
 */

import { relations } from 'drizzle-orm';
import { date, decimal, integer, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

import { userSyncSchema } from './userSync';

// Import related schemas

export const outsourceOrderSchema = pgTable('outsource_order', {
  id: serial('id').primaryKey(),

  // Regular fields
  orderCode: text('order_code').notNull().unique(),
  orderTitle: text('order_title'),
  orderDate: date('order_date').notNull(),
  expectedCompletionDate: date('expected_completion_date'),
  actualCompletionDate: date('actual_completion_date'),
  status: text('status').notNull(),
  priority: integer('priority').notNull(),
  totalAmount: decimal('total_amount'),
  currency: text('currency'),
  notes: text('notes'),
  attachment: text('attachment'),
  applyRetailPrice: integer('apply_retail_price').notNull().default(2),

  // Foreign key fields
  createdByUserId: text('created_by_user_id').notNull().references(() => userSyncSchema.userId, { onDelete: 'restrict' }),
  assignedToUserId: text('assigned_to_user_id').notNull().references(() => userSyncSchema.userId, { onDelete: 'restrict' }),

  ownerId: text('owner_id').notNull(),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Relations configuration
export const outsourceOrderRelations = relations(outsourceOrderSchema, ({ one }) => ({
  createdByUser: one(userSyncSchema, {
    fields: [outsourceOrderSchema.createdByUserId],
    references: [userSyncSchema.userId],
    relationName: 'outsourceOrder_createdByUser',
  }),
  assignedToUser: one(userSyncSchema, {
    fields: [outsourceOrderSchema.assignedToUserId],
    references: [userSyncSchema.userId],
    relationName: 'outsourceOrder_assignedToUser',
  }),
}));