/**
 * PlanDetail Database Schema with Relations
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { relations } from 'drizzle-orm';
import { pgTable, serial, text, integer, timestamp, date } from 'drizzle-orm/pg-core';

// Import related schemas
import { planSchema } from '../Schema';

export const plandetailSchema = pgTable('plan_detail', {
  id: serial('id').primaryKey(),
  
  // Regular fields
  locationCode: text('locationCode').notNull(),
  locationType: text('locationType'),
  productCode: text('productCode').notNull(),
  productSubCode: text('productSubCode').notNull(),
  plannedQuantity: integer('plannedQuantity').notNull(),
  actualQuantity: integer('actualQuantity'),
  plannedStartDate: date('plannedStartDate'),
  plannedEndDate: date('plannedEndDate'),
  actualStartDate: date('actualStartDate'),
  actualEndDate: date('actualEndDate'),
  status: text('status'),
  priority: integer('priority'),
  note: text('note'),
  ownerId: text('ownerId').notNull(),

  // Foreign key fields
  planId: integer('planId').notNull().references(() => planSchema.id, { onDelete: 'cascade' }),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Relations configuration
export const plandetailRelations = relations(plandetailSchema, ({ one }) => ({
  plan: one(planSchema, {
    fields: [plandetailSchema.planId],
    references: [planSchema.id],
    relationName: 'plandetail_plan',
  }),
}));