/**
 * EmployeeSalaryEntry Enhanced Database Queries with Complex Features
 * Generated by enhanced entity generator script V4
 * 🆕 Features: Text FK Support, Complex Relations, Enhanced Error Handling
 */

import { and, asc, between, count, desc, eq, gte, ilike, lte } from 'drizzle-orm';

import { db } from '@/libs/DB';
import { employeeSalaryEntrySchema, planSchema, productionStepDetailSchema, userSyncSchema } from '@/models/Schema';
import type {
  CreateEmployeeSalaryEntryInput,
  EmployeeSalaryEntryBatchRequest,
  EmployeeSalaryEntryBatchResponse,
  EmployeeSalaryEntryDb,
  EmployeeSalaryEntryRelationOptions,
  EmployeeSalaryEntryStats,
  EmployeeSalaryEntryWithRelations,
  UpdateEmployeeSalaryEntryInput,
} from '@/types/employeeSalaryEntry';

/**
 * 🆕 V4: Create a new employeeSalaryEntry with enhanced features
 * - Text foreign key support
 * - Complex validation
 * - Business logic calculations
 */
export async function createEmployeeSalaryEntry(data: CreateEmployeeSalaryEntryInput): Promise<EmployeeSalaryEntryDb> {
  // 🆕 V4: Validate foreign keys exist (supporting both text and integer FKs)

  if (data.userId) {
    const userSyncExists = await db
      .select({ userId: userSyncSchema.userId })
      .from(userSyncSchema)
      .where(eq(userSyncSchema.userId, data.userId))
      .limit(1);

    if (!userSyncExists.length) {
      throw new Error('UserSync not found');
    }
  }
  if (data.productionStepDetailId) {
    const productionStepDetailExists = await db
      .select({ id: productionStepDetailSchema.id })
      .from(productionStepDetailSchema)
      .where(eq(productionStepDetailSchema.id, data.productionStepDetailId))
      .limit(1);

    if (!productionStepDetailExists.length) {
      throw new Error('ProductionStepDetail not found');
    }
  }
  if (data.planId) {
    const planExists = await db
      .select({ id: planSchema.id })
      .from(planSchema)
      .where(eq(planSchema.id, data.planId))
      .limit(1);

    if (!planExists.length) {
      throw new Error('Plan not found');
    }
  }

  //  V4: Business logic - Auto-calculate total amount
  if (data.actualQuantity && data.unitPrice && !data.totalAmount) {
    data.totalAmount = Number(data.actualQuantity ?? 0) * Number(data.unitPrice ?? 0);
  }

  const [employeeSalaryEntry] = await db
    .insert(employeeSalaryEntrySchema)
    .values({
      work_date: data.workDate ? new Date(data.workDate) : null,
      entry_date: data.entryDate ? new Date(data.entryDate) : null,
      actual_quantity: data.actualQuantity,
      planned_quantity: data.plannedQuantity,
      limit_quantity: data.limitQuantity,
      previous_entered_quantity: data.previousEnteredQuantity,
      unit_price: data.unitPrice,
      total_amount: data.totalAmount,
      salary_note: data.salaryNote,
      status: data.status,
      approved_by: data.approvedBy,
      approved_at: data.approvedAt ? new Date(data.approvedAt) : null,
      start_time: data.startTime ? new Date(data.startTime) : null,
      end_time: data.endTime ? new Date(data.endTime) : null,
      work_duration_minutes: data.workDurationMinutes,
      owner_id: data.ownerId,
      user_id: data.userId,
      production_step_detail_id: data.productionStepDetailId,
      plan_id: data.planId,
    } as any)
    .returning();

  if (!employeeSalaryEntry) {
    throw new Error('Failed to create employeeSalaryEntry');
  }

  return employeeSalaryEntry;
}

/**
 * 🆕 V4: Get employeeSalaryEntries with enhanced filtering and relations
 * - Complex search and filtering
 * - Text FK joins
 * - Performance optimizations
 */
export async function getEmployeeSalaryEntries(params: {
  page?: number;
  limit?: number;
  search?: string;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  includeRelations?: boolean;
  status?: string;
  dateFrom?: string | Date;
  dateTo?: string | Date;
  user_id?: string;
  production_step_detail_id?: number;
  plan_id?: number;
  owner_id?: string;
}): Promise<EmployeeSalaryEntryDb | EmployeeSalaryEntryWithRelations[]> {
  const {
    page = 1,
    limit = 10,
    search,
    sortBy = 'created_at',
    sortOrder = 'desc',
    includeRelations = false,
    status,
    dateFrom,
    dateTo,
    user_id,
    production_step_detail_id,
    plan_id,
    owner_id,
  } = params;

  const offset = (page - 1) * limit;

  const query = db
    .select({
      // Main entity fields
      id: employeeSalaryEntrySchema.id,
      work_date: employeeSalaryEntrySchema.work_date,
      entry_date: employeeSalaryEntrySchema.entry_date,
      actual_quantity: employeeSalaryEntrySchema.actual_quantity,
      planned_quantity: employeeSalaryEntrySchema.planned_quantity,
      limit_quantity: employeeSalaryEntrySchema.limit_quantity,
      previous_entered_quantity: employeeSalaryEntrySchema.previous_entered_quantity,
      unit_price: employeeSalaryEntrySchema.unit_price,
      total_amount: employeeSalaryEntrySchema.total_amount,
      salary_note: employeeSalaryEntrySchema.salary_note,
      status: employeeSalaryEntrySchema.status,
      approved_by: employeeSalaryEntrySchema.approved_by,
      approved_at: employeeSalaryEntrySchema.approved_at,
      start_time: employeeSalaryEntrySchema.start_time,
      end_time: employeeSalaryEntrySchema.end_time,
      work_duration_minutes: employeeSalaryEntrySchema.work_duration_minutes,
      owner_id: employeeSalaryEntrySchema.owner_id,
      created_at: employeeSalaryEntrySchema.created_at,
      updated_at: employeeSalaryEntrySchema.updated_at,

      // Foreign key fields
      user_id: employeeSalaryEntrySchema.user_id,
      production_step_detail_id: employeeSalaryEntrySchema.production_step_detail_id,
      plan_id: employeeSalaryEntrySchema.plan_id,

      // 🆕 V4: Related entity data with text FK support

      ...(includeRelations
        ? {
            userSync: {
              userId: userSyncSchema.userId,
              fullName: userSyncSchema.fullName,
            },
          }
        : {}),

      ...(includeRelations
        ? {
            productionStepDetail: {
              id: productionStepDetailSchema.id,
            },
          }
        : {}),

      ...(includeRelations
        ? {
            plan: {
              id: planSchema.id,
              planName: planSchema.planName,
            },
          }
        : {}),
    })
    .from(employeeSalaryEntrySchema)
    .leftJoin(
      userSyncSchema,
      eq(employeeSalaryEntrySchema.user_id, userSyncSchema.userId),
    )
    .leftJoin(
      productionStepDetailSchema,
      eq(employeeSalaryEntrySchema.production_step_detail_id, productionStepDetailSchema.id),
    )
    .leftJoin(
      planSchema,
      eq(employeeSalaryEntrySchema.plan_id, planSchema.id),
    );

  // Build enhanced where conditions
  const conditions = [];
  if (owner_id !== undefined) {
    conditions.push(eq(employeeSalaryEntrySchema.owner_id, owner_id));
  }
  if (typeof search === 'string' && search.trim() !== '') {
    conditions.push(ilike(employeeSalaryEntrySchema.work_date, `%${search}%`));
    conditions.push(ilike(employeeSalaryEntrySchema.salary_note, `%${search}%`));
    conditions.push(ilike(userSyncSchema.fullName, `%${search}%`));
    conditions.push(ilike(productionStepDetailSchema.id, `%${search}%`));
    conditions.push(ilike(planSchema.planName, `%${search}%`));
  }
  if (status) {
    conditions.push(eq(employeeSalaryEntrySchema.status, status));
  }

  let whereConditions = conditions.length > 1 ? and(...conditions) : conditions[0];

  // Date range filter
  if (dateFrom && dateTo) {
    whereConditions = and(
      whereConditions,
      between(employeeSalaryEntrySchema.work_date, typeof dateFrom === 'string' ? dateFrom : new Date(dateFrom).toISOString().slice(0, 10), typeof dateTo === 'string' ? dateTo : new Date(dateTo).toISOString().slice(0, 10)),
    );
  } else if (dateFrom) {
    whereConditions = and(whereConditions, gte(employeeSalaryEntrySchema.work_date, typeof dateFrom === 'string' ? dateFrom : new Date(dateFrom).toISOString().slice(0, 10)));
  } else if (dateTo) {
    whereConditions = and(whereConditions, lte(employeeSalaryEntrySchema.work_date, typeof dateTo === 'string' ? dateTo : new Date(dateTo).toISOString().slice(0, 10)));
  }

  // Relation filters

  if (user_id !== undefined) {
    whereConditions = and(whereConditions, eq(employeeSalaryEntrySchema.user_id, user_id));
  }
  if (production_step_detail_id !== undefined) {
    whereConditions = and(whereConditions, eq(employeeSalaryEntrySchema.production_step_detail_id, production_step_detail_id));
  }
  if (plan_id !== undefined) {
    whereConditions = and(whereConditions, eq(employeeSalaryEntrySchema.plan_id, plan_id));
  }

  // 🆕 V4: Enhanced sorting with relation support
  let orderBy;
  switch (sortBy) {
    case 'created_at':
      orderBy = sortOrder === 'asc' ? asc(employeeSalaryEntrySchema.created_at) : desc(employeeSalaryEntrySchema.created_at);
      break;
    case 'updated_at':
      orderBy = sortOrder === 'asc' ? asc(employeeSalaryEntrySchema.updated_at) : desc(employeeSalaryEntrySchema.updated_at);
      break;
    case 'work_date':
      orderBy = sortOrder === 'asc' ? asc(employeeSalaryEntrySchema.work_date) : desc(employeeSalaryEntrySchema.work_date);
      break;
    case 'id':
      orderBy = sortOrder === 'asc' ? asc(employeeSalaryEntrySchema.id) : desc(employeeSalaryEntrySchema.id);
      break;
    case 'status':
      orderBy = sortOrder === 'asc' ? asc(employeeSalaryEntrySchema.status) : desc(employeeSalaryEntrySchema.status);
      break;
    default:
      orderBy = desc(employeeSalaryEntrySchema.created_at);
  }

  const results = await query
    .where(whereConditions)
    .orderBy(orderBy)
    .limit(limit)
    .offset(offset);

  return results.map(r => ({
    ...r,
    workDate: r.work_date,
    entryDate: r.entry_date,
    actualQuantity: r.actual_quantity,
    plannedQuantity: r.planned_quantity,
    limitQuantity: r.limit_quantity,
    previousEnteredQuantity: r.previous_entered_quantity,
    unitPrice: r.unit_price,
    totalAmount: r.total_amount,
    salaryNote: r.salary_note,
    approvedBy: r.approved_by,
    approvedAt: r.approved_at,
    startTime: r.start_time,
    endTime: r.end_time,
    workDurationMinutes: r.work_duration_minutes,
    ownerId: r.owner_id,
    userId: r.user_id,
    productionStepDetailId: r.production_step_detail_id,
    planId: r.plan_id,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
    userSync: r.userSync
      ? {
          userId: r.userSync.userId,
          fullName: r.userSync.fullName,
        }
      : undefined,
    plan: r.plan
      ? {
          id: r.plan.id,
          planName: r.plan.planName,
        }
      : undefined,
    productionStepDetail: r.productionStepDetail
      ? {
          id: r.productionStepDetail.id,
        }
      : undefined,
  }));
}

/**
 * 🆕 V4: Get employeeSalaryEntry by ID with enhanced features
 */
export async function getEmployeeSalaryEntryById(id: number, owner_id: string, includeRelations = false): Promise<EmployeeSalaryEntryDb | EmployeeSalaryEntryWithRelations | undefined> {
  const query = db
    .select({
      id: employeeSalaryEntrySchema.id,
      work_date: employeeSalaryEntrySchema.work_date,
      entry_date: employeeSalaryEntrySchema.entry_date,
      actual_quantity: employeeSalaryEntrySchema.actual_quantity,
      planned_quantity: employeeSalaryEntrySchema.planned_quantity,
      limit_quantity: employeeSalaryEntrySchema.limit_quantity,
      previous_entered_quantity: employeeSalaryEntrySchema.previous_entered_quantity,
      unit_price: employeeSalaryEntrySchema.unit_price,
      total_amount: employeeSalaryEntrySchema.total_amount,
      salary_note: employeeSalaryEntrySchema.salary_note,
      status: employeeSalaryEntrySchema.status,
      approved_by: employeeSalaryEntrySchema.approved_by,
      approved_at: employeeSalaryEntrySchema.approved_at,
      start_time: employeeSalaryEntrySchema.start_time,
      end_time: employeeSalaryEntrySchema.end_time,
      work_duration_minutes: employeeSalaryEntrySchema.work_duration_minutes,
      owner_id: employeeSalaryEntrySchema.owner_id,
      created_at: employeeSalaryEntrySchema.created_at,
      updated_at: employeeSalaryEntrySchema.updated_at,

      // Foreign key fields
      user_id: employeeSalaryEntrySchema.user_id,
      production_step_detail_id: employeeSalaryEntrySchema.production_step_detail_id,
      plan_id: employeeSalaryEntrySchema.plan_id,

      // Related entity data

      ...(includeRelations
        ? {
            userSync: {
              userId: userSyncSchema.userId,
              fullName: userSyncSchema.fullName,
            },
          }
        : {}),

      ...(includeRelations
        ? {
            productionStepDetail: {
              id: productionStepDetailSchema.id,
            },
          }
        : {}),

      ...(includeRelations
        ? {
            plan: {
              id: planSchema.id,
              planName: planSchema.planName,
            },
          }
        : {}),
    })
    .from(employeeSalaryEntrySchema)
    .leftJoin(
      userSyncSchema,
      eq(employeeSalaryEntrySchema.user_id, userSyncSchema.userId),
    )
    .leftJoin(
      productionStepDetailSchema,
      eq(employeeSalaryEntrySchema.production_step_detail_id, productionStepDetailSchema.id),
    )
    .leftJoin(
      planSchema,
      eq(employeeSalaryEntrySchema.plan_id, planSchema.id),
    );

  const [result] = await query
    .where(and(
      eq(employeeSalaryEntrySchema.id, id),
      eq(employeeSalaryEntrySchema.owner_id, owner_id),
    ))
    .limit(1);

  if (!result) {
    return undefined;
  }

  return result;
}

/**
 * 🆕 V4: Update employeeSalaryEntry with enhanced features
 */
export async function updateEmployeeSalaryEntry(
  id: number,
  owner_id: string,
  data: UpdateEmployeeSalaryEntryInput,
): Promise<EmployeeSalaryEntryDb> {
  // Get existing entity for conditional updates
  const existingEmployeeSalaryEntry = await getEmployeeSalaryEntryById(id, owner_id);
  if (!existingEmployeeSalaryEntry) {
    throw new Error('EmployeeSalaryEntry not found or access denied');
  }

  // 🆕 V4: Auto-calculate total amount if needed
  if (data.actualQuantity !== undefined || data.unitPrice !== undefined) {
    const actual_quantity = data.actualQuantity ?? existingEmployeeSalaryEntry.actual_quantity ?? 0;
    const unit_price = data.unitPrice ?? existingEmployeeSalaryEntry.unit_price ?? 0;
    data.totalAmount = Number(actual_quantity) * Number(unit_price);
  }

  // Build update data with proper type handling
  const updateData: Record<string, unknown> = {};

  if (data.userId !== undefined) {
    updateData.user_id = data.userId;
  } else {
    updateData.user_id = existingEmployeeSalaryEntry.user_id;
  }
  if (data.productionStepDetailId !== undefined) {
    updateData.production_step_detail_id = data.productionStepDetailId;
  } else {
    updateData.production_step_detail_id = existingEmployeeSalaryEntry.production_step_detail_id;
  }
  if (data.planId !== undefined) {
    updateData.plan_id = data.planId;
  } else {
    updateData.plan_id = existingEmployeeSalaryEntry.plan_id;
  }
  if (data.workDate !== undefined) {
    updateData.work_date = data.workDate ? new Date(data.workDate) : null;
  } else {
    updateData.work_date = existingEmployeeSalaryEntry.work_date;
  }
  if (data.entryDate !== undefined) {
    updateData.entry_date = data.entryDate ? new Date(data.entryDate) : null;
  } else {
    updateData.entry_date = existingEmployeeSalaryEntry.entry_date;
  }
  if (data.actualQuantity !== undefined) {
    updateData.actual_quantity = data.actualQuantity;
  } else {
    updateData.actual_quantity = existingEmployeeSalaryEntry.actual_quantity;
  }
  if (data.plannedQuantity !== undefined) {
    updateData.planned_quantity = data.plannedQuantity;
  } else {
    updateData.planned_quantity = existingEmployeeSalaryEntry.planned_quantity;
  }
  if (data.limitQuantity !== undefined) {
    updateData.limit_quantity = data.limitQuantity;
  } else {
    updateData.limit_quantity = existingEmployeeSalaryEntry.limit_quantity;
  }
  if (data.previousEnteredQuantity !== undefined) {
    updateData.previous_entered_quantity = data.previousEnteredQuantity;
  } else {
    updateData.previous_entered_quantity = existingEmployeeSalaryEntry.previous_entered_quantity;
  }
  if (data.unitPrice !== undefined) {
    updateData.unit_price = data.unitPrice;
  } else {
    updateData.unit_price = existingEmployeeSalaryEntry.unit_price;
  }
  if (data.totalAmount !== undefined) {
    updateData.total_amount = data.totalAmount;
  } else {
    updateData.total_amount = existingEmployeeSalaryEntry.total_amount;
  }
  if (data.salaryNote !== undefined) {
    updateData.salary_note = data.salaryNote;
  } else {
    updateData.salary_note = existingEmployeeSalaryEntry.salary_note;
  }
  if (data.status !== undefined) {
    updateData.status = data.status;
  } else {
    updateData.status = existingEmployeeSalaryEntry.status;
  }
  if (data.approvedBy !== undefined) {
    updateData.approved_by = data.approvedBy;
  } else {
    updateData.approved_by = existingEmployeeSalaryEntry.approved_by;
  }
  if (data.approvedAt !== undefined) {
    updateData.approved_at = data.approvedAt ? new Date(data.approvedAt) : null;
  } else {
    updateData.approved_at = existingEmployeeSalaryEntry.approved_at;
  }
  if (data.startTime !== undefined) {
    updateData.start_time = data.startTime ? new Date(data.startTime) : null;
  } else {
    updateData.start_time = existingEmployeeSalaryEntry.start_time;
  }
  if (data.endTime !== undefined) {
    updateData.end_time = data.endTime ? new Date(data.endTime) : null;
  } else {
    updateData.end_time = existingEmployeeSalaryEntry.end_time;
  }
  if (data.workDurationMinutes !== undefined) {
    updateData.work_duration_minutes = data.workDurationMinutes;
  } else {
    updateData.work_duration_minutes = existingEmployeeSalaryEntry.work_duration_minutes;
  }

  const [updatedEmployeeSalaryEntry] = await db
    .update(employeeSalaryEntrySchema)
    .set(updateData as any)
    .where(and(eq(employeeSalaryEntrySchema.id, id), eq(employeeSalaryEntrySchema.owner_id, owner_id)))
    .returning();

  if (!updatedEmployeeSalaryEntry) {
    throw new Error('Failed to update employeeSalaryEntry');
  }

  return updatedEmployeeSalaryEntry;
}

/**
 * 🆕 V4: Delete employeeSalaryEntry with enhanced cascade handling
 */
export async function deleteEmployeeSalaryEntry(id: number, owner_id: string): Promise<void> {
  const result = await db
    .delete(employeeSalaryEntrySchema)
    .where(and(eq(employeeSalaryEntrySchema.id, id), eq(employeeSalaryEntrySchema.owner_id, owner_id)))
    .returning();

  if (!result || result.length === 0) {
    throw new Error('EmployeeSalaryEntry not found or access denied');
  }
}

/**
 * 🆕 V4: Get relation options with enhanced performance
 */
export async function getEmployeeSalaryEntryRelationOptions(): Promise<EmployeeSalaryEntryRelationOptions> {
  const [userSyncOptions, productionStepDetailOptions, planOptions] = await Promise.all([

    db.select({
      userId: userSyncSchema.userId,
      fullName: userSyncSchema.fullName,
      shortcut: userSyncSchema.shortcut,
    }).from(userSyncSchema).orderBy(asc(userSyncSchema.fullName)),

    db.select({
      id: productionStepDetailSchema.id,
    }).from(productionStepDetailSchema).orderBy(asc(productionStepDetailSchema.id)),

    db.select({
      id: planSchema.id,
      planName: planSchema.planName,
    }).from(planSchema).orderBy(asc(planSchema.planName)),
  ]);

  return {
    userSyncs: userSyncOptions,
    productionStepDetails: productionStepDetailOptions,
    plans: planOptions,
  };
}

/**
 * 🆕 V4: Enhanced statistics with complex metrics
 */
export async function getEmployeeSalaryEntryStats(owner_id: string): Promise<EmployeeSalaryEntryStats> {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const thisWeekStart = new Date(today);
  thisWeekStart.setDate(today.getDate() - today.getDay());
  const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const [totalResult, todayResult, thisWeekResult, thisMonthResult, statusStats] = await Promise.all([
    db.select({ count: count() }).from(employeeSalaryEntrySchema).where(eq(employeeSalaryEntrySchema.owner_id, owner_id)),
    db.select({ count: count() }).from(employeeSalaryEntrySchema).where(
      and(eq(employeeSalaryEntrySchema.owner_id, owner_id), gte(employeeSalaryEntrySchema.created_at, today)),
    ),
    db.select({ count: count() }).from(employeeSalaryEntrySchema).where(
      and(eq(employeeSalaryEntrySchema.owner_id, owner_id), gte(employeeSalaryEntrySchema.created_at, thisWeekStart)),
    ),
    db.select({ count: count() }).from(employeeSalaryEntrySchema).where(
      and(eq(employeeSalaryEntrySchema.owner_id, owner_id), gte(employeeSalaryEntrySchema.created_at, thisMonthStart)),
    ),

    // Status breakdown
    db.select({
      status: employeeSalaryEntrySchema.status,
      count: count(),
    })
      .from(employeeSalaryEntrySchema)
      .where(eq(employeeSalaryEntrySchema.owner_id, owner_id))
      .groupBy(employeeSalaryEntrySchema.status),
  ]);

  return {
    total: totalResult[0]?.count ?? 0,
    today: todayResult[0]?.count ?? 0,
    thisWeek: thisWeekResult[0]?.count ?? 0,
    thisMonth: thisMonthResult[0]?.count ?? 0,

    byStatus: {
      draft: statusStats?.find(s => s.status === 'draft')?.count ?? 0,
      submitted: statusStats?.find(s => s.status === 'submitted')?.count ?? 0,
      approved: statusStats?.find(s => s.status === 'approved')?.count ?? 0,
      paid: statusStats?.find(s => s.status === 'paid')?.count ?? 0,
      cancelled: statusStats?.find(s => s.status === 'cancelled')?.count ?? 0,
    },
    financial: {
      totalAmount: 0,
      averageAmount: 0,
      maxAmount: 0,
      minAmount: 0,
    },
    productivity: {
      totalWorkTime: 0,
      averageWorkTime: 0,
      efficiency: 0,
    },
  };
}

/**
 * 🆕 V4: Enhanced batch operations
 */
export async function batchEmployeeSalaryEntryOperations(
  request: EmployeeSalaryEntryBatchRequest,
  owner_id: string,
): Promise<EmployeeSalaryEntryBatchResponse> {
  const { ids, action, newStatus, reason: _reason } = request;

  return db.transaction(async (tx) => {
    let processed = 0;
    const errors: { id: number; error: string }[] = [];

    for (const id of ids) {
      try {
        // Verify ownership
        const existing = await tx
          .select({ id: employeeSalaryEntrySchema.id })
          .from(employeeSalaryEntrySchema)
          .where(and(
            eq(employeeSalaryEntrySchema.id, id),
            eq(employeeSalaryEntrySchema.owner_id, owner_id),
          ))
          .limit(1);

        if (!existing.length) {
          errors.push({ id, error: 'Not found or access denied' });
          continue;
        }

        switch (action) {
          case 'delete':

            await tx.delete(employeeSalaryEntrySchema)
              .where(eq(employeeSalaryEntrySchema.id, id));
            break;

          case 'updateStatus':
            if (!newStatus) {
              errors.push({ id, error: 'New status is required' });
              continue;
            }
            await tx.update(employeeSalaryEntrySchema)
              .set({
                status: newStatus,

                ...(newStatus === 'approved'
                  ? {
                      approved_by: owner_id,
                      approved_at: new Date(),
                    }
                  : {}),
              })
              .where(eq(employeeSalaryEntrySchema.id, id));
            break;

          case 'approve':
            await tx.update(employeeSalaryEntrySchema)
              .set({
                status: 'approved',
                approved_by: owner_id,
                approved_at: new Date(),
              })
              .where(eq(employeeSalaryEntrySchema.id, id));
            break;

          case 'reject':
            await tx.update(employeeSalaryEntrySchema)
              .set({ status: 'cancelled' })
              .where(eq(employeeSalaryEntrySchema.id, id));
            break;

          default:
            errors.push({ id, error: `Unknown action: ${action}` });
            continue;
        }

        processed++;
      } catch (error) {
        errors.push({
          id,
          error: error instanceof Error ? error.message : 'Unknown error',
        });
      }
    }

    return {
      success: errors.length === 0,
      processed,
      failed: errors.length,
      errors,
    };
  });
}
