/**
 * OutsourceOrder database queries using Drizzle ORM with Relations Support
 * Enhanced version with proper error handling, type safety and relationships
 * Generated by enhanced entity generator script V4 (improved)
 */

import { and, asc, count, desc, eq, gte, ilike, or, type SQL } from 'drizzle-orm';

import { db } from '../db';
import { outsourceOrderSchema, userSyncSchema } from '@/models/Schema';
import type {
  CreateOutsourceOrderInput,
  OutsourceOrderDb,
  OutsourceOrderListParamsWithOwner,
  OutsourceOrderStats,
  OutsourceOrderWithRelations,
  UpdateOutsourceOrderInput,
} from '@/types/outsourceOrder';

/**
 * Create a new outsourceOrder with proper date and relation handling
 */
export async function createOutsourceOrder(data: CreateOutsourceOrderInput): Promise<OutsourceOrderDb> {
  // Validate foreign keys exist

  if (data.createdByUserId) {
    const userSyncExists = await db
      .select({ userId: userSyncSchema.userId })
      .from(userSyncSchema)
      .where(eq(userSyncSchema.userId, data.createdByUserId))
      .limit(1);

    if (!userSyncExists.length) {
      throw new Error('UserSync not found');
    }
  }
  if (data.assignedToUserId) {
    const userSyncExists = await db
      .select({ userId: userSyncSchema.userId })
      .from(userSyncSchema)
      .where(eq(userSyncSchema.userId, data.assignedToUserId))
      .limit(1);

    if (!userSyncExists.length) {
      throw new Error('UserSync not found');
    }
  }

  const [outsourceOrder] = await db
    .insert(outsourceOrderSchema)
    .values({
      orderCode: data.orderCode,
      orderTitle: data.orderTitle,
      orderDate: data.orderDate ? (typeof data.orderDate === 'string' ? data.orderDate : data.orderDate.toISOString().slice(0, 10)) : null,
      expectedCompletionDate: data.expectedCompletionDate ? (typeof data.expectedCompletionDate === 'string' ? data.expectedCompletionDate : data.expectedCompletionDate.toISOString().slice(0, 10)) : null,
      actualCompletionDate: data.actualCompletionDate ? (typeof data.actualCompletionDate === 'string' ? data.actualCompletionDate : data.actualCompletionDate.toISOString().slice(0, 10)) : null,
      status: data.status ?? '',
      priority: typeof data.priority === 'number' ? data.priority : 0,
      totalAmount: typeof data.totalAmount === 'number' ? data.totalAmount : (data.totalAmount ? Number(data.totalAmount) : undefined),
      currency: data.currency,
      notes: data.notes,
      attachment: data.attachment,
      createdByUserId: data.createdByUserId,
      assignedToUserId: data.assignedToUserId,
      ownerId: data.ownerId,
    } as typeof outsourceOrderSchema.$inferInsert)
    .returning();

  if (!outsourceOrder) {
    throw new Error('Failed to create outsourceOrder');
  }

  return outsourceOrder;
}

/**
 * Update an existing outsourceOrder with proper validation
 */
export async function updateOutsourceOrder(
  id: number,
  data: UpdateOutsourceOrderInput,
  ownerId: string,
): Promise<OutsourceOrderDb> {
  // Check if entity exists and belongs to user
  const existingEntity = await getOutsourceOrderById(id, ownerId);
  if (!existingEntity) {
    throw new Error('OutsourceOrder not found or access denied');
  }

  // Check orderCode uniqueness if it's being changed
  if (data.orderCode !== undefined && data.orderCode !== existingEntity.orderCode) {
    const existingOrderCode = await db
      .select({ id: outsourceOrderSchema.id })
      .from(outsourceOrderSchema)
      .where(and(
        eq(outsourceOrderSchema.orderCode, data.orderCode),
        eq(outsourceOrderSchema.ownerId, ownerId),
      ))
      .limit(1);

    if (existingOrderCode.length > 0) {
      throw new Error('A outsourceOrder with this code already exists');
    }
  }

  // Validate foreign keys if provided

  if (data.createdByUserId !== undefined) {
    const userSyncExists = await db
      .select({ userId: userSyncSchema.userId })
      .from(userSyncSchema)
      .where(eq(userSyncSchema.userId, data.createdByUserId))
      .limit(1);

    if (!userSyncExists.length) {
      throw new Error('UserSync not found');
    }
  }
  if (data.assignedToUserId !== undefined) {
    const userSyncExists = await db
      .select({ userId: userSyncSchema.userId })
      .from(userSyncSchema)
      .where(eq(userSyncSchema.userId, data.assignedToUserId))
      .limit(1);

    if (!userSyncExists.length) {
      throw new Error('UserSync not found');
    }
  }

  // Build update data object - only include fields that are actually being updated
  const updateData: any = {};

  if (data.orderCode !== undefined) {
    updateData.orderCode = data.orderCode;
  }
  if (data.orderTitle !== undefined) {
    updateData.orderTitle = data.orderTitle;
  }
  if (data.createdByUserId !== undefined) {
    updateData.createdByUserId = data.createdByUserId;
  }
  if (data.assignedToUserId !== undefined) {
    updateData.assignedToUserId = data.assignedToUserId;
  }
  if (data.orderDate !== undefined) {
    updateData.orderDate = data.orderDate ? new Date(data.orderDate) : null;
  }
  if (data.expectedCompletionDate !== undefined) {
    updateData.expectedCompletionDate = data.expectedCompletionDate ? new Date(data.expectedCompletionDate) : null;
  }
  if (data.actualCompletionDate !== undefined) {
    updateData.actualCompletionDate = data.actualCompletionDate ? new Date(data.actualCompletionDate) : null;
  }
  if (data.status !== undefined) {
    updateData.status = data.status;
  }
  if (data.priority !== undefined) {
    updateData.priority = data.priority;
  }
  if (data.totalAmount !== undefined) {
    updateData.totalAmount = data.totalAmount;
  }
  if (data.currency !== undefined) {
    updateData.currency = data.currency;
  }
  if (data.notes !== undefined) {
    updateData.notes = data.notes;
  }
  if (data.attachment !== undefined) {
    updateData.attachment = data.attachment;
  }

  const [updatedOutsourceOrder] = await db
    .update(outsourceOrderSchema)
    .set({
      ...updateData,
      updatedAt: new Date(),
    })
    .where(and(
      eq(outsourceOrderSchema.id, id),
      eq(outsourceOrderSchema.ownerId, ownerId),
    ))
    .returning();

  if (!updatedOutsourceOrder) {
    throw new Error('Failed to update outsourceOrder');
  }

  return updatedOutsourceOrder;
}

/**
 * Get outsourceOrder by ID with relations
 */
export async function getOutsourceOrderById(
  id: number,
  ownerId: string,
  includeRelations = false,
): Promise<OutsourceOrderWithRelations | null> {
  if (includeRelations) {
    const result = await db.query.outsourceOrderSchema.findFirst({
      where: and(
        eq(outsourceOrderSchema.id, id),
        eq(outsourceOrderSchema.ownerId, ownerId),
      ),
      with: {
        createdByUser: true as const,
        assignedToUser: true as const,
      },
    });

    return result || null;
  }

  const [outsourceOrder] = await db
    .select()
    .from(outsourceOrderSchema)
    .where(and(
      eq(outsourceOrderSchema.id, id),
      eq(outsourceOrderSchema.ownerId, ownerId),
    ))
    .limit(1);

  return outsourceOrder || null;
}

/**
 * Get all outsourceOrders for a user with pagination and filtering
 */
export async function getOutsourceOrdersByOwner(
  params: OutsourceOrderListParamsWithOwner,
): Promise<OutsourceOrderWithRelations[]> {
  const {
    ownerId,
    page = 1,
    limit = 10,
    search,
    sortBy = 'createdAt',
    sortOrder = 'desc',
  } = params;

  const conditions: SQL[] = [eq(outsourceOrderSchema.ownerId, ownerId)];

  // Add search conditions
  if (search) {
    conditions.push(
      or(
        ilike(outsourceOrderSchema.orderCode, `%${search}%`),
        ilike(outsourceOrderSchema.orderTitle, `%${search}%`),
      )!,
    );
  }

  const queryOptions = {
    where: and(...conditions),
    orderBy: [sortOrder === 'asc' ? asc(outsourceOrderSchema[sortBy]) : desc(outsourceOrderSchema[sortBy])],
    limit,
    offset: (page - 1) * limit,
    with: { createdByUser: true as const, assignedToUser: true as const },
  };

  const result = await db.query.outsourceOrderSchema.findMany(queryOptions);

  return result as OutsourceOrderWithRelations[];
}

/**
 * Delete outsourceOrder by ID
 */
export async function deleteOutsourceOrder(id: number, ownerId: string): Promise<boolean> {
  const result = await db
    .delete(outsourceOrderSchema)
    .where(and(
      eq(outsourceOrderSchema.id, id),
      eq(outsourceOrderSchema.ownerId, ownerId),
    ));

  return !!result;
}

/**
 * Get outsourceOrder statistics
 */
export async function getOutsourceOrderStats(ownerId: string): Promise<OutsourceOrderStats> {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const thisWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const thisMonth = new Date(now.getFullYear(), now.getMonth(), 1);

  const [total, todayCount, weekCount, monthCount] = await Promise.all([
    db
      .select({ count: count() })
      .from(outsourceOrderSchema)
      .where(eq(outsourceOrderSchema.ownerId, ownerId))
      .then(res => res[0]?.count || 0),

    db
      .select({ count: count() })
      .from(outsourceOrderSchema)
      .where(and(
        eq(outsourceOrderSchema.ownerId, ownerId),
        gte(outsourceOrderSchema.createdAt, today),
      ))
      .then(res => res[0]?.count || 0),

    db
      .select({ count: count() })
      .from(outsourceOrderSchema)
      .where(and(
        eq(outsourceOrderSchema.ownerId, ownerId),
        gte(outsourceOrderSchema.createdAt, thisWeek),
      ))
      .then(res => res[0]?.count || 0),

    db
      .select({ count: count() })
      .from(outsourceOrderSchema)
      .where(and(
        eq(outsourceOrderSchema.ownerId, ownerId),
        gte(outsourceOrderSchema.createdAt, thisMonth),
      ))
      .then(res => res[0]?.count || 0),
  ]);

  return {
    total,
    today: todayCount,
    thisWeek: weekCount,
    thisMonth: monthCount,
  };
}
