/**
 * PlanDetail database queries using Drizzle ORM with Relations Support
 * Enhanced version with proper error handling, type safety and relationships
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { and, asc, count, desc, eq, gte, ilike, or, type SQL } from 'drizzle-orm';

import { planDetailSchema, planSchema, productSchema, productSubSchema, workTableSchema } from '@/models/Schema';
import type {
  CreatePlanDetailInput,
  PlanDetailDb,
  PlanDetailListParamsWithOwner,
  PlanDetailStats,
  PlanDetailWithRelations,
  UpdatePlanDetailInput,
} from '@/types/plandetail';

import { db } from '../DB';

/**
 * Create a new plandetail with proper date and relation handling
 */
export async function createPlanDetail(data: CreatePlanDetailInput): Promise<PlanDetailDb> {
  // Validate foreign keys exist

  if (data.planId) {
    const planExists = await db
      .select({ id: planSchema.id })
      .from(planSchema)
      .where(eq(planSchema.id, data.planId))
      .limit(1);

    if (!planExists.length) {
      throw new Error('Plan not found');
    }
  }

  const [plandetail] = await db
    .insert(planDetailSchema)
    .values({
      locationCode: data.locationCode,
      locationType: data.locationType,
      productCode: data.productCode,
      productSubCode: data.productSubCode,
      plannedQuantity: data.plannedQuantity,
      actualQuantity: data.actualQuantity,
      plannedStartDate: data.plannedStartDate ? new Date(data.plannedStartDate) : null,
      plannedEndDate: data.plannedEndDate ? new Date(data.plannedEndDate) : null,
      actualStartDate: data.actualStartDate ? new Date(data.actualStartDate) : null,
      actualEndDate: data.actualEndDate ? new Date(data.actualEndDate) : null,
      status: data.status,
      priority: data.priority,
      note: data.note,
      ownerId: data.ownerId,
      planId: data.planId,
    } as any)
    .returning();

  if (!plandetail) {
    throw new Error('Failed to create plandetail');
  }

  return plandetail;
}

/**
 * Get plandetails by organization through plan relationship
 * Shows plandetails that belong to plans accessible by the organization
 */
export async function getPlanDetailsByOwner(
  params: PlanDetailListParamsWithOwner,
): Promise<PlanDetailDb[] | PlanDetailWithRelations[]> {
  const {
    ownerId: orgId, // ownerId is now actually orgId from the route
    page = 1,
    limit = 10,
    search,
    planCode,
    productCode,
    productName,
    sortBy = 'createdAt',
    sortOrder = 'desc',
    includeRelations = false,
  } = params;

  const offset = (page - 1) * limit;

  let baseQuery;
  if (includeRelations) {
    baseQuery = db.select({
      id: planDetailSchema.id,
      ownerId: planDetailSchema.ownerId,
      planId: planDetailSchema.planId,
      locationCode: planDetailSchema.locationCode,
      locationType: planDetailSchema.locationType,
      productCode: planDetailSchema.productCode,
      productSubCode: planDetailSchema.productSubCode,
      plannedQuantity: planDetailSchema.plannedQuantity,
      actualQuantity: planDetailSchema.actualQuantity,
      plannedStartDate: planDetailSchema.plannedStartDate,
      plannedEndDate: planDetailSchema.plannedEndDate,
      actualStartDate: planDetailSchema.actualStartDate,
      actualEndDate: planDetailSchema.actualEndDate,
      status: planDetailSchema.status,
      priority: planDetailSchema.priority,
      note: planDetailSchema.note,
      updatedAt: planDetailSchema.updatedAt,
      createdAt: planDetailSchema.createdAt,
      plan: {
        id: planSchema.id,
        planCode: planSchema.planCode,
      },
    }).from(planDetailSchema)
      .leftJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .leftJoin(productSchema, eq(planDetailSchema.productCode, productSchema.productCode));
  } else {
    baseQuery = db.select().from(planDetailSchema)
      .innerJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .leftJoin(productSchema, eq(planDetailSchema.productCode, productSchema.productCode));
  }

  // Build where conditions safely
  // Filter by plan's ownerId instead of plandetail's ownerId to get org-wide access
  const whereConditions: (SQL | undefined)[] = [eq(planSchema.ownerId, orgId)];

  if (search) {
    const searchTerm = `%${search}%`;
    const searchConditions: (SQL | undefined)[] = [
      ilike(planDetailSchema.locationCode, searchTerm),
      ilike(planDetailSchema.productSubCode, searchTerm),
    ];

    // Always include plan search since we now always JOIN with plan
    searchConditions.push(ilike(planSchema.planCode, searchTerm));
    searchConditions.push(ilike(planSchema.planName, searchTerm));

    const validSearchConditions = searchConditions.filter((c): c is SQL => !!c);
    if (validSearchConditions.length > 0) {
      whereConditions.push(or(...validSearchConditions));
    }
  }

  // Individual filter conditions
  if (planCode) {
    whereConditions.push(ilike(planSchema.planCode, `%${planCode}%`));
  }

  if (productCode) {
    whereConditions.push(ilike(planDetailSchema.productCode, `%${productCode}%`));
  }

  if (productName) {
    whereConditions.push(ilike(productSchema.productName, `%${productName}%`));
  }

  // Safe sorting with switch statement
  let orderBy;
  switch (sortBy) {
    case 'createdAt':
      orderBy = sortOrder === 'asc' ? asc(planDetailSchema.createdAt) : desc(planDetailSchema.createdAt);
      break;
    case 'updatedAt':
      orderBy = sortOrder === 'asc' ? asc(planDetailSchema.updatedAt) : desc(planDetailSchema.updatedAt);
      break;
    case 'productSubCode':
      orderBy = sortOrder === 'asc' ? asc(planDetailSchema.productSubCode) : desc(planDetailSchema.productSubCode);
      break;
    case 'locationCode':
      orderBy = sortOrder === 'asc' ? asc(planDetailSchema.locationCode) : desc(planDetailSchema.locationCode);
      break;
    default:
      orderBy = desc(planDetailSchema.createdAt);
  }

  const results = await baseQuery
    .where(and(...whereConditions.filter((c): c is SQL => !!c)))
    .orderBy(orderBy)
    .limit(limit)
    .offset(offset);

  if (includeRelations) {
    return results.map((result: any) => {
      const { plan, ...rest } = result as any;
      return { ...rest, plan: plan ?? undefined };
    });
  }

  return results;
}

/**
 * Get plandetail by ID with ownership check and relations
 */
export async function getPlanDetailById(
  id: number,
  orgId: string,
  includeRelations = false,
): Promise<PlanDetailDb | PlanDetailWithRelations | undefined> {
  let baseQuery;
  if (includeRelations) {
    baseQuery = db.select({
      id: planDetailSchema.id,
      ownerId: planDetailSchema.ownerId,
      planId: planDetailSchema.planId,
      locationCode: planDetailSchema.locationCode,
      locationType: planDetailSchema.locationType,
      productCode: planDetailSchema.productCode,
      productSubCode: planDetailSchema.productSubCode,
      plannedQuantity: planDetailSchema.plannedQuantity,
      actualQuantity: planDetailSchema.actualQuantity,
      plannedStartDate: planDetailSchema.plannedStartDate,
      plannedEndDate: planDetailSchema.plannedEndDate,
      actualStartDate: planDetailSchema.actualStartDate,
      actualEndDate: planDetailSchema.actualEndDate,
      status: planDetailSchema.status,
      priority: planDetailSchema.priority,
      note: planDetailSchema.note,
      updatedAt: planDetailSchema.updatedAt,
      createdAt: planDetailSchema.createdAt,
      plan: {
        id: planSchema.id,
        planCode: planSchema.planCode,
      },
    }).from(planDetailSchema)
      .leftJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .leftJoin(productSchema, eq(planDetailSchema.productCode, productSchema.productCode));
  } else {
    baseQuery = db.select().from(planDetailSchema)
      .innerJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .leftJoin(productSchema, eq(planDetailSchema.productCode, productSchema.productCode));
  }

  const [result] = await baseQuery
    .where(and(
      eq(planDetailSchema.id, id),
      eq(planSchema.ownerId, orgId),
    ))
    .limit(1);

  if (!result) {
    return undefined;
  }

  if (includeRelations) {
    const { plan, ...rest } = result as any;
    return { ...rest, plan: plan ?? undefined };
  }

  return result;
}

/**
 * Update plandetail with proper date handling, type safety and relations
 */
export async function updatePlanDetail(
  id: number,
  orgId: string,
  data: UpdatePlanDetailInput,
): Promise<PlanDetailDb> {
  // Get existing entity for conditional updates
  const existingPlanDetail = await getPlanDetailById(id, orgId);
  if (!existingPlanDetail) {
    throw new Error('PlanDetail not found or access denied');
  }

  // Build update data with proper type handling
  const updateData: Record<string, unknown> = {};

  if (data.planId !== undefined) {
    updateData.planId = data.planId;
  } else {
    updateData.planId = existingPlanDetail.planId;
  }

  if (data.locationCode !== undefined) {
    updateData.locationCode = data.locationCode;
  } else {
    updateData.locationCode = existingPlanDetail.locationCode;
  }

  if (data.locationType !== undefined) {
    updateData.locationType = data.locationType;
  } else {
    updateData.locationType = existingPlanDetail.locationType;
  }

  if (data.productCode !== undefined) {
    updateData.productCode = data.productCode;
  } else {
    updateData.productCode = existingPlanDetail.productCode;
  }

  if (data.productSubCode !== undefined) {
    updateData.productSubCode = data.productSubCode;
  } else {
    updateData.productSubCode = existingPlanDetail.productSubCode;
  }

  if (data.plannedQuantity !== undefined) {
    updateData.plannedQuantity = data.plannedQuantity;
  } else {
    updateData.plannedQuantity = existingPlanDetail.plannedQuantity;
  }

  if (data.actualQuantity !== undefined) {
    updateData.actualQuantity = data.actualQuantity;
  } else {
    updateData.actualQuantity = existingPlanDetail.actualQuantity;
  }

  if (data.plannedStartDate !== undefined) {
    updateData.plannedStartDate = data.plannedStartDate ? new Date(data.plannedStartDate) : null;
  } else {
    updateData.plannedStartDate = existingPlanDetail.plannedStartDate;
  }

  if (data.plannedEndDate !== undefined) {
    updateData.plannedEndDate = data.plannedEndDate ? new Date(data.plannedEndDate) : null;
  } else {
    updateData.plannedEndDate = existingPlanDetail.plannedEndDate;
  }

  if (data.actualStartDate !== undefined) {
    updateData.actualStartDate = data.actualStartDate ? new Date(data.actualStartDate) : null;
  } else {
    updateData.actualStartDate = existingPlanDetail.actualStartDate;
  }

  if (data.actualEndDate !== undefined) {
    updateData.actualEndDate = data.actualEndDate ? new Date(data.actualEndDate) : null;
  } else {
    updateData.actualEndDate = existingPlanDetail.actualEndDate;
  }

  if (data.status !== undefined) {
    updateData.status = data.status;
  } else {
    updateData.status = existingPlanDetail.status;
  }

  if (data.priority !== undefined) {
    updateData.priority = data.priority;
  } else {
    updateData.priority = existingPlanDetail.priority;
  }

  if (data.note !== undefined) {
    updateData.note = data.note;
  } else {
    updateData.note = existingPlanDetail.note;
  }

  const [updatedPlanDetail] = await db
    .update(planDetailSchema)
    .set(updateData as any)
    .where(eq(planDetailSchema.id, id))
    .returning();

  if (!updatedPlanDetail) {
    throw new Error('Failed to update plandetail');
  }

  return updatedPlanDetail;
}

/**
 * Delete plandetail with ownership check and cascade handling
 */
export async function deletePlanDetail(id: number, orgId: string): Promise<void> {
  // First check if plandetail exists and user has access through plan ownership
  const existingPlanDetail = await getPlanDetailById(id, orgId);
  if (!existingPlanDetail) {
    throw new Error('PlanDetail not found or access denied');
  }

  const result = await db
    .delete(planDetailSchema)
    .where(eq(planDetailSchema.id, id));

  if (!result) {
    throw new Error('Failed to delete PlanDetail');
  }
}

/**
 * Get relation options for dropdowns
 */
export async function getPlanDetailRelationOptions(): Promise<{
  plans: Array<{ id: number; planCode: string }>;
  products: Array<{ id: number; productCode: string; productName: string }>;
  locationCodes: Array<{ locationCode: string; tableName?: string }>;
  productSubCodes: Array<{ productSubCode: string; productSubDetail: string; productCode: string }>;
}> {
  try {
    // Get plans
    const planOptions = await db.select({
      id: planSchema.id,
      planCode: planSchema.planCode,
    }).from(planSchema).orderBy(asc(planSchema.planCode));

    // Get products
    const productOptions = await db.select({
      id: productSchema.id,
      productCode: productSchema.productCode,
      productName: productSchema.productName,
    }).from(productSchema).orderBy(asc(productSchema.productCode));

    // Get location codes from work tables
    const locationOptions = await db.select({
      locationCode: workTableSchema.locationCode,
      tableName: workTableSchema.tableName,
    }).from(workTableSchema)
      .orderBy(asc(workTableSchema.locationCode));

    // Get product sub codes
    const productSubOptions = await db.select({
      productSubCode: productSubSchema.productSubCode,
      productSubDetail: productSubSchema.productSubDetail,
      productCode: productSubSchema.productCode,
    }).from(productSubSchema).orderBy(asc(productSubSchema.productSubCode));

    return {
      plans: planOptions,
      products: productOptions,
      locationCodes: locationOptions.filter((item: any) => item.locationCode != null) as Array<{ locationCode: string; tableName?: string }>,
      productSubCodes: productSubOptions,
    };
  } catch (error) {
    console.error('Error fetching relation options:', error);
    return {
      plans: [],
      products: [],
      locationCodes: [],
      productSubCodes: [],
    };
  }
}

/**
 * Get plandetail statistics
 */
export async function getPlanDetailStats(orgId: string): Promise<PlanDetailStats> {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const thisWeekStart = new Date(today);
  thisWeekStart.setDate(today.getDate() - today.getDay());
  const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const [totalResult, todayResult, thisWeekResult, thisMonthResult] = await Promise.all([
    db.select({ count: count() })
      .from(planDetailSchema)
      .innerJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .where(eq(planSchema.ownerId, orgId)),
    db.select({ count: count() })
      .from(planDetailSchema)
      .innerJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .where(and(eq(planSchema.ownerId, orgId), gte(planDetailSchema.createdAt, today))),
    db.select({ count: count() })
      .from(planDetailSchema)
      .innerJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .where(and(eq(planSchema.ownerId, orgId), gte(planDetailSchema.createdAt, thisWeekStart))),
    db.select({ count: count() })
      .from(planDetailSchema)
      .innerJoin(planSchema, eq(planDetailSchema.planId, planSchema.id))
      .where(and(eq(planSchema.ownerId, orgId), gte(planDetailSchema.createdAt, thisMonthStart))),
  ]);

  return {
    total: totalResult[0]?.count ?? 0,
    today: todayResult[0]?.count ?? 0,
    thisWeek: thisWeekResult[0]?.count ?? 0,
    thisMonth: thisMonthResult[0]?.count ?? 0,
  };
}
