/**
 * EmployeeSalaryEntry Enhanced Relation Options API Route
 * Generated by enhanced entity generator script V4
 */

import { auth } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

import { getEmployeeSalaryEntryRelationOptions } from '@/libs/queries/employeeSalaryEntry';

// GET /api/employeeSalaryEntries/relations/options
export async function GET() {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const relationOptions = await getEmployeeSalaryEntryRelationOptions(orgId || userId);

    console.log(`🔍 [relation-options] ownerId: ${orgId || userId}, plans: ${relationOptions.plans.length}, products: ${relationOptions.products.length}`);

    return NextResponse.json({
      success: true,
      data: relationOptions,
      metadata: {
        totalOptions: relationOptions.userSyncs.length + relationOptions.productionStepDetails.length + relationOptions.plans.length,
        lastUpdated: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error('Error fetching relation options:', error);
    return NextResponse.json(
      { error: 'Failed to fetch relation options' },
      { status: 500 },
    );
  }
}
