/**
 * PlanDetail Single Item API Routes
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import {
  deletePlanDetail,
  getPlanDetailById,
  updatePlanDetail,
} from '@/libs/queries/plandetail';
import {
  validatePlanDetailId,
  validateUpdatePlanDetail,
} from '@/libs/validations/plandetail';

// GET /api/plandetails/[id]
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Use orgId for organization plandetails, fallback to userId for personal plandetails
    const ownerId = orgId || userId;

    const { id } = validatePlanDetailId({ id: params.id });
    const { searchParams } = new URL(request.url);
    const includeRelations = searchParams.get('includeRelations') === 'true';

    const plandetail = await getPlanDetailById(id, ownerId, includeRelations);

    if (!plandetail) {
      return NextResponse.json(
        { error: 'PlanDetail not found' },
        { status: 404 },
      );
    }

    return NextResponse.json({
      success: true,
      data: plandetail,
    });
  } catch (error) {
    console.error('Error fetching plandetail:', error);
    return NextResponse.json(
      { error: 'Failed to fetch plandetail' },
      { status: 500 },
    );
  }
}

// PUT /api/plandetails/[id]
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Use orgId for organization plandetails, fallback to userId for personal plandetails
    const ownerId = orgId || userId;

    const { id } = validatePlanDetailId({ id: params.id });
    const body = await request.json();
    const validatedData = validateUpdatePlanDetail(body);

    const plandetail = await updatePlanDetail(id, ownerId, validatedData);

    return NextResponse.json({
      success: true,
      data: plandetail,
      message: 'PlanDetail updated successfully',
    });
  } catch (error) {
    console.error('Error updating plandetail:', error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to update plandetail',
        code: 'UPDATE_ERROR',
      },
      { status: 400 },
    );
  }
}

// DELETE /api/plandetails/[id]
export async function DELETE(
  _request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Use orgId for organization plandetails, fallback to userId for personal plandetails
    const ownerId = orgId || userId;

    const { id } = validatePlanDetailId({ id: params.id });

    await deletePlanDetail(id, ownerId);

    return NextResponse.json({
      success: true,
      message: 'PlanDetail deleted successfully',
    });
  } catch (error) {
    console.error('Error deleting plandetail:', error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to delete plandetail',
        code: 'DELETE_ERROR',
      },
      { status: 400 },
    );
  }
}
