/**
 * PlanDetail API Routes with Relations Support
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import {
  createPlanDetail,
  getPlanDetailsByOwner,
} from '@/libs/queries/plandetail';
import {
  validateCreatePlanDetail,
  validatePlanDetailListParams,
} from '@/libs/validations/plandetail';

// GET /api/plandetails
export async function GET(request: NextRequest) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    
    // Use orgId for organization plandetails, fallback to userId for personal plandetails
    const ownerId = orgId || userId;

    const { searchParams } = new URL(request.url);
    const params = validatePlanDetailListParams({
      page: Number(searchParams.get('page')) || 1,
      limit: Number(searchParams.get('limit')) || 10,
      search: searchParams.get('search') || undefined,
      planCode: searchParams.get('planCode') || undefined,
      productCode: searchParams.get('productCode') || undefined,
      productName: searchParams.get('productName') || undefined,
      sortBy: searchParams.get('sortBy') || 'createdAt',
      sortOrder: searchParams.get('sortOrder') || 'desc',
      includeRelations: searchParams.get('includeRelations') === 'true',
    });


    const plandetails = await getPlanDetailsByOwner({
      ...params,
      ownerId,
    });

    // Get total count for pagination
    const total = await getPlanDetailsByOwner({
      ...params,
      ownerId,
      page: 1,
      limit: 999999,
    });

    return NextResponse.json({
      success: true,
      data: plandetails,
      pagination: {
        page: params.page,
        limit: params.limit,
        total: Array.isArray(total) ? total.length : 0,
        hasMore: Array.isArray(plandetails) && plandetails.length === params.limit,
      },
    });
  } catch (error) {
    console.error('Error fetching plandetails:', error);
    return NextResponse.json(
      { error: 'Failed to fetch plandetails' },
      { status: 500 },
    );
  }
}

// POST /api/plandetails
export async function POST(request: NextRequest) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    
    // Use orgId for organization plandetails, fallback to userId for personal plandetails
    const ownerId = orgId || userId;

    const body = await request.json();
    const validatedData = validateCreatePlanDetail({
      ...body,
      ownerId,
    });

    const plandetail = await createPlanDetail(validatedData);

    return NextResponse.json({
      success: true,
      data: plandetail,
      message: 'PlanDetail created successfully',
    });
  } catch (error) {
    console.error('Error creating plandetail:', error);
    
    // Check if it's a unique constraint violation
    if (error && typeof error === 'object' && 'code' in error && error.code === '23505') {
      return NextResponse.json(
        {
          error: 'Đã tồn tại Plan Detail với cùng Kế hoạch, Vị trí và Phân loại sản phẩm này',
          code: 'DUPLICATE_ENTRY',
        },
        { status: 400 },
      );
    }
    
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to create plandetail',
        code: 'CREATE_ERROR',
      },
      { status: 400 },
    );
  }
}
