/**
 * OutsourceOrder validation schemas with Relations Support
 * Enhanced version with proper error handling, type safety and relationships
 * Generated by enhanced entity generator script V4 (improved)
 */

import { z } from 'zod';

// Enhanced validation with custom error messages and regex patterns
export const outsourceOrderFormSchema = z.object({
  orderCode: z.string().trim().min(1, 'Order Code is required').max(50, 'Order Code must be 50 characters or less').regex(/^[\w-]+$/, 'Order Code can only contain letters, numbers, underscores and dashes'),
  orderTitle: z.string().trim().max(200, 'Order Title must be 200 characters or less').optional(),
  createdByUserId: z.string().min(1, 'Created By is required'),
  assignedToUserId: z.string().min(1, 'Assigned To is required'),
  orderDate: z.preprocess(
    val => typeof val === 'string' ? new Date(val) : val,
    z.date({ required_error: 'Order Date is required', invalid_type_error: 'Invalid date' }),
  ),
  expectedCompletionDate: z.preprocess(
    val => val === undefined || val === '' ? undefined : (typeof val === 'string' ? new Date(val) : val),
    z.date({ invalid_type_error: 'Invalid date' }).optional(),
  ),
  actualCompletionDate: z.preprocess(
    val => val === undefined || val === '' ? undefined : (typeof val === 'string' ? new Date(val) : val),
    z.date({ invalid_type_error: 'Invalid date' }).optional(),
  ),
  status: z.string().trim().optional(),
  priority: z.number().int().optional(),
  totalAmount: z.preprocess(
    (val) => {
      // Handle empty string, null, undefined
      if (val === undefined || val === null || val === '') {
        return undefined;
      }
      // Handle whitespace-only strings
      if (typeof val === 'string' && val.trim() === '') {
        return undefined;
      }
      // Convert to number
      const num = Number(val);
      // Return undefined if conversion results in NaN
      return Number.isNaN(num) ? undefined : num;
    },
    z.number().min(0, 'Value cannot be negative').optional(),
  ),
  currency: z.string().trim().max(10, 'Currency must be 10 characters or less').optional(),
  notes: z.string().trim().optional(),
  attachment: z.string().trim().optional(),
  applyRetailPrice: z.preprocess(
    (val) => {
      // Convert string to number if needed
      if (typeof val === 'string') {
        const num = parseInt(val, 10);
        return Number.isNaN(num) ? undefined : num;
      }
      return val;
    },
    z.number().int().min(2).max(3)
  ),
});

// Create outsourceOrder schema (same as form + ownerId)
export const createOutsourceOrderSchema = outsourceOrderFormSchema.extend({
  ownerId: z.string().min(1, 'Owner ID is required'),
});

// Update outsourceOrder schema (all fields optional except ID validation)
export const updateOutsourceOrderSchema = z.object({
  orderCode: z.string().trim().max(50, 'Order Code must be 50 characters or less').regex(/^[\w-]+$/, 'Order Code can only contain letters, numbers, underscores and dashes').optional(),
  orderTitle: z.string().trim().max(200, 'Order Title must be 200 characters or less').optional(),
  createdByUserId: z.string().optional(),
  assignedToUserId: z.string().optional(),
  orderDate: z.preprocess(
    val => typeof val === 'string' ? new Date(val) : val,
    z.date({ invalid_type_error: 'Invalid date' }).optional(),
  ),
  expectedCompletionDate: z.preprocess(
    val => val === undefined || val === '' ? undefined : (typeof val === 'string' ? new Date(val) : val),
    z.date({ invalid_type_error: 'Invalid date' }).optional(),
  ),
  actualCompletionDate: z.preprocess(
    val => val === undefined || val === '' ? undefined : (typeof val === 'string' ? new Date(val) : val),
    z.date({ invalid_type_error: 'Invalid date' }).optional(),
  ),
  status: z.string().trim().optional(),
  priority: z.number().int().optional(),
  totalAmount: z.preprocess(
    (val) => {
      // Handle empty string, null, undefined
      if (val === undefined || val === null || val === '') {
        return undefined;
      }
      // Handle whitespace-only strings
      if (typeof val === 'string' && val.trim() === '') {
        return undefined;
      }
      // Convert to number
      const num = Number(val);
      // Return undefined if conversion results in NaN
      return Number.isNaN(num) ? undefined : num;
    },
    z.number().min(0, 'Value cannot be negative').optional(),
  ),
  currency: z.string().trim().max(10, 'Currency must be 10 characters or less').optional(),
  notes: z.string().trim().optional(),
  attachment: z.string().trim().optional(),
  applyRetailPrice: z.preprocess(
    (val) => {
      // Convert string to number if needed
      if (typeof val === 'string') {
        const num = parseInt(val, 10);
        return Number.isNaN(num) ? undefined : num;
      }
      return val;
    },
    z.number().int().min(2).max(3)
  ).optional(),
});

// List parameters validation
export const outsourceOrderListParamsSchema = z.object({
  page: z.number().int().min(1).default(1),
  limit: z.number().int().min(1).max(100).default(10),
  search: z.string().optional(),
  sortBy: z.enum(['createdAt', 'updatedAt', 'orderTitle', 'orderCode']).default('createdAt'),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
  includeRelations: z.boolean().default(false),
  showAll: z.boolean().default(false),
});

// Export parameters validation
export const outsourceOrderExportParamsSchema = outsourceOrderListParamsSchema.extend({
  format: z.enum(['xlsx', 'csv']).default('xlsx'),
  includeHeaders: z.boolean().default(true),
  filename: z.string().optional(),
});

// Import validation
export const importOutsourceOrderSchema = z.object({
  file: z.instanceof(File),
  skipDuplicates: z.boolean().default(true),
  validateRelations: z.boolean().default(true),
  dryRun: z.boolean().default(false),
});

// Filter validation schemas
export const outsourceOrderFiltersSchema = z.object({
  search: z.string().default(''),
  sortBy: z.enum(['createdAt', 'updatedAt', 'orderTitle', 'orderCode']).default('createdAt'),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
  status: z.string().optional(),
  priority: z.number().int().min(1).max(10).optional(),
  dateRange: z.object({
    start: z.date(),
    end: z.date(),
  }).optional(),
  relations: z.record(z.any()).optional(),
});

export function validateOutsourceOrderFilters(data: unknown) {
  return outsourceOrderFiltersSchema.safeParse(data);
}

// Validation helper functions
export function validateOutsourceOrderFormData(data: unknown) {
  return outsourceOrderFormSchema.safeParse(data);
}

export function validateCreateOutsourceOrder(data: unknown) {
  return createOutsourceOrderSchema.safeParse(data);
}

export function validateUpdateOutsourceOrder(data: unknown) {
  return updateOutsourceOrderSchema.safeParse(data);
}

export function validateOutsourceOrderListParams(data: unknown) {
  return outsourceOrderListParamsSchema.safeParse(data);
}

export function validateOutsourceOrderExportParams(data: unknown) {
  return outsourceOrderExportParamsSchema.safeParse(data);
}

// Custom validation rules
export const outsourceOrderValidationRules = {
  // Field-specific rules
  orderCodePattern: /^[\w-]+$/,
  orderDateRange: { min: new Date('1900-01-01'), max: new Date('2100-12-31') },
  expectedCompletionDateRange: { min: new Date('1900-01-01'), max: new Date('2100-12-31') },
  actualCompletionDateRange: { min: new Date('1900-01-01'), max: new Date('2100-12-31') },
  priorityRange: { min: 1, max: 10 },

  // Business logic validation
  validateBusinessRules: (data: any): string[] => {
    const errors: string[] = [];

    // Add custom business logic validation here
    // Example: Date validation
    if (data.plannedStartDate && data.plannedEndDate) {
      if (new Date(data.plannedStartDate) > new Date(data.plannedEndDate)) {
        errors.push('Planned start date must be before planned end date');
      }
    }

    if (data.actualStartDate && data.actualEndDate) {
      if (new Date(data.actualStartDate) > new Date(data.actualEndDate)) {
        errors.push('Actual start date must be before actual end date');
      }
    }

    // Example: Quantity validation
    if (data.actualQuantity && data.plannedQuantity) {
      if (data.actualQuantity > data.plannedQuantity * 1.5) {
        errors.push('Actual quantity significantly exceeds planned quantity');
      }
    }

    return errors;
  },
};
