/**
 * PlanDetail validation schemas with Relations Support
 * Enhanced version with proper error handling, type safety and relationships
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { z } from 'zod';

// Form validation schema with relations
export const plandetailFormSchema = z.object({
  planId: z.number().int().positive(),
  locationCode: z.string().trim().min(1, 'Location Code is required').max(50, 'Location Code must be 50 characters or less').regex(/^[\w-]+$/, 'Location Code can only contain letters, numbers, underscores and dashes'),
  locationType: z.string().trim().max(50, 'Location Type must be 50 characters or less').optional(),
  productCode: z.string().trim().min(1, 'Product Code is required').max(50, 'Product Code must be 50 characters or less').regex(/^[\w-]+$/, 'Product Code can only contain letters, numbers, underscores and dashes'),
  productSubCode: z.string().trim().max(100, 'Product Sub Code must be 100 characters or less').regex(/^[\w-]*$/, 'Product Sub Code can only contain letters, numbers, underscores and dashes').optional(),
  plannedQuantity: z.number().int().min(0),
  actualQuantity: z.number().int().min(0).optional(),
  plannedStartDate: z.union([z.string(), z.date()]).optional(),
  plannedEndDate: z.union([z.string(), z.date()]).optional(),
  actualStartDate: z.union([z.string(), z.date()]).optional(),
  actualEndDate: z.union([z.string(), z.date()]).optional(),
  status: z.string().trim().max(50, 'Status must be 50 characters or less').optional(),
  priority: z.number().int().min(1).max(10).optional(),
  note: z.string().trim().optional(),
});

// Create plandetail schema (same as form + ownerId)
export const createPlanDetailSchema = plandetailFormSchema.extend({
  ownerId: z.string().min(1, 'Owner ID is required'),
});

// Update plandetail schema (all fields optional)
export const updatePlanDetailSchema = z.object({
  planId: z.number().int().positive().optional(),
  locationCode: z.string().trim().min(1, 'Location Code is required').max(50, 'Location Code must be 50 characters or less').regex(/^[\w-]+$/, 'Location Code can only contain letters, numbers, underscores and dashes').optional(),
  locationType: z.string().trim().max(50, 'Location Type must be 50 characters or less').optional(),
  productCode: z.string().trim().min(1, 'Product Code is required').max(50, 'Product Code must be 50 characters or less').regex(/^[\w-]+$/, 'Product Code can only contain letters, numbers, underscores and dashes').optional(),
  productSubCode: z.string().trim().max(100, 'Product Sub Code must be 100 characters or less').regex(/^[\w-]*$/, 'Product Sub Code can only contain letters, numbers, underscores and dashes').optional(),
  plannedQuantity: z.number().int().min(0).optional(),
  actualQuantity: z.number().int().min(0).optional(),
  plannedStartDate: z.union([z.string(), z.date()]).optional(),
  plannedEndDate: z.union([z.string(), z.date()]).optional(),
  actualStartDate: z.union([z.string(), z.date()]).optional(),
  actualEndDate: z.union([z.string(), z.date()]).optional(),
  status: z.string().trim().max(50, 'Status must be 50 characters or less').optional(),
  priority: z.number().int().min(1).max(10).optional(),
  note: z.string().trim().optional(),
});

// List parameters validation
export const plandetailListParamsSchema = z.object({
  page: z.number().int().min(1).default(1),
  limit: z.number().int().min(1).max(100).default(10),
  search: z.string().trim().max(255).optional(),
  planCode: z.string().trim().max(255).optional(),
  productCode: z.string().trim().max(255).optional(),
  productName: z.string().trim().max(255).optional(),
  sortBy: z.enum(['createdAt', 'updatedAt', 'productSubCode', 'locationCode']).default('createdAt'),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
  showAll: z.boolean().default(false),
  includeRelations: z.boolean().default(false),
});

// Export parameters validation
export type PlanDetailExportParams = z.infer<typeof plandetailListParamsSchema>;

// Import row validation for Excel import with relations
export const importPlanDetailRowSchema = z.object({
  planId: z.number().int().positive(),
  locationCode: z.string().trim().min(1, 'Location Code is required').max(50, 'Location Code must be 50 characters or less').regex(/^[\w-]+$/, 'Location Code can only contain letters, numbers, underscores and dashes'),
  locationType: z.string().trim().max(50, 'Location Type must be 50 characters or less').optional(),
  productCode: z.string().trim().min(1, 'Product Code is required').max(50, 'Product Code must be 50 characters or less').regex(/^[\w-]+$/, 'Product Code can only contain letters, numbers, underscores and dashes'),
  productSubCode: z.string().trim().max(100, 'Product Sub Code must be 100 characters or less').regex(/^[\w-]*$/, 'Product Sub Code can only contain letters, numbers, underscores and dashes').optional(),
  plannedQuantity: z.number().int().min(0),
  actualQuantity: z.number().int().min(0).optional(),
  plannedStartDate: z.union([z.string(), z.date()]).optional(),
  plannedEndDate: z.union([z.string(), z.date()]).optional(),
  actualStartDate: z.union([z.string(), z.date()]).optional(),
  actualEndDate: z.union([z.string(), z.date()]).optional(),
  status: z.string().trim().max(50, 'Status must be 50 characters or less').optional(),
  priority: z.number().int().min(1).max(10).optional(),
  note: z.string().trim().optional(),
  rowNumber: z.number().int().positive(),
});

// ID validation
export const plandetailIdSchema = z.object({
  id: z.string().regex(/^\d+$/, 'ID must be a valid number').transform(Number),
});

// Validation helper functions
export function validatePlanDetailId(data: unknown) {
  return plandetailIdSchema.parse(data);
}

export function validatePlanDetailForm(data: unknown) {
  return plandetailFormSchema.parse(data);
}

export function validateCreatePlanDetail(data: unknown) {
  return createPlanDetailSchema.parse(data);
}

export function validateUpdatePlanDetail(data: unknown) {
  return updatePlanDetailSchema.parse(data);
}

export function validatePlanDetailListParams(data: unknown) {
  return plandetailListParamsSchema.parse(data);
}
