/**
 * OutsourceOrder Export API Route
 * Generated by enhanced entity generator script V4 (improved)
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';
import * as XLSX from 'xlsx';

import { getOutsourceOrdersByOwner } from '@/libs/queries/outsourceOrder';
import { validateOutsourceOrderExportParams } from '@/libs/validations/outsourceOrder';

// GET /api/outsourceOrders/export
export async function GET(request: NextRequest) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized', code: 'AUTH_REQUIRED' },
        { status: 401 },
      );
    }

    const { searchParams } = new URL(request.url);
    const rawParams = {
      page: 1,
      limit: 999999, // Export all
      search: searchParams.get('search') || undefined,
      sortBy: searchParams.get('sortBy') || 'createdAt',
      sortOrder: searchParams.get('sortOrder') || 'desc',
      format: searchParams.get('format') || 'xlsx',
      includeHeaders: searchParams.get('includeHeaders') !== 'false',
      filename: searchParams.get('filename') || undefined,
    };

    const validation = validateOutsourceOrderExportParams(rawParams);
    if (!validation.success) {
      return NextResponse.json(
        {
          success: false,
          error: 'Invalid export parameters',
          code: 'VALIDATION_ERROR',
          details: validation.error.errors,
        },
        { status: 400 },
      );
    }

    // Use orgId for organization outsource orders, fallback to userId for personal outsource orders
    const ownerId = orgId || userId;

    const params = validation.data;
    const outsourceOrders = await getOutsourceOrdersByOwner({
      ...params,
      ownerId,
      userId,
      includeRelations: true,
    });

    // Prepare data for export
    const exportData = outsourceOrders.map(item => ({
      'Order Code': item.orderCode || '',
      'Order Title': item.orderTitle || '',
      'User Full Name': item.userSync?.fullName || '',
      'Order Date': item.orderDate || '',
      'Expected Completion Date': item.expectedCompletionDate || '',
      'Actual Completion Date': item.actualCompletionDate || '',
      'Status': item.status || '',
      'Priority': item.priority || '',
      'Total Amount': item.totalAmount || '',
      'Currency': item.currency || '',
      'Notes': item.notes || '',
      'Attachment': item.attachment || '',
      'Created At': item.createdAt,
      'Updated At': item.updatedAt,
    }));

    // Create workbook
    const workbook = XLSX.utils.book_new();
    const worksheet = XLSX.utils.json_to_sheet(exportData);

    // Set column widths
    const columnWidths = Object.keys(exportData[0] || {}).map(() => ({ width: 20 }));
    worksheet['!cols'] = columnWidths;

    XLSX.utils.book_append_sheet(workbook, worksheet, 'OutsourceOrders');

    // Generate buffer
    const buffer = XLSX.write(workbook, {
      type: 'buffer',
      bookType: params.format as 'xlsx' | 'csv',
    });

    // Set response headers
    const filename = params.filename
      || `outsourceOrders-${new Date().toISOString().split('T')[0]}.${params.format}`;

    const mimeType = params.format === 'csv'
      ? 'text/csv'
      : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

    return new NextResponse(buffer, {
      headers: {
        'Content-Type': mimeType,
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': buffer.length.toString(),
      },
    });
  } catch (error) {
    console.error('GET /api/outsourceOrders/export error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Export failed',
        code: 'EXPORT_ERROR',
      },
      { status: 500 },
    );
  }
}
