/**
 * OutsourceOrder List Component with Enhanced Features
 * Generated by enhanced entity generator script V4 (improved)
 */

'use client';

import {
  Download,
  Edit,
  Eye,
  Plus,
  RefreshCw,
  Search,
  Trash2,
} from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { useOutsourceOrderExport } from '@/hooks/useOutsourceOrderExport';
import { useOutsourceOrderFilters } from '@/hooks/useOutsourceOrderFilters';
import { useDeleteOutsourceOrder } from '@/hooks/useOutsourceOrderMutations';
import { useOutsourceOrders, useOutsourceOrderStats } from '@/hooks/useOutsourceOrders';
import type { OutsourceOrderFormData, OutsourceOrderWithRelations } from '@/types/outsourceOrder';

import { OutsourceOrderForm } from './OutsourceOrderForm';
import { OutsourceOrderSkeleton } from './OutsourceOrderSkeleton';

function toFormData(item: OutsourceOrderWithRelations | null): OutsourceOrderFormData | undefined {
  if (!item) {
    return undefined;
  }
  return {
    orderCode: item.orderCode ?? '',
    orderTitle: item.orderTitle ?? undefined,
    createdByUserId: item.createdByUserId ?? '',
    assignedToUserId: item.assignedToUserId ?? '',
    orderDate: item.orderDate ?? '',
    expectedCompletionDate: item.expectedCompletionDate ?? undefined,
    actualCompletionDate: item.actualCompletionDate ?? undefined,
    status: item.status ?? '',
    priority: typeof item.priority === 'number' ? item.priority : 0,
    totalAmount: typeof item.totalAmount === 'number' ? item.totalAmount : (item.totalAmount ? Number(item.totalAmount) : undefined),
    currency: item.currency ?? undefined,
    notes: item.notes ?? undefined,
    attachment: item.attachment ?? undefined,
  };
}

export function OutsourceOrderList() {
  const t = useTranslations('outsourceOrder.list');
  const router = useRouter();
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingItem, setEditingItem] = useState<OutsourceOrderWithRelations | null>(null);

  const { filters, setSearch, resetFilters, hasActiveFilters } = useOutsourceOrderFilters();

  const {
    data: outsourceOrders = [],
    isLoading,
    error,
    refetch,
  } = useOutsourceOrders({ ...filters, includeRelations: true });

  const { data: stats } = useOutsourceOrderStats();
  const deleteMutation = useDeleteOutsourceOrder();

  const { exportData, isExporting } = useOutsourceOrderExport();

  const handleEdit = (item: OutsourceOrderWithRelations) => {
    setEditingItem(item);
    setIsFormOpen(true);
  };

  const handleViewDetails = (item: OutsourceOrderWithRelations) => {
    router.push(`/dashboard/outsourceOrders/${item.id}/details`);
  };

  const handleDelete = async (id: number) => {
    try {
      await deleteMutation.mutateAsync(id);
      setDeleteId(null);
    } catch (error) {
      console.error('Delete error:', error);
    }
  };

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center rounded bg-white p-6 py-8 shadow">
        <p className="mb-4 text-destructive">
          {t('error_loading')}
          {error.message}
        </p>
        <Button onClick={() => refetch()} variant="outline">
          <RefreshCw className="mr-2 size-4" />
          {t('retry')}
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with Stats */}
      {stats && (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-4">
          <div className="rounded bg-white p-4 shadow">
            <div className="text-2xl font-bold">{stats.total}</div>
            <p className="text-xs text-muted-foreground">{t('total')}</p>
          </div>
          <div className="rounded bg-white p-4 shadow">
            <div className="text-2xl font-bold">{stats.today}</div>
            <p className="text-xs text-muted-foreground">{t('created_today')}</p>
          </div>
          <div className="rounded bg-white p-4 shadow">
            <div className="text-2xl font-bold">{stats.thisWeek}</div>
            <p className="text-xs text-muted-foreground">{t('this_week')}</p>
          </div>
          <div className="rounded bg-white p-4 shadow">
            <div className="text-2xl font-bold">{stats.thisMonth}</div>
            <p className="text-xs text-muted-foreground">{t('this_month')}</p>
          </div>
        </div>
      )}

      {/* Controls */}
      <div className="mt-4 rounded bg-white p-6 shadow">
        <div className="mb-4 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center">
          <h2 className="text-lg font-bold">{t('title')}</h2>
          <div className="flex gap-2">

            <Button
              variant="outline"
              size="sm"
              onClick={() => exportData()}
              disabled={isExporting}
            >
              <Download className="mr-2 size-4" />
              {t('export')}
            </Button>

            <Button onClick={() => setIsFormOpen(true)}>
              <Plus className="mr-2 size-4" />
              {t('add')}
            </Button>
          </div>
        </div>

        <div>
          {/* Search and Filters */}
          <div className="mb-4 flex gap-4">

            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-gray-400" />
                <Input
                  placeholder={t('search_placeholder')}
                  value={filters.search}
                  onChange={e => setSearch(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>

            {hasActiveFilters && (
              <Button variant="outline" onClick={resetFilters}>
                {t('clear_filters')}
              </Button>
            )}
          </div>

          {/* Table */}
          {isLoading
            ? (
                <OutsourceOrderSkeleton />
              )
            : (
                <Table>
                  <TableHeader>
                    <TableRow>

                      <TableHead>{t('table.order_code')}</TableHead>
                      <TableHead>{t('table.created_by')}</TableHead>
                      <TableHead>{t('table.assigned_to')}</TableHead>
                      <TableHead>{t('table.order_date')}</TableHead>
                      <TableHead className="w-32">{t('table.actions')}</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {outsourceOrders.map(item => (
                      <TableRow key={item.id}>

                        <TableCell className="font-medium">
                          {item.orderCode}
                        </TableCell>
                        <TableCell>{item.createdByUser?.fullName || item.createdByUserId}</TableCell>
                        <TableCell>{item.assignedToUser?.fullName || item.assignedToUserId}</TableCell>
                        <TableCell>
                          {item.orderDate ? new Date(item.orderDate).toLocaleDateString() : '-'}
                        </TableCell>
                        <TableCell>
                          <div className="flex gap-1">
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleViewDetails(item)}
                              className="size-8 p-0"
                              title="View Details"
                            >
                              <Eye className="size-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => handleEdit(item)}
                              className="size-8 p-0"
                            >
                              <Edit className="size-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => setDeleteId(item.id)}
                              className="size-8 p-0 text-destructive hover:text-destructive"
                            >
                              <Trash2 className="size-4" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}

          {outsourceOrders.length === 0 && !isLoading && (
            <div className="py-8 text-center text-muted-foreground">
              {t('empty')}
            </div>
          )}
        </div>
      </div>

      {/* Form Modal */}
      {isFormOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="m-4 max-h-[90vh] w-full max-w-2xl overflow-auto rounded-lg bg-white">
            <OutsourceOrderForm
              outsourceOrder={toFormData(editingItem)}
              isEditing={!!editingItem}
              onSuccess={() => {
                setIsFormOpen(false);
                setEditingItem(null);
                refetch();
              }}
              onCancel={() => {
                setIsFormOpen(false);
                setEditingItem(null);
              }}
            />
          </div>
        </div>
      )}

      {/* Delete Confirmation */}
      {deleteId && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
          <div className="w-full max-w-md rounded-lg bg-white p-6">
            <h3 className="mb-2 text-lg font-bold">{t('delete_confirm_title')}</h3>
            <p className="mb-4">{t('delete_confirm_desc')}</p>
            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => setDeleteId(null)}>{t('cancel')}</Button>
              <Button className="bg-destructive text-destructive-foreground" onClick={() => deleteId && handleDelete(deleteId)}>{t('delete')}</Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
