/**
 * OutsourceOrder Form Component with Enhanced Features
 * Generated by enhanced entity generator script V4 (improved)
 */

'use client';

import { useAuth } from '@clerk/nextjs';
import { zodResolver } from '@hookform/resolvers/zod';
import { Loader2, Save, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useForm } from 'react-hook-form';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useCreateOutsourceOrder, useUpdateOutsourceOrder } from '@/hooks/useOutsourceOrderMutations';
import { useOutsourceOrderRelationOptions } from '@/hooks/useOutsourceOrders';
import { outsourceOrderFormSchema } from '@/libs/validations/outsourceOrder';
import type { OutsourceOrderFormData } from '@/types/outsourceOrder';

type OutsourceOrderFormProps = {
  outsourceOrder?: OutsourceOrderFormData;
  isEditing?: boolean;
  onSuccess?: () => void;
  onCancel?: () => void;
};

export function OutsourceOrderForm({
  outsourceOrder,
  isEditing = false,
  onSuccess,
  onCancel,
}: OutsourceOrderFormProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { userId } = useAuth();

  const createMutation = useCreateOutsourceOrder();
  const updateMutation = useUpdateOutsourceOrder();
  const { data: relationOptions, isLoading: isLoadingOptions } = useOutsourceOrderRelationOptions();

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
    reset,
  } = useForm<OutsourceOrderFormData>({
    resolver: zodResolver(outsourceOrderFormSchema),
    defaultValues: (outsourceOrder as OutsourceOrderFormData) || {
      orderCode: '',
      orderTitle: '',
      orderDate: new Date().toISOString().slice(0, 10),
      expectedCompletionDate: (() => {
        const d = new Date();
        d.setDate(d.getDate() + 30);
        return d.toISOString().slice(0, 10);
      })(),
      actualCompletionDate: undefined,
      status: '',
      priority: 0,
      totalAmount: undefined,
      currency: '',
      notes: '',
      attachment: '',
      createdByUserId: outsourceOrder?.createdByUserId || userId || '',
      assignedToUserId: '',
    },
    mode: 'onChange',
  });

  // Format dates for edit mode
  useEffect(() => {
    if (outsourceOrder && isEditing) {
      const formatDate = (date: any) => {
        if (!date) {
          return '';
        }
        const d = new Date(date);
        return d.toISOString().slice(0, 10);
      };

      // Reset form with properly formatted dates
      reset({
        ...outsourceOrder,
        orderDate: formatDate(outsourceOrder.orderDate),
        expectedCompletionDate: formatDate(outsourceOrder.expectedCompletionDate),
        actualCompletionDate: formatDate(outsourceOrder.actualCompletionDate),
        totalAmount: outsourceOrder.totalAmount !== undefined && outsourceOrder.totalAmount !== null ? Number(outsourceOrder.totalAmount) : undefined,
        priority: typeof outsourceOrder.priority === 'number' ? outsourceOrder.priority : 0,
      });
    }
  }, [outsourceOrder, isEditing, reset]);

  const onSubmit = async (data: OutsourceOrderFormData) => {
    setIsSubmitting(true);

    // Chuyển các trường ngày về Date nếu là string
    const toDate = (d: string | Date | undefined) => (typeof d === 'string' ? new Date(d) : d);
    const submitData = {
      ...data,
      orderDate: toDate(data.orderDate) ?? new Date(),
      expectedCompletionDate: toDate(data.expectedCompletionDate),
      actualCompletionDate: toDate(data.actualCompletionDate),
    };

    try {
      if (isEditing && outsourceOrder && 'id' in outsourceOrder) {
        await updateMutation.mutateAsync({
          id: (outsourceOrder as any).id,
          data: submitData,
        });
      } else {
        await createMutation.mutateAsync(submitData);
      }

      reset();
      onSuccess?.();
    } catch (error) {
      console.error('Form submission error:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancel = () => {
    reset();
    onCancel?.();
  };

  // Xử lý giá trị ngày tháng: chuyển '' thành undefined để tránh lỗi Invalid datetime
  const handleDateChange = (field: keyof OutsourceOrderFormData) => (e: React.ChangeEvent<HTMLInputElement>) => {
    setValue(field, e.target.value === '' ? undefined : e.target.value);
  };

  // Hàm sinh mã Order Code
  function generateOrderCode(fullName: string): string {
    if (!fullName) {
      return '';
    }
    const initials = fullName
      .split(' ')
      .filter(Boolean)
      .map(word => word?.[0]?.toUpperCase() || '')
      .join('');
    const now = new Date();
    const dd = String(now.getDate()).padStart(2, '0');
    const mm = String(now.getMonth() + 1).padStart(2, '0');
    const hh = String(now.getHours()).padStart(2, '0');
    const min = String(now.getMinutes()).padStart(2, '0');
    return `${initials}${dd}${mm}${hh}${min}`;
  }

  return (
    <div className="mx-auto w-full max-w-2xl rounded bg-white p-6 shadow">
      <div className="mb-4 border-b pb-2">
        <h2 className="text-xl font-bold">
          {isEditing ? `Edit ${outsourceOrder?.orderTitle || 'OutsourceOrder'}` : 'Create New OutsourceOrder'}
        </h2>
      </div>
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Error display */}
        {(createMutation.error || updateMutation.error) && (
          <div className="rounded bg-red-100 p-2 text-red-700">
            {createMutation.error?.message || updateMutation.error?.message}
          </div>
        )}

        {/* Assigned To */}
        <div className="space-y-2">
          <Label htmlFor="assignedToUserId">Assigned To *</Label>

          {isLoadingOptions
            ? (
                <div className="h-10 animate-pulse rounded bg-muted" />
              )
            : (
                <Select
                  value={watch('assignedToUserId') || ''}
                  onValueChange={(value) => {
                    setValue('assignedToUserId', value, { shouldValidate: true });
                    const user = relationOptions?.userSyncs?.find((u: { userId: string; fullName: string }) => u.userId === value);
                    if (user && user.fullName) {
                      setValue('orderCode', generateOrderCode(user.fullName), { shouldValidate: true });
                    }
                  }}
                >
                  <SelectTrigger className={errors.assignedToUserId ? 'border-destructive' : ''}>
                    <SelectValue placeholder="Select assigned to..." />
                  </SelectTrigger>
                  <SelectContent>
                    {relationOptions?.userSyncs?.map((option: { userId: string; fullName: string }) => (
                      <SelectItem key={option.userId} value={option.userId}>
                        {option.fullName}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
          {errors.assignedToUserId && (
            <p className="text-sm text-destructive">{errors.assignedToUserId?.message}</p>
          )}
        </div>

        {/* Order Code */}
        <div className="space-y-2">
          <Label htmlFor="orderCode">Order Code *</Label>
          <Input
            id="orderCode"
            type="text"
            placeholder="Enter order code..."
            {...register('orderCode')}
            className={errors.orderCode ? 'border-destructive' : ''}
          />
          {errors.orderCode && (
            <p className="text-sm text-destructive">{errors.orderCode?.message}</p>
          )}
        </div>
        {/* Order Title */}
        <div className="space-y-2">
          <Label htmlFor="orderTitle">Order Title</Label>
          <Input
            id="orderTitle"
            type="text"
            placeholder="Enter order title..."
            {...register('orderTitle')}
            className={errors.orderTitle ? 'border-destructive' : ''}
          />
          {errors.orderTitle && (
            <p className="text-sm text-destructive">{errors.orderTitle?.message}</p>
          )}
        </div>
        {/* Order Date */}
        <div className="space-y-2">
          <Label htmlFor="orderDate">Order Date *</Label>
          <Input
            id="orderDate"
            type="date"
            {...register('orderDate')}
            onChange={handleDateChange('orderDate')}
            className={errors.orderDate ? 'border-destructive' : ''}
          />
          {errors.orderDate && (
            <p className="text-sm text-destructive">{errors.orderDate?.message}</p>
          )}
        </div>
        {/* Expected Completion Date */}
        <div className="space-y-2">
          <Label htmlFor="expectedCompletionDate">Expected Completion Date</Label>
          <Input
            id="expectedCompletionDate"
            type="date"
            {...register('expectedCompletionDate')}
            onChange={handleDateChange('expectedCompletionDate')}
            className={errors.expectedCompletionDate ? 'border-destructive' : ''}
          />
          {errors.expectedCompletionDate && (
            <p className="text-sm text-destructive">{errors.expectedCompletionDate?.message}</p>
          )}
        </div>
        {/* Actual Completion Date */}
        <div className="space-y-2">
          <Label htmlFor="actualCompletionDate">Actual Completion Date</Label>
          <Input
            id="actualCompletionDate"
            type="date"
            {...register('actualCompletionDate')}
            onChange={handleDateChange('actualCompletionDate')}
            className={errors.actualCompletionDate ? 'border-destructive' : ''}
          />
          {errors.actualCompletionDate && (
            <p className="text-sm text-destructive">{errors.actualCompletionDate?.message}</p>
          )}
        </div>
        {/* Total Amount */}
        <div className="space-y-2">
          <Label htmlFor="totalAmount">Total Amount (Optional)</Label>
          <Input
            id="totalAmount"
            type="number"
            placeholder="Enter total amount (optional)..."
            {...register('totalAmount')}
            className={errors.totalAmount ? 'border-destructive' : ''}
          />
          {errors.totalAmount && (
            <p className="text-sm text-destructive">{errors.totalAmount?.message}</p>
          )}
        </div>
        {/* Notes */}
        <div className="space-y-2">
          <Label htmlFor="notes">Notes</Label>
          <Textarea
            id="notes"
            placeholder="Enter notes..."
            {...register('notes')}
            className={errors.notes ? 'border-destructive' : ''}
          />
          {errors.notes && (
            <p className="text-sm text-destructive">{errors.notes?.message}</p>
          )}
        </div>
        {/* Attachment */}
        <div className="space-y-2">
          <Label htmlFor="attachment">Attachment</Label>
          <Input
            id="attachment"
            type="text"
            placeholder="Enter attachment..."
            {...register('attachment')}
            className={errors.attachment ? 'border-destructive' : ''}
          />
          {errors.attachment && (
            <p className="text-sm text-destructive">{errors.attachment?.message}</p>
          )}
        </div>

        {/* Created By */}
        <div className="space-y-2">
          <Label htmlFor="createdByUserId">Created By *</Label>

          {isLoadingOptions
            ? (
                <div className="h-10 animate-pulse rounded bg-muted" />
              )
            : (
                <Select
                  value={watch('createdByUserId') || ''}
                  onValueChange={value => setValue('createdByUserId', value)}
                >
                  <SelectTrigger className={errors.createdByUserId ? 'border-destructive' : ''}>
                    <SelectValue placeholder="Select created by..." />
                  </SelectTrigger>
                  <SelectContent>
                    {relationOptions?.userSyncs?.map((option: { userId: string; fullName: string }) => (
                      <SelectItem key={option.userId} value={option.userId}>
                        {option.fullName}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
          {errors.createdByUserId && (
            <p className="text-sm text-destructive">{errors.createdByUserId?.message}</p>
          )}
        </div>

        {/* Form Actions */}
        <div className="flex justify-end space-x-4 border-t pt-6">
          <Button
            type="button"
            variant="outline"
            onClick={handleCancel}
            disabled={isSubmitting}
          >
            <X className="mr-2 size-4" />
            Cancel
          </Button>

          <Button
            type="submit"
            disabled={isSubmitting}
            className="min-w-[120px]"
          >
            {isSubmitting
              ? (
                  <Loader2 className="mr-2 size-4 animate-spin" />
                )
              : (
                  <Save className="mr-2 size-4" />
                )}
            {isEditing ? 'Update' : 'Create'}
            {' '}
            OutsourceOrder
          </Button>
        </div>
      </form>
    </div>
  );
}
