/**
 * EmployeeSalaryEntry Stats API Route with Enhanced Metrics
 * Generated by enhanced entity generator script V4
 */

import { auth } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

import { getEmployeeSalaryEntryStats } from '@/libs/queries/employeeSalaryEntry';

// GET /api/employeeSalaryEntries/stats
export async function GET() {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const stats = await getEmployeeSalaryEntryStats(userId);

    return NextResponse.json({
      success: true,
      data: stats,
    });
  } catch (error) {
    console.error('Error fetching employeeSalaryEntry stats:', error);
    return NextResponse.json(
      { error: 'Failed to fetch stats' },
      { status: 500 },
    );
  }
}
