/**
 * OutsourceOrder filters hook with state management
 * Generated by enhanced entity generator script V4 (improved)
 */

import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useCallback, useMemo, useState } from 'react';

import type { OutsourceOrderFilters } from '@/types/outsourceOrder';

const DEFAULT_FILTERS: OutsourceOrderFilters = {
  search: '',
  sortBy: 'createdAt',
  sortOrder: 'desc',
};

export function useOutsourceOrderFilters() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  // Initialize filters from URL params
  const [filters, setFilters] = useState<OutsourceOrderFilters>(() => ({
    search: searchParams.get('search') || DEFAULT_FILTERS.search,
    sortBy: (searchParams.get('sortBy') as any) || DEFAULT_FILTERS.sortBy,
    sortOrder: (searchParams.get('sortOrder') as any) || DEFAULT_FILTERS.sortOrder,
    status: searchParams.get('status') || undefined,
    priority: searchParams.get('priority') ? Number(searchParams.get('priority')) : undefined,
  }));

  // Update URL when filters change
  const updateURL = useCallback((newFilters: OutsourceOrderFilters) => {
    const params = new URLSearchParams(searchParams);

    Object.entries(newFilters).forEach(([key, value]) => {
      if (value !== undefined && value !== null && value !== '') {
        params.set(key, String(value));
      } else {
        params.delete(key);
      }
    });

    router.push(`${pathname}?${params.toString()}`, { scroll: false });
  }, [router, pathname, searchParams]);

  // Update filters function
  const updateFilters = useCallback((updates: Partial<OutsourceOrderFilters>) => {
    const newFilters = { ...filters, ...updates };
    setFilters(newFilters);
    updateURL(newFilters);
  }, [filters, updateURL]);

  // Reset filters
  const resetFilters = useCallback(() => {
    setFilters(DEFAULT_FILTERS);
    updateURL(DEFAULT_FILTERS);
  }, [updateURL]);

  // Individual filter setters
  const setSearch = useCallback((search: string) => {
    updateFilters({ search });
  }, [updateFilters]);

  const setSorting = useCallback((sortBy: OutsourceOrderFilters['sortBy'], sortOrder: OutsourceOrderFilters['sortOrder']) => {
    updateFilters({ sortBy, sortOrder });
  }, [updateFilters]);

  const setStatus = useCallback((status: string | undefined) => {
    updateFilters({ status });
  }, [updateFilters]);

  const setPriority = useCallback((priority: number | undefined) => {
    updateFilters({ priority });
  }, [updateFilters]);

  // Check if filters are active
  const hasActiveFilters = useMemo(() => {
    return Object.entries(filters).some(([key, value]) => {
      const defaultValue = DEFAULT_FILTERS[key as keyof OutsourceOrderFilters];
      return value !== defaultValue && value !== undefined && value !== null && value !== '';
    });
  }, [filters]);

  // Active filter count
  const activeFilterCount = useMemo(() => {
    return Object.entries(filters).filter(([key, value]) => {
      const defaultValue = DEFAULT_FILTERS[key as keyof OutsourceOrderFilters];
      return value !== defaultValue && value !== undefined && value !== null && value !== '';
    }).length;
  }, [filters]);

  return {
    filters,
    updateFilters,
    resetFilters,
    setSearch,
    setSorting,
    setStatus,
    setPriority,
    hasActiveFilters,
    activeFilterCount,
  };
}
