/**
 * OutsourceOrder export hook with progress tracking
 * Generated by enhanced entity generator script V4 (improved)
 */

import { useAuth } from '@clerk/nextjs';
import { useCallback, useState } from 'react';
import { toast } from 'sonner';

import type { OutsourceOrderExportParams } from '@/types/outsourceOrder';

type ExportStatus = 'idle' | 'preparing' | 'exporting' | 'downloading' | 'completed' | 'error';

type ExportState = {
  status: ExportStatus;
  progress: number;
  error?: string;
  downloadUrl?: string;
};

export function useOutsourceOrderExport() {
  const { userId } = useAuth();
  const [exportState, setExportState] = useState<ExportState>({
    status: 'idle',
    progress: 0,
  });

  const exportData = useCallback(async (params: OutsourceOrderExportParams = {}) => {
    if (!userId) {
      toast.error('User not authenticated');
      return;
    }

    try {
      setExportState({ status: 'preparing', progress: 10 });

      const searchParams = new URLSearchParams();
      Object.entries(params).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          searchParams.append(key, String(value));
        }
      });

      setExportState({ status: 'exporting', progress: 30 });

      const response = await fetch(`/api/outsourceOrders/export?${searchParams}`, {
        method: 'GET',
        headers: {
          Accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        },
      });

      if (!response.ok) {
        throw new Error(`Export failed: ${response.statusText}`);
      }

      setExportState({ status: 'downloading', progress: 70 });

      // Create blob and download
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);

      const filename = params.filename
        || `outsourceOrders-${new Date().toISOString().split('T')[0]}.${params.format || 'xlsx'}`;

      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);

      window.URL.revokeObjectURL(url);

      setExportState({
        status: 'completed',
        progress: 100,
        downloadUrl: url,
      });

      toast.success(`OutsourceOrder data exported successfully`);

      // Reset after 3 seconds
      setTimeout(() => {
        setExportState({ status: 'idle', progress: 0 });
      }, 3000);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Export failed';
      setExportState({
        status: 'error',
        progress: 0,
        error: errorMessage,
      });
      toast.error(errorMessage);
    }
  }, [userId]);

  const resetExport = useCallback(() => {
    setExportState({ status: 'idle', progress: 0 });
  }, []);

  return {
    ...exportState,
    exportData,
    resetExport,
    isExporting: exportState.status !== 'idle' && exportState.status !== 'completed' && exportState.status !== 'error',
  };
}
