/**
 * OutsourceOrder data fetching hook with enhanced features
 * Generated by enhanced entity generator script V4 (improved)
 */

import { useQuery, useInfiniteQuery } from '@tanstack/react-query';
import { useAuth } from '@clerk/nextjs';

import type {
  OutsourceOrderWithRelations,
  OutsourceOrderListParams,
  OutsourceOrderStats,
  OutsourceOrdersResponse,
  OutsourceOrderStatsResponse,
} from '@/types/outsourceOrder';

const API_BASE = '/api/outsourceOrders';

// Query key factory
export const outsourceOrderKeys = {
  all: ['outsourceOrders'] as const,
  lists: () => [...outsourceOrderKeys.all, 'list'] as const,
  list: (params: OutsourceOrderListParams) => 
    [...outsourceOrderKeys.lists(), params] as const,
  details: () => [...outsourceOrderKeys.all, 'detail'] as const,
  detail: (id: number) => [...outsourceOrderKeys.details(), id] as const,
  stats: () => [...outsourceOrderKeys.all, 'stats'] as const,
  relations: () => [...outsourceOrderKeys.all, 'relations'] as const,
  relationOptions: () => [...outsourceOrderKeys.relations(), 'options'] as const,
} as const;

/**
 * Fetch outsourceOrders with pagination and filtering
 */
export function useOutsourceOrders(params: OutsourceOrderListParams = {}) {
  const { userId } = useAuth();

  return useQuery({
    queryKey: outsourceOrderKeys.list(params),
    queryFn: async (): Promise<OutsourceOrderWithRelations[]> => {
      if (!userId) throw new Error('User not authenticated');

      const searchParams = new URLSearchParams();
      Object.entries({ ...params, includeRelations: true }).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          searchParams.append(key, String(value));
        }
      });

      const response = await fetch(`${API_BASE}?${searchParams}`);
      if (!response.ok) {
        throw new Error(`Failed to fetch outsourceOrders: ${response.statusText}`);
      }

      const result: OutsourceOrdersResponse = await response.json();
      return result.data as OutsourceOrderWithRelations[];
    },
    enabled: !!userId,
    staleTime: 1000 * 60 * 5, // 5 minutes
    retry: 2,
  });
}

/**
 * Infinite scroll hook for outsourceOrders
 */
export function useOutsourceOrdersInfinite(params: Omit<OutsourceOrderListParams, 'page'> = {}) {
  const { userId } = useAuth();

  return useInfiniteQuery({
    queryKey: [...outsourceOrderKeys.list(params), 'infinite'],
    queryFn: async ({ pageParam = 1 }): Promise<OutsourceOrdersResponse> => {
      if (!userId) throw new Error('User not authenticated');

      const searchParams = new URLSearchParams();
      Object.entries({ ...params, page: pageParam }).forEach(([key, value]) => {
        if (value !== undefined && value !== null) {
          searchParams.append(key, String(value));
        }
      });

      const response = await fetch(`${API_BASE}?${searchParams}`);
      if (!response.ok) {
        throw new Error(`Failed to fetch outsourceOrders: ${response.statusText}`);
      }

      return response.json();
    },
    enabled: !!userId,
    initialPageParam: 1,
    getNextPageParam: (lastPage) => 
      lastPage.pagination.hasMore ? lastPage.pagination.page + 1 : undefined,
    staleTime: 1000 * 60 * 5,
  });
}

/**
 * Fetch single outsourceOrder by ID
 */
export function useOutsourceOrder(id: number, includeRelations = false) {
  const { userId } = useAuth();

  return useQuery({
    queryKey: outsourceOrderKeys.detail(id),
    queryFn: async (): Promise<OutsourceOrderWithRelations> => {
      if (!userId) throw new Error('User not authenticated');

      const searchParams = new URLSearchParams();
      if (includeRelations) {
        searchParams.append('includeRelations', 'true');
      }

      const response = await fetch(`${API_BASE}/${id}?${searchParams}`);
      if (!response.ok) {
        if (response.status === 404) {
          throw new Error('OutsourceOrder not found');
        }
        throw new Error(`Failed to fetch outsourceOrder: ${response.statusText}`);
      }

      const result = await response.json();
      return result.data;
    },
    enabled: !!userId && !!id,
    staleTime: 1000 * 60 * 2, // 2 minutes
  });
}

/**
 * Fetch outsourceOrder statistics
 */
export function useOutsourceOrderStats() {
  const { userId } = useAuth();

  return useQuery({
    queryKey: outsourceOrderKeys.stats(),
    queryFn: async (): Promise<OutsourceOrderStats> => {
      if (!userId) throw new Error('User not authenticated');

      const response = await fetch(`${API_BASE}/stats`);
      if (!response.ok) {
        throw new Error(`Failed to fetch outsourceOrder stats: ${response.statusText}`);
      }

      const result: OutsourceOrderStatsResponse = await response.json();
      return result.data;
    },
    enabled: !!userId,
    staleTime: 1000 * 60 * 10, // 10 minutes
    refetchOnWindowFocus: false,
  });
}


/**
 * Fetch relation options for dropdowns and selectors
 */
export function useOutsourceOrderRelationOptions() {
  const { userId } = useAuth();

  return useQuery({
    queryKey: outsourceOrderKeys.relationOptions(),
    queryFn: async () => {
      if (!userId) throw new Error('User not authenticated');

      const response = await fetch(`${API_BASE}/relations/options`);
      if (!response.ok) {
        throw new Error(`Failed to fetch relation options: ${response.statusText}`);
      }

      const result = await response.json();
      return result.data;
    },
    enabled: !!userId,
    staleTime: 1000 * 60 * 10, // 10 minutes
    refetchOnWindowFocus: false,
  });
}