/**
 * OutsourceOrder mutation hooks with optimistic updates
 * Generated by enhanced entity generator script V4 (improved)
 */

import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@clerk/nextjs';
import { toast } from 'sonner';

import type {
  OutsourceOrderWithRelations,
  CreateOutsourceOrderInput,
  UpdateOutsourceOrderInput,
  OutsourceOrderResponse,
} from '@/types/outsourceOrder';
import { outsourceOrderKeys } from './useOutsourceOrders';

const API_BASE = '/api/outsourceOrders';

/**
 * Create outsourceOrder mutation
 */
export function useCreateOutsourceOrder() {
  const queryClient = useQueryClient();
  const { userId } = useAuth();

  return useMutation({
    mutationFn: async (data: Omit<CreateOutsourceOrderInput, 'ownerId'>): Promise<OutsourceOrderWithRelations> => {
      if (!userId) throw new Error('User not authenticated');

      const response = await fetch(API_BASE, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ ...data, ownerId: userId }),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || `Failed to create outsourceOrder`);
      }

      const result: OutsourceOrderResponse = await response.json();
      return result.data;
    },
    onSuccess: (newOutsourceOrder) => {
      // Invalidate and refetch
      queryClient.invalidateQueries({ queryKey: outsourceOrderKeys.all });
      
      // Optimistically update lists
      queryClient.setQueriesData(
        { queryKey: outsourceOrderKeys.lists() },
        (oldData: OutsourceOrderWithRelations[] | undefined) => {
          if (!oldData) return [newOutsourceOrder];
          return [newOutsourceOrder, ...oldData];
        }
      );

      toast.success('OutsourceOrder created successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to create outsourceOrder: ${error.message}`);
    },
  });
}

/**
 * Update outsourceOrder mutation
 */
export function useUpdateOutsourceOrder() {
  const queryClient = useQueryClient();
  const { userId } = useAuth();

  return useMutation({
    mutationFn: async ({ 
      id, 
      data 
    }: { 
      id: number; 
      data: UpdateOutsourceOrderInput 
    }): Promise<OutsourceOrderWithRelations> => {
      if (!userId) throw new Error('User not authenticated');

      const response = await fetch(`${API_BASE}/${id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || `Failed to update outsourceOrder`);
      }

      const result: OutsourceOrderResponse = await response.json();
      return result.data;
    },
    onSuccess: (updatedOutsourceOrder, { id }) => {
      // Update specific item in cache
      queryClient.setQueryData(
        outsourceOrderKeys.detail(id),
        updatedOutsourceOrder
      );

      // Update item in lists
      queryClient.setQueriesData(
        { queryKey: outsourceOrderKeys.lists() },
        (oldData: OutsourceOrderWithRelations[] | undefined) => {
          if (!oldData) return oldData;
          return oldData.map(item => 
            item.id === id ? { ...item, ...updatedOutsourceOrder } : item
          );
        }
      );

      // Invalidate stats
      queryClient.invalidateQueries({ queryKey: outsourceOrderKeys.stats() });

      toast.success('OutsourceOrder updated successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to update outsourceOrder: ${error.message}`);
    },
  });
}

/**
 * Delete outsourceOrder mutation
 */
export function useDeleteOutsourceOrder() {
  const queryClient = useQueryClient();
  const { userId } = useAuth();

  return useMutation({
    mutationFn: async (id: number): Promise<void> => {
      if (!userId) throw new Error('User not authenticated');

      const response = await fetch(`${API_BASE}/${id}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || `Failed to delete outsourceOrder`);
      }
    },
    onSuccess: (_, deletedId) => {
      // Remove from cache
      queryClient.removeQueries({ queryKey: outsourceOrderKeys.detail(deletedId) });

      // Remove from lists
      queryClient.setQueriesData(
        { queryKey: outsourceOrderKeys.lists() },
        (oldData: OutsourceOrderWithRelations[] | undefined) => {
          if (!oldData) return oldData;
          return oldData.filter(item => item.id !== deletedId);
        }
      );

      // Invalidate stats
      queryClient.invalidateQueries({ queryKey: outsourceOrderKeys.stats() });

      toast.success('OutsourceOrder deleted successfully');
    },
    onError: (error: Error) => {
      toast.error(`Failed to delete outsourceOrder: ${error.message}`);
    },
  });
}

