/**
 * PlanDetail export hook
 * Generated by enhanced entity generator script V3
 */

import { useState } from 'react';

import { exportPlanDetails } from '@/libs/api/plandetails';
import type { PlanDetailListParamsWithOwner } from '@/types/plandetail';

export function usePlanDetailExport() {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async (params: PlanDetailListParamsWithOwner) => {
    try {
      setIsExporting(true);
      const blob = await exportPlanDetails(params);

      // Create download link
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `plandetails-export-${new Date().toISOString().split('T')[0]}.xlsx`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Export failed:', error);
      throw error;
    } finally {
      setIsExporting(false);
    }
  };

  return {
    isExporting,
    handleExport,
  };
}
