/**
 * PlanDetail filters hook
 * Generated by enhanced entity generator script V3
 */

import { useState } from 'react';

import type { PlanDetailFilters } from '@/types/plandetail';

const DEFAULT_FILTERS: PlanDetailFilters = {
  search: '',
  sortBy: 'createdAt',
  sortOrder: 'desc',
};

export function usePlanDetailFilters() {
  const [filters, setFilters] = useState<PlanDetailFilters>(DEFAULT_FILTERS);

  const updateFilters = (newFilters: Partial<PlanDetailFilters>) => {
    setFilters(prev => ({ ...prev, ...newFilters }));
  };

  const resetFilters = () => {
    setFilters(DEFAULT_FILTERS);
  };

  return {
    filters,
    updateFilters,
    resetFilters,
  };
}
