/**
 * EmployeeSalaryEntry Enhanced TypeScript Types and Interfaces
 * Generated by enhanced entity generator script V4
 * 🆕 Features: Text FK Types, Decimal Types, Timestamp Types, Complex Relations
 */

import type { employeeSalaryEntrySchema } from '@/models/Schema';

// Infer the EmployeeSalaryEntryDb type from Drizzle schema
export type EmployeeSalaryEntryDb = typeof employeeSalaryEntrySchema.$inferSelect;

// Client-side EmployeeSalaryEntry type với camelCase
export type EmployeeSalaryEntry = Omit<EmployeeSalaryEntryDb, 'createdAt' | 'updatedAt'> & {
  readonly createdAt: string | Date;
  readonly updatedAt: string | Date;
};

// EmployeeSalaryEntry with enhanced relations (camelCase)
export type EmployeeSalaryEntryWithRelations = {
  id: number;
  createdAt: string | Date;
  updatedAt: string | Date;
  workDate: string | Date | null;
  entryDate?: string | Date | null;
  actualQuantity?: number | null;
  plannedQuantity?: number | null;
  limitQuantity?: number | null;
  previousEnteredQuantity?: number | null;
  unitPrice?: number | null;
  totalAmount?: number | null;
  salaryNote?: string | null;
  status?: string | null;
  approvedBy?: string | null;
  approvedAt?: string | Date | null;
  startTime?: string | Date | null;
  endTime?: string | Date | null;
  workDurationMinutes?: number | null;
  userId?: string | null;
  productionStepDetailId?: number | null;
  planId?: number | null;
  productId?: number | null;
  // Relations
  userSync?: {
    userId: string;
    fullName: string;
    shortcut?: string | null;
  };
  plan?: {
    id: number;
    planName: string;
  };
  productionStepDetail?: {
    id: number;
    stepName?: string | null;
    filmSequence?: string | null;
  };
  product?: {
    id: number;
    productCode: string;
    productName: string;
    productCategory?: string | null;
  };
};

// Form data type cho React Hook Form (camelCase)
export type EmployeeSalaryEntryFormData = {
  userId: string;
  productionStepDetailId?: number;
  planId: number;
  productId: number; // 🆕 Add product field
  workDate: Date | string;
  entryDate?: Date | string;
  actualQuantity?: number;
  plannedQuantity?: number;
  limitQuantity?: number;
  previousEnteredQuantity?: number;
  unitPrice?: number;
  totalAmount?: number;
  salaryNote?: string;
  status?: string;
  approvedBy?: string;
  approvedAt?: Date | string;
  startTime?: Date | string;
  endTime?: Date | string;
  workDurationMinutes?: number;
};

// Input types cho CRUD (camelCase)
export type CreateEmployeeSalaryEntryInput = {
  readonly ownerId: string;
  userId: string;
  productionStepDetailId?: number;
  planId: number;
  productId: number; // 🆕 Add product field
  workDate: Date | string;
  entryDate?: Date | string;
  actualQuantity?: number;
  plannedQuantity?: number;
  limitQuantity?: number;
  previousEnteredQuantity?: number;
  unitPrice?: number;
  totalAmount?: number;
  salaryNote?: string;
  status?: string;
  approvedBy?: string;
  approvedAt?: Date | string;
  startTime?: Date | string;
  endTime?: Date | string;
  workDurationMinutes?: number;
};

export type UpdateEmployeeSalaryEntryInput = Partial<CreateEmployeeSalaryEntryInput>;

// Relation options (camelCase)
export type EmployeeSalaryEntryRelationOptions = {
  readonly userSyncs: { userId: string; fullName: string | null; shortcut: string | null }[];
  readonly productionStepDetails: { id: number; stepName?: string; filmSequence?: string | null }[]; // 🆕 Add stepName & filmSequence
  readonly plans: { id: number; planName: string }[];
  readonly products: { id: number; productCode: string; productName: string; productCategory?: string | null }[]; // 🆕 Add products
};

// API Response types (camelCase)
export type EmployeeSalaryEntryResponse = {
  readonly success: true;
  readonly data: EmployeeSalaryEntryWithRelations;
  readonly message?: string;
  readonly metadata?: {
    readonly calculations?: {
      readonly totalAmount?: number;
      readonly workDuration?: number;
    };
  };
};

export type EmployeeSalaryEntrysResponse = {
  readonly success: true;
  readonly data: readonly EmployeeSalaryEntryWithRelations[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
  readonly filters?: {
    readonly applied: Record<string, unknown>;
    readonly available: Record<string, unknown[]>;
  };
};

export type EmployeeSalaryEntryErrorResponse = {
  readonly success: false;
  readonly error: string;
  readonly code: string;
  readonly details?: unknown;
  readonly validationErrors?: Record<string, string[]>;
};

// List params (camelCase)
export type EmployeeSalaryEntryListParams = {
  readonly page?: number;
  readonly limit?: number;
  readonly search?: string;
  readonly sortBy?: 'createdAt' | 'updatedAt' | 'workDate' | 'id' | 'status';
  readonly sortOrder?: 'asc' | 'desc';
  readonly showAll?: boolean;
  readonly includeRelations?: boolean;
  readonly status?: 'draft' | 'submitted' | 'approved' | 'paid' | 'cancelled';
  // Enhanced date filtering
  readonly dateFrom?: Date | string;
  readonly dateTo?: Date | string;
  readonly workDateFrom?: Date | string;
  readonly workDateTo?: Date | string;
  // Enhanced employee filtering
  readonly userId?: string;
  readonly employeeCode?: string; // Mã nhân viên (shortcut)
  readonly employeeName?: string; // Tên nhân viên (fullName)
  // Enhanced product filtering
  readonly productId?: number;
  readonly productCode?: string; // Mã sản phẩm
  readonly productName?: string; // Tên sản phẩm
  readonly productCategory?: string; // Danh mục sản phẩm
  // Production step filtering
  readonly productionStepDetailId?: number;
  readonly stepName?: string; // Tên công đoạn
  readonly filmSequence?: string; // Phim Tát
  readonly planId?: number;
};

export type EmployeeSalaryEntryListParamsWithOwner = EmployeeSalaryEntryListParams & {
  readonly ownerId: string;
};

// Export params (camelCase)
export type EmployeeSalaryEntryExportParams = EmployeeSalaryEntryListParams & {
  readonly includeCalculatedFields?: boolean;
  readonly format?: 'xlsx' | 'csv';
};

// Import result (camelCase)
export type ImportEmployeeSalaryEntryResult = {
  readonly success: boolean;
  readonly imported: number;
  readonly failed: number;
  readonly skipped: number;
  readonly errors: readonly {
    readonly row: number;
    readonly field: string;
    readonly message: string;
    readonly value: unknown;
  }[];
  readonly warnings: readonly string[];
  readonly employeeSalaryEntries: readonly EmployeeSalaryEntry[];
  readonly summary: {
    readonly totalRows: number;
    readonly validRows: number;
    readonly duplicateRows: number;
    readonly processingTime: number;
  };
};

// Statistics (camelCase)
export type EmployeeSalaryEntryStats = {
  readonly total: number;
  readonly today: number;
  readonly thisWeek: number;
  readonly thisMonth: number;
  readonly byStatus: {
    readonly draft: number;
    readonly submitted: number;
    readonly approved: number;
    readonly paid: number;
    readonly cancelled: number;
  };
  readonly financial: {
    readonly totalAmount: number;
    readonly averageAmount: number;
    readonly maxAmount: number;
    readonly minAmount: number;
  };
  readonly productivity: {
    readonly totalWorkTime: number;
    readonly averageWorkTime: number;
    readonly efficiency: number;
  };
};

export type EmployeeSalaryEntryStatsResponse = {
  readonly success: true;
  readonly data: EmployeeSalaryEntryStats;
};

// 🆕 V4: Enhanced filter state with complex options
export type EmployeeSalaryEntryFilters = {
  search: string;
  sortBy: 'createdAt' | 'updatedAt' | 'workDate' | 'id' | 'status';
  sortOrder: 'asc' | 'desc';
  status?: 'draft' | 'submitted' | 'approved' | 'paid' | 'cancelled';

  // Enhanced date filtering
  dateRange?: {
    from: Date | string;
    to: Date | string;
  };
  workDateRange?: {
    from: Date | string;
    to: Date | string;
  };

  // Enhanced employee filtering
  employee?: {
    userId?: string;
    employeeCode?: string; // Mã nhân viên
    employeeName?: string; // Tên nhân viên
  };

  // Enhanced product filtering
  product?: {
    productId?: number;
    productCode?: string; // Mã sản phẩm
    productName?: string; // Tên sản phẩm
    productCategory?: string; // Danh mục sản phẩm
  };

  // Production step filtering
  productionStep?: {
    productionStepDetailId?: number;
    stepName?: string; // Tên công đoạn
    filmSequence?: string; // Phim Tát
  };

  relations?: {
    planId?: number;
  };
};

// 🆕 V4: Enhanced batch operations types
export type EmployeeSalaryEntryBatchAction = 'delete' | 'approve' | 'reject' | 'updateStatus';

export type EmployeeSalaryEntryBatchRequest = {
  readonly ids: readonly number[];
  readonly action: EmployeeSalaryEntryBatchAction;
  readonly newStatus?: 'draft' | 'submitted' | 'approved' | 'paid' | 'cancelled';
  readonly reason?: string;
};

export type EmployeeSalaryEntryBatchResponse = {
  readonly success: boolean;
  readonly processed: number;
  readonly failed: number;
  readonly errors: readonly {
    readonly id: number;
    readonly error: string;
  }[];
};
