/**
 * OutsourceOrder-related TypeScript types and interfaces
 * Enhanced version with proper error handling, type safety and relationships support
 * Generated by enhanced entity generator script V4 (improved)
 */

import type { outsourceOrderSchema } from '@/models/Schema';
import type { UserSync } from '@/types/userSync';

// Infer the OutsourceOrderDb type from Drizzle schema
export type OutsourceOrderDb = typeof outsourceOrderSchema.$inferSelect;

// Client-side OutsourceOrder type with proper date handling
export type OutsourceOrder = Omit<OutsourceOrderDb, 'createdAt' | 'updatedAt'> & {
  readonly createdAt: string | Date;
  readonly updatedAt: string | Date;
};

// OutsourceOrder with relations
export type OutsourceOrderWithRelations = OutsourceOrder & {
  // Relations types
  userSync?: Pick<UserSync, 'id' | 'fullName'>;
  createdByUser?: { fullName?: string | null };
  assignedToUser?: { fullName?: string | null };
};

// Form data type for React Hook Form
export type OutsourceOrderFormData = {
  orderCode: string;
  orderTitle?: string;
  createdByUserId: string;
  assignedToUserId: string;
  orderDate: Date | string;
  expectedCompletionDate?: Date | string;
  actualCompletionDate?: Date | string;
  status: string;
  priority: number;
  totalAmount?: number;
  currency?: string;
  notes?: string;
  attachment?: string;
  applyRetailPrice: number;
};

// Input types for CRUD operations with proper validation
export type CreateOutsourceOrderInput = {
  ownerId: string;
  orderCode: string;
  createdByUserId: string;
  assignedToUserId: string;
  orderDate: Date;
  status?: string;
  notes?: string;
  orderTitle?: string;
  expectedCompletionDate?: Date;
  actualCompletionDate?: Date;
  priority?: number;
  totalAmount?: number;
  currency?: string;
  attachment?: string;
  applyRetailPrice: number;
};

export type UpdateOutsourceOrderInput = {
  orderCode?: string;
  orderTitle?: string;
  createdByUserId?: string;
  assignedToUserId?: string;
  orderDate?: Date | string;
  expectedCompletionDate?: Date | string;
  actualCompletionDate?: Date | string;
  status?: string;
  priority?: number;
  totalAmount?: number;
  currency?: string;
  notes?: string;
  attachment?: string;
  applyRetailPrice?: number;
};

// Relation options for dropdowns and selectors
export type OutsourceOrderRelationOptions = {
  readonly userSyncs: readonly Pick<UserSync, 'id' | 'fullName'>[];
};

// Enhanced relation options with search and pagination
export type OutsourceOrderRelationSearchOptions = {
  readonly query?: string;
  readonly page?: number;
  readonly limit?: number;
  readonly sortBy?: string;
  readonly sortOrder?: 'asc' | 'desc';
};

export type OutsourceOrderRelationSearchResult<T = any> = {
  readonly success: true;
  readonly data: readonly T[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
};

// API Response types
export type OutsourceOrderResponse = {
  readonly success: true;
  readonly data: OutsourceOrderWithRelations;
  readonly message?: string;
};

export type OutsourceOrdersResponse = {
  readonly success: true;
  readonly data: readonly OutsourceOrderWithRelations[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
};

export type OutsourceOrderErrorResponse = {
  readonly success: false;
  readonly error: string;
  readonly code: string;
  readonly details?: unknown;
};

// List parameters
export type OutsourceOrderListParams = {
  readonly page?: number;
  readonly limit?: number;
  readonly search?: string;
  readonly sortBy?: 'createdAt' | 'updatedAt' | 'orderTitle' | 'orderCode';
  readonly sortOrder?: 'asc' | 'desc';
  readonly showAll?: boolean;
  readonly includeRelations?: boolean;
};

export type OutsourceOrderListParamsWithOwner = OutsourceOrderListParams & {
  readonly ownerId: string;
};

// Export parameters for Excel functionality
export type OutsourceOrderExportParams = OutsourceOrderListParams & {
  readonly format?: 'xlsx' | 'csv';
  readonly includeHeaders?: boolean;
  readonly filename?: string;
};

// Import validation result
export type ImportOutsourceOrderResult = {
  readonly success: boolean;
  readonly imported: number;
  readonly failed: number;
  readonly errors: readonly string[];
  readonly outsourceOrders: readonly OutsourceOrder[];
  readonly duplicates?: readonly string[];
  readonly warnings?: readonly string[];
};

// Statistics type
export type OutsourceOrderStats = {
  readonly total: number;
  readonly today: number;
  readonly thisWeek: number;
  readonly thisMonth: number;
  readonly byStatus?: Record<string, number>;
  readonly byPriority?: Record<string, number>;
  readonly trends?: {
    readonly daily: Record<string, number>;
    readonly weekly: Record<string, number>;
    readonly monthly: Record<string, number>;
  };
};

export type OutsourceOrderStatsResponse = {
  readonly success: true;
  readonly data: OutsourceOrderStats;
};

// Filter state
export type OutsourceOrderFilters = {
  search: string;
  sortBy: 'createdAt' | 'updatedAt' | 'orderTitle' | 'orderCode';
  sortOrder: 'asc' | 'desc';

  status?: string;
  priority?: number;
  dateRange?: {
    start: Date;
    end: Date;
  };
  relations?: Record<string, any>;
};

// Advanced filter options
export type OutsourceOrderFilterOptions = {
  readonly statuses: readonly string[];
  readonly priorities: readonly number[];
  readonly datePresets: readonly {
    readonly label: string;
    readonly value: string;
    readonly start: Date;
    readonly end: Date;
  }[];
  readonly relations: {
    readonly userSyncs: readonly Pick<UserSync, 'id' | 'fullName'>[];
  };
};
