/**
 * OutsourceOrder-related TypeScript types and interfaces
 * Enhanced version with proper error handling, type safety and relationships support
 * Generated by enhanced entity generator script V4 (improved)
 */

import type { outsourceOrderSchema } from '@/models/Schema';
import type { Plan } from '@/types/plan';
import type { Product } from '@/types/product';
import type { ProductionStep } from '@/types/productionStep';
import type { UserSync } from '@/types/userSync';

// Infer the OutsourceOrderDb type from Drizzle schema
export type OutsourceOrderDb = typeof outsourceOrderSchema.$inferSelect;

// Client-side OutsourceOrder type with proper date handling
export type OutsourceOrder = Omit<OutsourceOrderDb, 'createdAt' | 'updatedAt'> & {
  readonly createdAt: string | Date;
  readonly updatedAt: string | Date;
};

// OutsourceOrder with relations
export type OutsourceOrderWithRelations = OutsourceOrder & {
  // Relations types
  userSync?: Pick<UserSync, 'id' | 'fullName'>;
  createdByUser?: { fullName?: string | null };
  assignedToUser?: { fullName?: string | null };
};

// Form data type for React Hook Form
export type OutsourceOrderFormData = {
  orderCode: string;
  orderTitle?: string;
  createdByUserId: string;
  assignedToUserId: string;
  orderDate: Date | string;
  expectedCompletionDate?: Date | string;
  actualCompletionDate?: Date | string;
  status: string;
  priority: number;
  totalAmount?: number;
  currency?: string;
  notes?: string;
  attachment?: string;
  applyRetailPrice: number;
};

// Input types for CRUD operations with proper validation
export type CreateOutsourceOrderInput = {
  ownerId: string;
  orderCode: string;
  createdByUserId: string;
  assignedToUserId: string;
  orderDate: Date;
  status?: string;
  notes?: string;
  orderTitle?: string;
  expectedCompletionDate?: Date;
  actualCompletionDate?: Date;
  priority?: number;
  totalAmount?: number;
  currency?: string;
  attachment?: string;
  applyRetailPrice: number;
};

export type UpdateOutsourceOrderInput = {
  orderCode?: string;
  orderTitle?: string;
  createdByUserId?: string;
  assignedToUserId?: string;
  orderDate?: Date | string;
  expectedCompletionDate?: Date | string;
  actualCompletionDate?: Date | string;
  status?: string;
  priority?: number;
  totalAmount?: number;
  currency?: string;
  notes?: string;
  attachment?: string;
  applyRetailPrice?: number;
};

// Relation options for dropdowns and selectors
export type OutsourceOrderRelationOptions = {
  readonly userSyncs: readonly Pick<UserSync, 'id' | 'fullName'>[];
};

// Enhanced relation options with search and pagination
export type OutsourceOrderRelationSearchOptions = {
  readonly query?: string;
  readonly page?: number;
  readonly limit?: number;
  readonly sortBy?: string;
  readonly sortOrder?: 'asc' | 'desc';
};

export type OutsourceOrderRelationSearchResult<T = any> = {
  readonly success: true;
  readonly data: readonly T[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
};

// API Response types
export type OutsourceOrderResponse = {
  readonly success: true;
  readonly data: OutsourceOrderWithRelations;
  readonly message?: string;
};

export type OutsourceOrdersResponse = {
  readonly success: true;
  readonly data: readonly OutsourceOrderWithRelations[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
};

export type OutsourceOrderErrorResponse = {
  readonly success: false;
  readonly error: string;
  readonly code: string;
  readonly details?: unknown;
};

// List parameters
export type OutsourceOrderListParams = {
  readonly page?: number;
  readonly limit?: number;
  readonly search?: string;
  readonly sortBy?: 'createdAt' | 'updatedAt' | 'orderTitle' | 'orderCode';
  readonly sortOrder?: 'asc' | 'desc';
  readonly showAll?: boolean;
  readonly includeRelations?: boolean;
};

export type OutsourceOrderListParamsWithOwner = OutsourceOrderListParams & {
  readonly ownerId: string;
};

// Export parameters for Excel functionality
export type OutsourceOrderExportParams = OutsourceOrderListParams & {
  readonly format?: 'xlsx' | 'csv';
  readonly includeHeaders?: boolean;
  readonly filename?: string;
};

// Import validation result
export type ImportOutsourceOrderResult = {
  readonly success: boolean;
  readonly imported: number;
  readonly failed: number;
  readonly errors: readonly string[];
  readonly outsourceOrders: readonly OutsourceOrder[];
  readonly duplicates?: readonly string[];
  readonly warnings?: readonly string[];
};

// Statistics type
export type OutsourceOrderStats = {
  readonly total: number;
  readonly today: number;
  readonly thisWeek: number;
  readonly thisMonth: number;
  readonly byStatus?: Record<string, number>;
  readonly byPriority?: Record<string, number>;
  readonly trends?: {
    readonly daily: Record<string, number>;
    readonly weekly: Record<string, number>;
    readonly monthly: Record<string, number>;
  };
};

export type OutsourceOrderStatsResponse = {
  readonly success: true;
  readonly data: OutsourceOrderStats;
};

// Filter state
export type OutsourceOrderFilters = {
  search: string;
  sortBy: 'createdAt' | 'updatedAt' | 'orderTitle' | 'orderCode';
  sortOrder: 'asc' | 'desc';

  status?: string;
  priority?: number;
  dateRange?: {
    start: Date;
    end: Date;
  };
  relations?: Record<string, any>;
};

// Advanced filter options
export type OutsourceOrderFilterOptions = {
  readonly statuses: readonly string[];
  readonly priorities: readonly number[];
  readonly datePresets: readonly {
    readonly label: string;
    readonly value: string;
    readonly start: Date;
    readonly end: Date;
  }[];
  readonly relations: {
    readonly userSyncs: readonly Pick<UserSync, 'id' | 'fullName'>[];
  };
};

// =============================================================================
// BULK FORM TYPES (New Step-by-Step Flow)
// =============================================================================

// Bulk form data type for the new step-by-step flow
export type OutsourceOrderBulkFormData = {
  // Step 1: OutsourceOrder Header
  assignedToUserId: string;
  orderDate: Date;
  applyRetailPrice: number; // 2=normal, 3=retail

  // Optional header fields
  orderTitle?: string;
  priority: number; // 1-10, default 5
  expectedCompletionDate?: Date;
  notes?: string;

  // Step 2: Order Details
  planId: number;
  productId: number;
  productSubCode?: string;
  locationCode?: string;

  // Selected production steps with quantities
  selectedSteps: OutsourceOrderDetailFormData[];
};

// Individual order detail form data
export type OutsourceOrderDetailFormData = {
  productionStepId: number;
  orderedQuantity: number;
  expectedCompletionDate: Date;
  itemNotes?: string;
  unitPrice?: number;
  sequenceNumber?: number;
};

// Relation options for the bulk form dependency chain
export type OutsourceOrderBulkRelationOptions = {
  readonly userSyncs: readonly Pick<UserSync, 'id' | 'fullName'>[];
  readonly plans: readonly Pick<Plan, 'id' | 'planCode' | 'planName'>[];
  readonly applyRetailPriceOptions: readonly {
    readonly value: number;
    readonly label: string;
  }[];
};

// Filtered relation options based on selections
export type OutsourceOrderFilteredProducts = readonly Pick<Product, 'id' | 'productCode' | 'productName'>[];

export type OutsourceOrderProductSub = {
  readonly code: string;
  readonly name: string;
};

export type OutsourceOrderLocation = {
  readonly code: string;
  readonly name: string;
  readonly description?: string;
};

export type OutsourceOrderProductionStepOption = Pick<ProductionStep, 'id' | 'stepCode' | 'stepName'> & {
  readonly planCode?: string;
  readonly planName?: string;
  readonly productCode?: string;
  readonly productName?: string;
};

// State for dependency chain management
export type OutsourceOrderDependencyState = {
  selectedPlan: Pick<Plan, 'id' | 'planCode' | 'planName'> | null;
  selectedProduct: Pick<Product, 'id' | 'productCode' | 'productName'> | null;
  selectedProductSub: OutsourceOrderProductSub | null;
  selectedLocation: OutsourceOrderLocation | null;

  filteredProducts: OutsourceOrderFilteredProducts;
  filteredProductSubs: readonly OutsourceOrderProductSub[];
  filteredLocations: readonly OutsourceOrderLocation[];
  productionSteps: readonly OutsourceOrderProductionStepOption[];
};

// API payload for creating outsource order with details
export type CreateOutsourceOrderWithDetailsInput = {
  // Header data
  ownerId: string;
  orderCode: string; // Auto-generated
  createdByUserId: string;
  assignedToUserId: string;
  orderDate: Date;
  applyRetailPrice: number;
  orderTitle?: string;
  priority?: number;
  expectedCompletionDate?: Date;
  notes?: string;
  status?: string; // Default 'draft'

  // Details data
  details: Array<{
    planId: number;
    productId: number;
    productionStepId: number;
    orderedQuantity: number;
    expectedCompletionDate: Date;
    itemNotes?: string;
    unitPrice?: number;
    locationCode?: string;
    productSubCode?: string;
    sequenceNumber?: number;
  }>;
};

// Response for bulk creation
export type OutsourceOrderBulkCreateResponse = {
  readonly success: true;
  readonly data: {
    readonly outsourceOrder: OutsourceOrderWithRelations;
    readonly details: readonly any[]; // OutsourceOrderDetail type
    readonly created: number;
  };
  readonly message?: string;
};

// Step validation state
export type OutsourceOrderStepValidation = {
  step1Valid: boolean;
  step2Valid: boolean;
  canProceedToStep2: boolean;
  validationErrors: {
    step1: readonly string[];
    step2: readonly string[];
  };
};
