/**
 * PlanDetail-related TypeScript types and interfaces
 * Enhanced version with proper error handling, type safety and relationships support
 * Generated by enhanced entity generator script V3 (configurable)
 */

import type { planDetailSchema } from '@/models/Schema';
import type { Plan } from '@/types/plan';

// Infer the PlanDetailDb type from Drizzle schema
export type PlanDetailDb = typeof planDetailSchema.$inferSelect;

// Client-side PlanDetail type with proper date handling
export type PlanDetail = Omit<PlanDetailDb, 'createdAt' | 'updatedAt'> & {
  readonly createdAt: string | Date;
  readonly updatedAt: string | Date;
};

// PlanDetail with relations
export type PlanDetailWithRelations = PlanDetail & {
// Relations types
  plan?: Pick<Plan, 'id' | 'planCode'>;
};

// Form data type for React Hook Form
export type PlanDetailFormData = {
  planId: number;
  locationCode: string;
  locationType?: string;
  productCode: string;
  productSubCode?: string;
  plannedQuantity: number;
  actualQuantity?: number;
  plannedStartDate?: Date | string;
  plannedEndDate?: Date | string;
  actualStartDate?: Date | string;
  actualEndDate?: Date | string;
  status?: string;
  priority?: number;
  note?: string;
};

// Input types for CRUD operations with proper validation
export type CreatePlanDetailInput = {
  readonly ownerId: string;
  planId: number;
  locationCode: string;
  locationType?: string;
  productCode: string;
  productSubCode?: string;
  plannedQuantity: number;
  actualQuantity?: number;
  plannedStartDate?: Date | string;
  plannedEndDate?: Date | string;
  actualStartDate?: Date | string;
  actualEndDate?: Date | string;
  status?: string;
  priority?: number;
  note?: string;
};

export type UpdatePlanDetailInput = {
  planId?: number;
  locationCode?: string;
  locationType?: string;
  productCode?: string;
  productSubCode?: string;
  plannedQuantity?: number;
  actualQuantity?: number;
  plannedStartDate?: Date | string;
  plannedEndDate?: Date | string;
  actualStartDate?: Date | string;
  actualEndDate?: Date | string;
  status?: string;
  priority?: number;
  note?: string;
};

// Relation options for dropdowns
export type PlanDetailRelationOptions = {
  readonly plans: readonly Pick<Plan, 'id' | 'planCode'>[];
  readonly products: readonly {
    readonly id: number;
    readonly productCode: string;
    readonly productName: string;
  }[];
  readonly locationCodes: readonly {
    readonly locationCode: string;
    readonly tableName?: string;
  }[];
  readonly productSubCodes: readonly {
    readonly productSubCode: string;
    readonly productSubDetail: string;
    readonly productCode: string;
  }[];
};

// API Response types
export type PlanDetailResponse = {
  readonly success: true;
  readonly data: PlanDetailWithRelations;
  readonly message?: string;
};

export type PlanDetailsResponse = {
  readonly success: true;
  readonly data: readonly PlanDetailWithRelations[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
};

export type PlanDetailErrorResponse = {
  readonly success: false;
  readonly error: string;
  readonly code: string;
  readonly details?: unknown;
};

// List parameters
export type PlanDetailListParams = {
  readonly page?: number;
  readonly limit?: number;
  readonly search?: string;
  readonly sortBy?: 'createdAt' | 'updatedAt' | 'productSubCode' | 'locationCode';
  readonly sortOrder?: 'asc' | 'desc';
  readonly showAll?: boolean;
  readonly includeRelations?: boolean;
};

export type PlanDetailListParamsWithOwner = PlanDetailListParams & {
  readonly ownerId: string;
};

// Export parameters for Excel functionality
export type PlanDetailExportParams = PlanDetailListParams;

// Import validation result
export type ImportPlanDetailResult = {
  readonly success: boolean;
  readonly imported: number;
  readonly failed: number;
  readonly errors: readonly string[];
  readonly plandetails: readonly PlanDetail[];
};

// Statistics type
export type PlanDetailStats = {
  readonly total: number;
  readonly today: number;
  readonly thisWeek: number;
  readonly thisMonth: number;
};

export type PlanDetailStatsResponse = {
  readonly success: true;
  readonly data: PlanDetailStats;
};

// Filter state
export type PlanDetailFilters = {
  search: string;
  sortBy: 'createdAt' | 'updatedAt' | 'productSubCode' | 'locationCode';
  sortOrder: 'asc' | 'desc';
};
