/**
 * OutsourceOrder Dashboard Page
 * Generated by enhanced entity generator script V4 (improved)
 */

import { OutsourceOrderList } from '@/features/outsourceOrder/OutsourceOrderList';

export default function OutsourceOrdersPage() {
  return (
    <div className="container mx-auto py-6">
      <OutsourceOrderList />
    </div>
  );
}