/**
 * PlanDetail Import Modal Component
 * Generated by enhanced entity generator script V3
 */

'use client';

import { AlertCircle, CheckCircle, FileSpreadsheet, Upload } from 'lucide-react';
import { useState } from 'react';

import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { importPlanDetails } from '@/libs/api/plandetails';
import type { ImportPlanDetailResult } from '@/types/plandetail';

type PlanDetailImportModalProps = {
  onSuccess?: (result: ImportPlanDetailResult) => void;
  onError?: (error: string) => void;
};

export function PlanDetailImportModal({ onSuccess, onError }: PlanDetailImportModalProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isImporting, setIsImporting] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [importResult, setImportResult] = useState<ImportPlanDetailResult | null>(null);

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file && file.type === 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet') {
      setSelectedFile(file);
      setImportResult(null);
    } else {
      onError?.('Please select a valid Excel file (.xlsx)');
    }
  };

  const handleImport = async () => {
    if (!selectedFile) {
      return;
    }

    try {
      setIsImporting(true);
      const result = await importPlanDetails(selectedFile);
      setImportResult(result);

      if (result.success) {
        onSuccess?.(result);
        setTimeout(() => {
          setIsOpen(false);
          setSelectedFile(null);
          setImportResult(null);
        }, 2000);
      }
    } catch (error) {
      onError?.(error instanceof Error ? error.message : 'Import failed');
    } finally {
      setIsImporting(false);
    }
  };

  const handleClose = () => {
    setIsOpen(false);
    setSelectedFile(null);
    setImportResult(null);
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm">
          <Upload className="mr-2 size-4" />
          Import Excel
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Import Plan Details</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {!importResult
            ? (
                <>
                  <div className="space-y-2">
                    <Label htmlFor="file-upload">Select Excel File</Label>
                    <Input
                      id="file-upload"
                      type="file"
                      accept=".xlsx,.xls"
                      onChange={handleFileSelect}
                      disabled={isImporting}
                    />
                    <p className="text-sm text-muted-foreground">
                      Upload an Excel file with plan detail data
                    </p>
                  </div>

                  {selectedFile && (
                    <div className="flex items-center space-x-2 rounded-md bg-muted p-3">
                      <FileSpreadsheet className="size-4" />
                      <span className="text-sm">{selectedFile.name}</span>
                    </div>
                  )}

                  <div className="flex justify-end space-x-2">
                    <Button variant="outline" onClick={handleClose} disabled={isImporting}>
                      Cancel
                    </Button>
                    <Button
                      onClick={handleImport}
                      disabled={!selectedFile || isImporting}
                    >
                      {isImporting ? 'Importing...' : 'Import'}
                    </Button>
                  </div>
                </>
              )
            : (
                <div className="space-y-4">
                  {importResult.success
                    ? (
                        <div className="flex items-center space-x-2 text-green-600">
                          <CheckCircle className="size-5" />
                          <span>Import completed successfully!</span>
                        </div>
                      )
                    : (
                        <div className="flex items-center space-x-2 text-red-600">
                          <AlertCircle className="size-5" />
                          <span>Import failed</span>
                        </div>
                      )}

                  <div className="space-y-2">
                    <p className="text-sm">
                      <strong>Imported:</strong>
                      {' '}
                      {importResult.imported}
                      {' '}
                      records
                    </p>
                    <p className="text-sm">
                      <strong>Failed:</strong>
                      {' '}
                      {importResult.failed}
                      {' '}
                      records
                    </p>

                    {importResult.errors.length > 0 && (
                      <div className="space-y-1">
                        <p className="text-sm font-medium">Errors:</p>
                        <div className="max-h-32 space-y-1 overflow-y-auto">
                          {importResult.errors.map((error, index) => (
                            <p key={index} className="text-xs text-red-600">
                              {error}
                            </p>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex justify-end">
                    <Button onClick={handleClose}>
                      Close
                    </Button>
                  </div>
                </div>
              )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
