/**
 * PlanDetail Form Component with Relations Support
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { useAuth } from '@clerk/nextjs';
import { zodResolver } from '@hookform/resolvers/zod';
import { useTranslations } from 'next-intl';
import { useEffect, useState } from 'react';
import { useForm, useWatch } from 'react-hook-form';

import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Combobox, type ComboboxOption } from '@/components/ui/combobox';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { CalendarDays, MapPin, Package, Settings, FileText, AlertCircle } from 'lucide-react';
import { usePlanDetailMutations } from '@/hooks/usePlanDetailMutations';
import { plandetailFormSchema } from '@/libs/validations/plandetail';
import type {
  CreatePlanDetailInput,
  PlanDetailFormData,
  PlanDetailRelationOptions,
  PlanDetailWithRelations,
} from '@/types/plandetail';

type PlanDetailFormProps = {
  plandetail?: PlanDetailWithRelations;
  onSuccess: (plandetail: PlanDetailWithRelations) => void;
  onCancel: () => void;
  isLoading?: boolean;
};

export function PlanDetailForm({ plandetail, onSuccess, onCancel, isLoading }: PlanDetailFormProps) {
  const t = useTranslations('plandetail');
  const { userId, orgId } = useAuth();
  const [relationOptions, setRelationOptions] = useState<PlanDetailRelationOptions>({
    plans: [],
    products: [],
    locationCodes: [],
    productSubCodes: [],
  });

  const form = useForm<PlanDetailFormData>({
    resolver: zodResolver(plandetailFormSchema),
    defaultValues: {
      planId: plandetail?.planId ?? undefined,
      locationCode: plandetail?.locationCode ?? '',
      locationType: plandetail?.locationType ?? '',
      productCode: plandetail?.productCode ?? '',
      productSubCode: plandetail?.productSubCode ?? '',
      plannedQuantity: plandetail?.plannedQuantity ?? 0,
      actualQuantity: plandetail?.actualQuantity ?? 0,
      plannedStartDate: plandetail?.plannedStartDate ? new Date(plandetail.plannedStartDate).toISOString().split('T')[0] : '',
      plannedEndDate: plandetail?.plannedEndDate ? new Date(plandetail.plannedEndDate).toISOString().split('T')[0] : '',
      actualStartDate: plandetail?.actualStartDate ? new Date(plandetail.actualStartDate).toISOString().split('T')[0] : '',
      actualEndDate: plandetail?.actualEndDate ? new Date(plandetail.actualEndDate).toISOString().split('T')[0] : '',
      status: plandetail?.status ?? '',
      priority: plandetail?.priority ?? 5,
      note: plandetail?.note ?? '',
    },
  });

  // Sử dụng useWatch để theo dõi productCode
  const productCode = useWatch({ control: form.control, name: 'productCode' });

  const { createPlanDetail, updatePlanDetail } = usePlanDetailMutations();

  // Filter product sub codes based on selected product code
  const filteredByProduct = relationOptions.productSubCodes.filter(
    option => option.productCode === productCode,
  );
  const filteredProductSubCodes = (productCode && filteredByProduct.length === 0)
    ? relationOptions.productSubCodes
    : filteredByProduct;

  // Reset productSubCode when productCode changes
  useEffect(() => {
    const subscription = form.watch((_value, { name }) => {
      if (name === 'productCode') {
        form.setValue('productSubCode', '');
      }
    });
    return () => subscription.unsubscribe();
  }, [form]);

  // Handle form submission
  const handleSubmit = async (data: PlanDetailFormData) => {
    try {
      let result;
      if (plandetail) {
        result = await updatePlanDetail(plandetail.id, data);
      } else {
        const ownerId = orgId || userId;
        if (!ownerId) {
          throw new Error('User is not authenticated.');
        }
        const createData: CreatePlanDetailInput = { ...data, ownerId };
        result = await createPlanDetail(createData);
      }
      onSuccess(result);
    } catch (error) {
      console.error('Form submission error:', error);
      // Optionally, you can show an error message to the user
    }
  };

  // Load relation options
  useEffect(() => {
    const loadRelationOptions = async () => {
      try {
        const response = await fetch('/api/plandetails/relations/options');
        if (response.ok) {
          const data = await response.json();
          setRelationOptions(data.data);
        }
      } catch (error) {
        console.error('Failed to load relation options:', error);
      }
    };

    loadRelationOptions();
  }, []);

  // Prepare product options for combobox
  const productOptions: ComboboxOption[] = relationOptions.products?.map(product => ({
    value: product.productCode,
    label: `${product.productCode} - ${product.productName}`,
    searchText: `${product.productCode} ${product.productName}`
  })) || [];

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <div className="rounded-lg border bg-gradient-to-r from-blue-50 to-indigo-50 p-6 dark:from-blue-950/20 dark:to-indigo-950/20">
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
          {plandetail ? t('form.updatePlanDetail') : t('form.createPlanDetail')}
        </h2>
        <p className="mt-2 text-sm text-gray-600 dark:text-gray-300">
          {t('form.planDetailDescription')}
        </p>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-6">
          <Tabs defaultValue="required" className="w-full">
            <TabsList className="grid w-full grid-cols-4 h-12">
              <TabsTrigger value="required" className="flex items-center gap-2">
                <AlertCircle className="h-4 w-4" />
                {t('tabs.required')}
              </TabsTrigger>
              <TabsTrigger value="location" className="flex items-center gap-2">
                <MapPin className="h-4 w-4" />
                {t('tabs.location')}
              </TabsTrigger>
              <TabsTrigger value="dates" className="flex items-center gap-2">
                <CalendarDays className="h-4 w-4" />
                {t('tabs.dates')}
              </TabsTrigger>
              <TabsTrigger value="other" className="flex items-center gap-2">
                <Settings className="h-4 w-4" />
                {t('tabs.other')}
              </TabsTrigger>
            </TabsList>

            {/* Tab 1: Required Fields */}
            <TabsContent value="required" className="space-y-6">
              <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="planId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.plan')}
                      {' '}
                      *
                    </FormLabel>
                    <Select
                      onValueChange={value => field.onChange(Number(value))}
                      value={field.value?.toString()}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('form.selectPlan')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.plans?.map(option => (
                          <SelectItem key={option.id} value={option.id.toString()}>
                            {option.planCode}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="locationCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.locationCode')}
                      {' '}
                      *
                    </FormLabel>
                    <Select
                      onValueChange={value => field.onChange(value)}
                      value={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('form.selectLocation')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.locationCodes?.map(option => (
                          <SelectItem key={option.locationCode} value={option.locationCode}>
                            {option.locationCode}
                            {option.tableName && ` - ${option.tableName}`}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

                    <FormField
                      control={form.control}
                      name="productCode"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="flex items-center gap-2">
                            <Package className="h-4 w-4" />
                            {t('form.productCode')}
                            {' '}
                            *
                          </FormLabel>
                          <FormControl>
                            <Combobox
                              options={productOptions}
                              value={field.value}
                              onValueChange={(value) => {
                                field.onChange(value);
                                // Clear productSubCode when product changes
                                form.setValue('productSubCode', '');
                              }}
                              placeholder={t('form.selectProduct')}
                              searchPlaceholder="Tìm kiếm sản phẩm..."
                              emptyMessage="Không tìm thấy sản phẩm nào"
                              className="w-full"
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="productSubCode"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="flex items-center gap-2">
                            <Package className="h-4 w-4" />
                            {t('form.productSubCode')}
                            {!productCode ? (
                              <Badge variant="outline" className="text-xs">
                                Chọn sản phẩm trước
                              </Badge>
                            ) : filteredProductSubCodes?.length === 0 ? (
                              <Badge variant="secondary" className="text-xs">
                                Tùy chọn
                              </Badge>
                            ) : null}
                          </FormLabel>
                          <Select
                            onValueChange={value => field.onChange(value)}
                            value={field.value}
                            disabled={!productCode}
                          >
                            <FormControl>
                              <SelectTrigger className={!productCode ? "bg-muted text-muted-foreground" : ""}>
                                <SelectValue 
                                  placeholder={
                                    !productCode 
                                      ? "Vui lòng chọn sản phẩm trước" 
                                      : filteredProductSubCodes?.length > 0
                                        ? "Chọn phân loại sản phẩm..."
                                        : "Không có phân loại"
                                  } 
                                />
                              </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                              {filteredProductSubCodes?.length > 0
                                ? (
                                    filteredProductSubCodes.map(option => (
                                      <SelectItem key={option.productSubCode} value={option.productSubCode}>
                                        <div className="flex flex-col">
                                          <span className="font-medium">{option.productSubCode}</span>
                                          <span className="text-xs text-muted-foreground">{option.productSubDetail}</span>
                                        </div>
                                      </SelectItem>
                                    ))
                                  )
                                : productCode ? (
                                    <div className="px-2 py-1.5 text-sm text-muted-foreground">
                                      Không có phân loại sản phẩm
                                    </div>
                                  ) : (
                                    <div className="px-2 py-1.5 text-sm text-muted-foreground">
                                      Vui lòng chọn sản phẩm trước
                                    </div>
                                  )}
                            </SelectContent>
                          </Select>
                          <FormMessage />
                          {productCode && filteredProductSubCodes?.length === 0 && (
                            <p className="text-xs text-muted-foreground mt-1">
                              💡 Sản phẩm này không có phân loại con
                            </p>
                          )}
                        </FormItem>
                      )}
                    />

              <FormField
                control={form.control}
                name="plannedQuantity"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.plannedQuantity')}
                      {' '}
                      *
                    </FormLabel>
                    <FormControl>
                      <Input
                        type="text"
                        placeholder={t('form.enterPlannedQuantity')}
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value) || 0)}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              </div>
            </TabsContent>

            {/* Tab 2: Location Type & Actual Quantity */}
            <TabsContent value="location" className="space-y-6">
              <Card className="border-green-200 dark:border-green-800">
                <CardHeader className="bg-green-50 dark:bg-green-950/20">
                  <CardTitle className="flex items-center gap-2 text-green-800 dark:text-green-200">
                    <MapPin className="h-5 w-5" />
                    {t('tabs.location')}
                    <Badge variant="secondary" className="ml-auto">Optional</Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent className="pt-6">
                  <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="locationType"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.locationType')}</FormLabel>
                    <FormControl>
                      <Input
                        placeholder={t('form.enterLocationType')}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="actualQuantity"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.actualQuantity')}</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder={t('form.enterActualQuantity')}
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            {/* Tab 3: Date Fields */}
            <TabsContent value="dates" className="space-y-6">
              <Card className="border-blue-200 dark:border-blue-800">
                <CardHeader className="bg-blue-50 dark:bg-blue-950/20">
                  <CardTitle className="flex items-center gap-2 text-blue-800 dark:text-blue-200">
                    <CalendarDays className="h-5 w-5" />
                    {t('tabs.dates')}
                    <Badge variant="secondary" className="ml-auto">Planning</Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent className="pt-6">
                  <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="plannedStartDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.plannedStartDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="plannedEndDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.plannedEndDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="actualStartDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.actualStartDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="actualEndDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.actualEndDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            {/* Tab 4: Other Fields */}
            <TabsContent value="other" className="space-y-6">
              <Card className="border-purple-200 dark:border-purple-800">
                <CardHeader className="bg-purple-50 dark:bg-purple-950/20">
                  <CardTitle className="flex items-center gap-2 text-purple-800 dark:text-purple-200">
                    <Settings className="h-5 w-5" />
                    {t('tabs.other')}
                    <Badge variant="secondary" className="ml-auto">Additional</Badge>
                  </CardTitle>
                </CardHeader>
                <CardContent className="pt-6">
                  <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="status"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.status')}</FormLabel>
                    <FormControl>
                      <Input
                        placeholder={t('form.enterStatus')}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="priority"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.priority')}</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder={t('form.enterPriority')}
                        min="1"
                        max="10"
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
                  </div>

                  <FormField
                    control={form.control}
                    name="note"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="flex items-center gap-2">
                          <FileText className="h-4 w-4" />
                          {t('form.note')}
                        </FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder={t('form.enterNote')}
                            className="min-h-[100px] resize-none"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>

          <Card className="border-gray-200 dark:border-gray-700">
            <CardContent className="pt-6">
              <div className="flex justify-end gap-4">
                <Button 
                  type="button" 
                  variant="outline" 
                  onClick={onCancel} 
                  disabled={isLoading}
                  className="min-w-[100px]"
                >
                  {t('form.cancel')}
                </Button>
                <Button 
                  type="submit" 
                  disabled={isLoading}
                  className="min-w-[120px] bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700"
                >
                  {isLoading ? (
                    <div className="flex items-center gap-2">
                      <div className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                      {t('form.saving')}
                    </div>
                  ) : (
                    plandetail ? t('form.updatePlanDetail') : t('form.createPlanDetail')
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        </form>
      </Form>
    </div>
  );
}
