/**
 * PlanDetail Form Component with Relations Support
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { useAuth } from '@clerk/nextjs';
import { zodResolver } from '@hookform/resolvers/zod';
import { useTranslations } from 'next-intl';
import { useEffect, useState } from 'react';
import { useForm, useWatch } from 'react-hook-form';

import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { usePlanDetailMutations } from '@/hooks/usePlanDetailMutations';
import { plandetailFormSchema } from '@/libs/validations/plandetail';
import type {
  CreatePlanDetailInput,
  PlanDetailFormData,
  PlanDetailRelationOptions,
  PlanDetailWithRelations,
} from '@/types/plandetail';

type PlanDetailFormProps = {
  plandetail?: PlanDetailWithRelations;
  onSuccess: (plandetail: PlanDetailWithRelations) => void;
  onCancel: () => void;
  isLoading?: boolean;
};

export function PlanDetailForm({ plandetail, onSuccess, onCancel, isLoading }: PlanDetailFormProps) {
  const t = useTranslations('plandetail');
  const { userId, orgId } = useAuth();
  const [relationOptions, setRelationOptions] = useState<PlanDetailRelationOptions>({
    plans: [],
    products: [],
    locationCodes: [],
    productSubCodes: [],
  });

  const form = useForm<PlanDetailFormData>({
    resolver: zodResolver(plandetailFormSchema),
    defaultValues: {
      planId: plandetail?.planId ?? undefined,
      locationCode: plandetail?.locationCode ?? '',
      locationType: plandetail?.locationType ?? '',
      productCode: plandetail?.productCode ?? '',
      productSubCode: plandetail?.productSubCode ?? '',
      plannedQuantity: plandetail?.plannedQuantity ?? 0,
      actualQuantity: plandetail?.actualQuantity ?? 0,
      plannedStartDate: plandetail?.plannedStartDate ? new Date(plandetail.plannedStartDate).toISOString().split('T')[0] : '',
      plannedEndDate: plandetail?.plannedEndDate ? new Date(plandetail.plannedEndDate).toISOString().split('T')[0] : '',
      actualStartDate: plandetail?.actualStartDate ? new Date(plandetail.actualStartDate).toISOString().split('T')[0] : '',
      actualEndDate: plandetail?.actualEndDate ? new Date(plandetail.actualEndDate).toISOString().split('T')[0] : '',
      status: plandetail?.status ?? '',
      priority: plandetail?.priority ?? 5,
      note: plandetail?.note ?? '',
    },
  });

  // Sử dụng useWatch để theo dõi productCode
  const productCode = useWatch({ control: form.control, name: 'productCode' });

  const { createPlanDetail, updatePlanDetail } = usePlanDetailMutations();

  // Filter product sub codes based on selected product code
  const filteredByProduct = relationOptions.productSubCodes.filter(
    option => option.productCode === productCode,
  );
  const filteredProductSubCodes = (productCode && filteredByProduct.length === 0)
    ? relationOptions.productSubCodes
    : filteredByProduct;

  // Reset productSubCode when productCode changes
  useEffect(() => {
    const subscription = form.watch((_value, { name }) => {
      if (name === 'productCode') {
        form.setValue('productSubCode', '');
      }
    });
    return () => subscription.unsubscribe();
  }, [form]);

  // Handle form submission
  const handleSubmit = async (data: PlanDetailFormData) => {
    try {
      let result;
      if (plandetail) {
        result = await updatePlanDetail(plandetail.id, data);
      } else {
        const ownerId = orgId || userId;
        if (!ownerId) {
          throw new Error('User is not authenticated.');
        }
        const createData: CreatePlanDetailInput = { ...data, ownerId };
        result = await createPlanDetail(createData);
      }
      onSuccess(result);
    } catch (error) {
      console.error('Form submission error:', error);
      // Optionally, you can show an error message to the user
    }
  };

  // Load relation options
  useEffect(() => {
    const loadRelationOptions = async () => {
      try {
        const response = await fetch('/api/plandetails/relations/options');
        if (response.ok) {
          const data = await response.json();
          setRelationOptions(data.data);
        }
      } catch (error) {
        console.error('Failed to load relation options:', error);
      }
    };

    loadRelationOptions();
  }, []);

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-6">
        <Tabs defaultValue="required" className="w-full">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="required">{t('tabs.required')}</TabsTrigger>
            <TabsTrigger value="location">{t('tabs.location')}</TabsTrigger>
            <TabsTrigger value="dates">{t('tabs.dates')}</TabsTrigger>
            <TabsTrigger value="other">{t('tabs.other')}</TabsTrigger>
          </TabsList>

          {/* Tab 1: Required Fields */}
          <TabsContent value="required" className="space-y-6">
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="planId"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.plan')}
                      {' '}
                      *
                    </FormLabel>
                    <Select
                      onValueChange={value => field.onChange(Number(value))}
                      value={field.value?.toString()}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('form.selectPlan')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.plans?.map(option => (
                          <SelectItem key={option.id} value={option.id.toString()}>
                            {option.planCode}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="locationCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.locationCode')}
                      {' '}
                      *
                    </FormLabel>
                    <Select
                      onValueChange={value => field.onChange(value)}
                      value={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('form.selectLocation')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.locationCodes?.map(option => (
                          <SelectItem key={option.locationCode} value={option.locationCode}>
                            {option.locationCode}
                            {option.tableName && ` - ${option.tableName}`}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="productCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.productCode')}
                      {' '}
                      *
                    </FormLabel>
                    <Select
                      onValueChange={value => field.onChange(value)}
                      value={field.value}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('form.selectProduct')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.products?.map(option => (
                          <SelectItem key={option.id} value={option.productCode}>
                            {option.productCode}
                            {' '}
                            -
                            {option.productName}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="productSubCode"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.productSubCode')}
                      {' '}
                      *
                    </FormLabel>
                    <Select
                      onValueChange={value => field.onChange(value)}
                      value={field.value}
                      disabled={!productCode}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={productCode ? t('form.selectProductSub') : t('form.selectProductFirst')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {filteredProductSubCodes?.length > 0
                          ? (
                              filteredProductSubCodes.map(option => (
                                <SelectItem key={option.productSubCode} value={option.productSubCode}>
                                  {option.productSubCode}
                                  {' '}
                                  -
                                  {option.productSubDetail}
                                </SelectItem>
                              ))
                            )
                          : (
                              <div className="px-2 py-1.5 text-sm text-muted-foreground">
                                {productCode ? t('form.noProductSubAvailable') : t('form.pleaseSelectProductFirst')}
                              </div>
                            )}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="plannedQuantity"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>
                      {t('form.plannedQuantity')}
                      {' '}
                      *
                    </FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder={t('form.enterPlannedQuantity')}
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
          </TabsContent>

          {/* Tab 2: Location Type & Actual Quantity */}
          <TabsContent value="location" className="space-y-6">
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="locationType"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.locationType')}</FormLabel>
                    <FormControl>
                      <Input
                        placeholder={t('form.enterLocationType')}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="actualQuantity"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.actualQuantity')}</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder={t('form.enterActualQuantity')}
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
          </TabsContent>

          {/* Tab 3: Date Fields */}
          <TabsContent value="dates" className="space-y-6">
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="plannedStartDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.plannedStartDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="plannedEndDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.plannedEndDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="actualStartDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.actualStartDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="actualEndDate"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.actualEndDate')}</FormLabel>
                    <FormControl>
                      <Input
                        type="date"
                        {...field}
                        value={typeof field.value === 'string' ? field.value : ''}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
          </TabsContent>

          {/* Tab 4: Other Fields */}
          <TabsContent value="other" className="space-y-6">
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              <FormField
                control={form.control}
                name="status"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.status')}</FormLabel>
                    <FormControl>
                      <Input
                        placeholder={t('form.enterStatus')}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="priority"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>{t('form.priority')}</FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        placeholder={t('form.enterPriority')}
                        min="1"
                        max="10"
                        {...field}
                        onChange={e => field.onChange(Number(e.target.value))}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="note"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>{t('form.note')}</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder={t('form.enterNote')}
                      className="min-h-[100px]"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </TabsContent>
        </Tabs>

        <div className="flex justify-end gap-4">
          <Button type="button" variant="outline" onClick={onCancel} disabled={isLoading}>
            {t('form.cancel')}
          </Button>
          <Button type="submit" disabled={isLoading}>
            {isLoading ? t('form.saving') : plandetail ? t('form.updatePlanDetail') : t('form.createPlanDetail')}
          </Button>
        </div>
      </form>
    </Form>
  );
}
