#!/usr/bin/env node

/**
 * Enhanced Advanced Entity Generator Script V3 - COMPLETE VERSION
 * Creates complete CRUD entity with Excel import/export capabilities and database relationships
 * Self-contained version that generates all files without requiring templates
 *
 * Usage: npx tsx scripts/enhanced-generate-advanced-entity-V3-complete.ts [entityName] [configFile]
 * Example: npx tsx scripts/enhanced-generate-advanced-entity-V3-complete.ts plandetail configs/plandetail-config.ts
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

// Helper function
function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

type FieldConfig = {
  name: string;
  type: 'string' | 'text' | 'number' | 'boolean' | 'date' | 'decimal' | 'relation';
  required: boolean;
  unique?: boolean;
  maxLength?: number;
  label: string;
  excelColumn?: string;
  dbColumnType?: 'text' | 'integer' | 'decimal' | 'boolean' | 'date' | 'timestamp';
  
  // Relationship properties
  relation?: {
    type: 'belongsTo' | 'hasMany' | 'manyToMany';
    entity: string;
    entityLower: string;
    foreignKey: string;
    referenceKey?: string;
    displayField: string;
    nullable?: boolean;
    onDelete?: 'cascade' | 'restrict' | 'setNull';
    
    // For many-to-many
    junctionTable?: string;
    junctionFields?: {
      currentKey: string;
      relatedKey: string;
    };
  };
};

export type EntityConfig = {
  entityName: string;
  entityNameLower: string;
  entityNamePlural: string;
  tableName: string;
  codeField: string;
  nameField: string;
  fields: FieldConfig[];
  features: {
    pagination: boolean;
    search: boolean;
    sorting: boolean;
    stats: boolean;
    excelImport: boolean;
    excelExport: boolean;
    uniqueCode: boolean;
    batchOperations: boolean;
    relationships: boolean;
  };
  uiType: 'table' | 'cards';
};

/**
 * Load entity configuration from external file
 */
async function loadEntityConfig(configPath: string, entityName: string): Promise<EntityConfig> {
  try {
    // Convert to absolute path
    const absolutePath = join(process.cwd(), 'scripts', configPath);
    
    if (!existsSync(absolutePath)) {
      throw new Error(`Config file not found: ${absolutePath}`);
    }

    // Import the config file
    const configModule = await import(pathToFileURL(absolutePath).href);
    
    // Try to get the main config with multiple naming conventions
    const possibleKeys = [
      `${entityName}Config`,                    // plandetailConfig
      `${entityName}Configuration`,            // plandetailConfiguration
      `${entityName.toLowerCase()}Config`,     // plandetailConfig
      `${capitalizeFirst(entityName)}Config`,  // PlanDetailConfig
      'planDetailConfig',                      // exact match for PlanDetail
      'plandetailConfig',                      // exact match for plandetail
      'config',                                // generic
      'entityConfig',                          // generic
      'default'                                // default export
    ];
    
    let config = configModule.default; // Try default first
    
    // If no default, try other keys
    if (!config) {
      for (const key of possibleKeys) {
        if (configModule[key]) {
          config = configModule[key];
          console.log(`✅ Found config using key: ${key}`);
          break;
        }
      }
    } else {
      console.log(`✅ Found config using default export`);
    }

    if (!config) {
      // Generate a meaningful error message
      const expectedConfigName = `${entityName}Config`;
      throw new Error(`No configuration found in ${configPath}. Expected export named '${expectedConfigName}' or one of: ${possibleKeys.join(', ')}`);
    }

    console.log(`✅ Loaded configuration from: ${configPath}`);
    return config;
  } catch (error) {
    console.error(`❌ Error loading config from ${configPath}:`, error);
    throw error;
  }
}

/**
 * Generate database schema with relationships
 */
function generateSchemaWithRelations(config: EntityConfig): string {
  const relationFields = config.fields.filter(f => f.relation);
  const regularFields = config.fields.filter(f => !f.relation && f.name !== 'id' && f.name !== 'createdAt' && f.name !== 'updatedAt');
  
  let schemaContent = `/**
 * ${config.entityName} Database Schema with Relations
 * Generated by enhanced entity generator script V3 (complete)
 */

import { relations } from 'drizzle-orm';
import { pgTable, serial, text, integer, timestamp, boolean, decimal, date } from 'drizzle-orm/pg-core';
${relationFields.length > 0 ? `\n// Import related schemas\n${relationFields
    .map(f => `import { ${f.relation!.entityLower}Schema } from '@/models/Schema';`)
    .join('\n')}` : ''}

export const ${config.entityNameLower}Schema = pgTable('${config.tableName}', {
  id: serial('id').primaryKey(),
  
  // Regular fields
${regularFields.map(field => {
    const column = getColumnDefinition(field);
    return `  ${field.name}: ${column},`;
  }).join('\n')}

  // Foreign key fields
${relationFields
    .filter(f => f.relation?.type === 'belongsTo')
    .map(field => {
      const nullable = field.relation?.nullable ? '' : '.notNull()';
      const onDelete = field.relation?.onDelete || 'restrict';
      return `  ${field.relation!.foreignKey}: integer('${field.relation!.foreignKey}')${nullable}.references(() => ${field.relation!.entityLower}Schema.id, { onDelete: '${onDelete}' }),`;
    }).join('\n')}

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Relations configuration
export const ${config.entityNameLower}Relations = relations(${config.entityNameLower}Schema, ({ one, many }) => ({
${relationFields.map(field => {
    const rel = field.relation!;
    if (rel.type === 'belongsTo') {
      return `  ${rel.entityLower}: one(${rel.entityLower}Schema, {
    fields: [${config.entityNameLower}Schema.${rel.foreignKey}],
    references: [${rel.entityLower}Schema.${rel.referenceKey || 'id'}],
    relationName: '${config.entityNameLower}_${rel.entityLower}',
  }),`;
    } else if (rel.type === 'hasMany') {
      return `  ${rel.entityLower}s: many(${rel.entityLower}Schema, {
    relationName: '${config.entityNameLower}_${rel.entityLower}s',
  }),`;
    } else if (rel.type === 'manyToMany') {
      return `  ${rel.entityLower}s: many(${rel.junctionTable}Schema, {
    relationName: '${config.entityNameLower}_${rel.entityLower}s',
  }),`;
    }
    return '';
  }).filter(Boolean).join('\n')}
}));`;

  // Add junction table schemas for many-to-many relations
  const manyToManyRelations = relationFields.filter(f => f.relation?.type === 'manyToMany');
  if (manyToManyRelations.length > 0) {
    schemaContent += `\n\n// Junction tables for many-to-many relations\n`;
    manyToManyRelations.forEach(field => {
      const rel = field.relation!;
      schemaContent += `
export const ${rel.junctionTable}Schema = pgTable('${rel.junctionTable}', {
  id: serial('id').primaryKey(),
  ${rel.junctionFields!.currentKey}: integer('${rel.junctionFields!.currentKey}').notNull().references(() => ${config.entityNameLower}Schema.id, { onDelete: 'cascade' }),
  ${rel.junctionFields!.relatedKey}: integer('${rel.junctionFields!.relatedKey}').notNull().references(() => ${rel.entityLower}Schema.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const ${rel.junctionTable}Relations = relations(${rel.junctionTable}Schema, ({ one }) => ({
  ${config.entityNameLower}: one(${config.entityNameLower}Schema, {
    fields: [${rel.junctionTable}Schema.${rel.junctionFields!.currentKey}],
    references: [${config.entityNameLower}Schema.id],
  }),
  ${rel.entityLower}: one(${rel.entityLower}Schema, {
    fields: [${rel.junctionTable}Schema.${rel.junctionFields!.relatedKey}],
    references: [${rel.entityLower}Schema.id],
  }),
}));`;
    });
  }

  return schemaContent;
}

/**
 * Get column definition for database schema
 */
function getColumnDefinition(field: FieldConfig): string {
  const nullable = field.required ? '.notNull()' : '';
  const unique = field.unique ? '.unique()' : '';
  
  switch (field.dbColumnType) {
    case 'text':
      return `text('${field.name}')${nullable}${unique}`;
    case 'integer':
      return `integer('${field.name}')${nullable}${unique}`;
    case 'decimal':
      return `decimal('${field.name}')${nullable}${unique}`;
    case 'boolean':
      return `boolean('${field.name}')${nullable}`;
    case 'date':
      return `date('${field.name}')${nullable}`;
    case 'timestamp':
      return `timestamp('${field.name}')${nullable}`;
    default:
      return `text('${field.name}')${nullable}${unique}`;
  }
}

/**
 * Generate complete types file content with relations support
 */
function generateCompleteTypesContent(config: EntityConfig): string {
  const relationFields = config.fields.filter(f => f.relation);
  const regularFields = config.fields.filter(f => !f.relation && f.name !== 'ownerId' && f.name !== 'id' && f.name !== 'createdAt' && f.name !== 'updatedAt');
  const belongsToFields = relationFields.filter(f => f.relation?.type === 'belongsTo');

  return `/**
 * ${config.entityName}-related TypeScript types and interfaces
 * Enhanced version with proper error handling, type safety and relationships support
 * Generated by enhanced entity generator script V3 (complete)
 */

import type { ${config.entityNameLower}Schema } from '@/models/Schema';
${relationFields.length > 0 ? relationFields.map(f => 
    `import type { ${f.relation!.entity} } from '@/types/${f.relation!.entityLower}';`
  ).join('\n') : ''}

// Infer the ${config.entityName}Db type from Drizzle schema
export type ${config.entityName}Db = typeof ${config.entityNameLower}Schema.$inferSelect;

// Client-side ${config.entityName} type with proper date handling
export type ${config.entityName} = Omit<${config.entityName}Db, 'createdAt' | 'updatedAt'> & {
  readonly createdAt: string | Date;
  readonly updatedAt: string | Date;
};

${relationFields.length > 0 ? `
// ${config.entityName} with relations
export type ${config.entityName}WithRelations = ${config.entityName} & {
${relationFields.map(field => {
    const rel = field.relation!;
    if (rel.type === 'belongsTo') {
      return `  ${rel.entityLower}?: Pick<${rel.entity}, 'id' | '${rel.displayField}'>;`;
    } else if (rel.type === 'hasMany') {
      return `  ${rel.entityLower}s?: ${rel.entity}[];`;
    } else if (rel.type === 'manyToMany') {
      return `  ${rel.entityLower}s?: Pick<${rel.entity}, 'id' | '${rel.displayField}'>[];`;
    }
    return '';
  }).filter(Boolean).join('\n')}
};` : ''}

// Form data type for React Hook Form
export type ${config.entityName}FormData = {
${[
  ...belongsToFields.map(f => `  ${f.relation!.foreignKey}: number;`),
  ...regularFields.map(field => {
    const optional = !field.required ? '?' : '';
    let type = 'string';
    switch (field.type) {
      case 'number': type = 'number'; break;
      case 'boolean': type = 'boolean'; break;
      case 'date': type = 'string'; break; // Form uses string for dates
      case 'decimal': type = 'number'; break;
    }
    return `  ${field.name}${optional}: ${type};`;
  })
].join('\n')}
};

// Input types for CRUD operations
export type Create${config.entityName}Input = {
  readonly ownerId: string;
${[
  ...belongsToFields.map(f => `  ${f.relation!.foreignKey}: number;`),
  ...regularFields.map(field => {
    const optional = !field.required ? '?' : '';
    let type = 'string';
    switch (field.type) {
      case 'number': type = 'number'; break;
      case 'boolean': type = 'boolean'; break;
      case 'date': type = 'Date | string'; break;
      case 'decimal': type = 'number'; break;
    }
    return `  ${field.name}${optional}: ${type};`;
  })
].join('\n')}
};

export type Update${config.entityName}Input = {
${[
  ...belongsToFields.map(f => `  ${f.relation!.foreignKey}?: number;`),
  ...regularFields.map(field => {
    let type = 'string';
    switch (field.type) {
      case 'number': type = 'number'; break;
      case 'boolean': type = 'boolean'; break;
      case 'date': type = 'Date | string'; break;
      case 'decimal': type = 'number'; break;
    }
    return `  ${field.name}?: ${type};`;
  })
].join('\n')}
};

${relationFields.length > 0 ? `
// Relation options for dropdowns
export type ${config.entityName}RelationOptions = {
${belongsToFields.map(f => 
  `  readonly ${f.relation!.entityLower}s: readonly Pick<${f.relation!.entity}, 'id' | '${f.relation!.displayField}'>[];`
).join('\n')}
};` : ''}

// API Response types
export type ${config.entityName}Response = {
  readonly success: true;
  readonly data: ${config.entityName}${relationFields.length > 0 ? 'WithRelations' : ''};
  readonly message?: string;
};

export type ${config.entityName}sResponse = {
  readonly success: true;
  readonly data: readonly ${config.entityName}${relationFields.length > 0 ? 'WithRelations' : ''}[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
};

export type ${config.entityName}ErrorResponse = {
  readonly success: false;
  readonly error: string;
  readonly code: string;
  readonly details?: unknown;
};

// List parameters
export type ${config.entityName}ListParams = {
  readonly page?: number;
  readonly limit?: number;
  readonly search?: string;
  readonly sortBy?: 'createdAt' | 'updatedAt' | '${config.nameField}' | '${config.codeField}';
  readonly sortOrder?: 'asc' | 'desc';
  readonly showAll?: boolean;
  readonly includeRelations?: boolean;
};

export type ${config.entityName}ListParamsWithOwner = ${config.entityName}ListParams & {
  readonly ownerId: string;
};

// Export parameters for Excel functionality
export type ${config.entityName}ExportParams = ${config.entityName}ListParams;

// Import validation result
export type Import${config.entityName}Result = {
  readonly success: boolean;
  readonly imported: number;
  readonly failed: number;
  readonly errors: readonly string[];
  readonly ${config.entityNamePlural}: readonly ${config.entityName}[];
};

// Statistics type
export type ${config.entityName}Stats = {
  readonly total: number;
  readonly today: number;
  readonly thisWeek: number;
  readonly thisMonth: number;
};

export type ${config.entityName}StatsResponse = {
  readonly success: true;
  readonly data: ${config.entityName}Stats;
};

// Filter state
export type ${config.entityName}Filters = {
  search: string;
  sortBy: 'createdAt' | 'updatedAt' | '${config.nameField}' | '${config.codeField}';
  sortOrder: 'asc' | 'desc';
};`;
}

/**
 * Generate validation schema content
 */
function generateValidationContent(config: EntityConfig): string {
  const relationFields = config.fields.filter(f => f.relation);
  const regularFields = config.fields.filter(f => !f.relation && f.name !== 'ownerId' && f.name !== 'id' && f.name !== 'createdAt' && f.name !== 'updatedAt');
  const belongsToFields = relationFields.filter(f => f.relation?.type === 'belongsTo');

  const generateFieldValidation = (field: FieldConfig, optional = false) => {
    let validation = `${field.name}: `;

    switch (field.type) {
      case 'string':
      case 'text':
        validation += 'z.string().trim()';
        if (field.required && !optional) {
          validation += `.min(1, '${field.label} is required')`;
        }
        if (field.maxLength) {
          validation += `.max(${field.maxLength}, '${field.label} must be ${field.maxLength} characters or less')`;
        }
        if (field.name.toLowerCase().includes('code')) {
          validation += `.regex(/^[\\w-]+$/, '${field.label} can only contain letters, numbers, underscores and dashes')`;
        }
        break;
      case 'number':
        validation += 'z.number().int()';
        if (field.name === 'priority') {
          validation += '.min(1).max(10)';
        } else if (field.name.includes('Quantity')) {
          validation += '.min(0)';
        }
        break;
      case 'boolean':
        validation += 'z.boolean()';
        break;
      case 'date':
        validation += 'z.union([z.string(), z.date()])';
        break;
      case 'decimal':
        validation += 'z.number()';
        break;
    }

    if (!field.required || optional) {
      validation += '.optional()';
    }

    return `${validation},`;
  };

  return `/**
 * ${config.entityName} validation schemas with Relations Support
 * Enhanced version with proper error handling, type safety and relationships
 * Generated by enhanced entity generator script V3 (complete)
 */

import { z } from 'zod';

// Form validation schema with relations
export const ${config.entityNameLower}FormSchema = z.object({
${[
  ...belongsToFields.map(f => `  ${f.relation!.foreignKey}: z.number().int().positive(),`),
  ...regularFields.map(f => `  ${generateFieldValidation(f)}`)
].join('\n')}
});

// Create ${config.entityNameLower} schema (same as form + ownerId)
export const create${config.entityName}Schema = ${config.entityNameLower}FormSchema.extend({
  ownerId: z.string().min(1, 'Owner ID is required'),
});

// Update ${config.entityNameLower} schema (all fields optional)
export const update${config.entityName}Schema = z.object({
${[
  ...belongsToFields.map(f => `  ${f.relation!.foreignKey}: z.number().int().positive().optional(),`),
  ...regularFields.map(f => `  ${generateFieldValidation(f, true)}`)
].join('\n')}
});

// List parameters validation
export const ${config.entityNameLower}ListParamsSchema = z.object({
  page: z.number().int().min(1).default(1),
  limit: z.number().int().min(1).max(100).default(10),
  search: z.string().trim().max(255).optional(),
  sortBy: z.enum(['createdAt', 'updatedAt', '${config.nameField}', '${config.codeField}']).default('createdAt'),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
  showAll: z.boolean().default(false),
  includeRelations: z.boolean().default(false),
});

// Export parameters validation
export type ${config.entityName}ExportParams = z.infer<typeof ${config.entityNameLower}ListParamsSchema>;

// ID validation
export const ${config.entityNameLower}IdSchema = z.object({
  id: z.string().regex(/^\\d+$/, 'ID must be a valid number').transform(Number),
});

// Validation helper functions
export function validate${config.entityName}Id(data: unknown) {
  return ${config.entityNameLower}IdSchema.parse(data);
}

export function validate${config.entityName}Form(data: unknown) {
  return ${config.entityNameLower}FormSchema.parse(data);
}

export function validateCreate${config.entityName}(data: unknown) {
  return create${config.entityName}Schema.parse(data);
}

export function validateUpdate${config.entityName}(data: unknown) {
  return update${config.entityName}Schema.parse(data);
}

export function validate${config.entityName}ListParams(data: unknown) {
  return ${config.entityNameLower}ListParamsSchema.parse(data);
}`;
}

/**
 * Generate queries content with full CRUD operations
 */
function generateQueriesContent(config: EntityConfig): string {
  const relationFields = config.fields.filter(f => f.relation);
  const regularFields = config.fields.filter(f => !f.relation && f.name !== 'id' && f.name !== 'createdAt' && f.name !== 'updatedAt');
  const belongsToFields = relationFields.filter(f => f.relation?.type === 'belongsTo');

  return `/**
 * ${config.entityName} database queries using Drizzle ORM with Relations Support
 * Enhanced version with proper error handling, type safety and relationships
 * Generated by enhanced entity generator script V3 (complete)
 */

import { and, asc, count, desc, eq, gte, ilike, or } from 'drizzle-orm';

import { db } from '@/libs/DB';
import { ${config.entityNameLower}Schema } from '@/models/Schema';
${belongsToFields.map(f => `import { ${f.relation!.entityLower}Schema } from '@/models/Schema';`).join('\n')}
import type {
  Create${config.entityName}Input,
  ${config.entityName}Db,
  ${config.entityName}ListParamsWithOwner,
  ${config.entityName}Stats,
  Update${config.entityName}Input,
  ${relationFields.length > 0 ? `${config.entityName}WithRelations,` : ''}
} from '@/types/${config.entityNameLower}';

/**
 * Create a new ${config.entityNameLower} with proper date and relation handling
 */
export async function create${config.entityName}(data: Create${config.entityName}Input): Promise<${config.entityName}Db> {
${belongsToFields.length > 0 ? `  // Validate foreign keys exist
${belongsToFields.map(field => `  if (data.${field.relation!.foreignKey}) {
    const ${field.relation!.entityLower}Exists = await db
      .select({ id: ${field.relation!.entityLower}Schema.id })
      .from(${field.relation!.entityLower}Schema)
      .where(eq(${field.relation!.entityLower}Schema.id, data.${field.relation!.foreignKey}))
      .limit(1);
      
    if (!${field.relation!.entityLower}Exists.length) {
      throw new Error('${field.relation!.entity} not found');
    }
  }`).join('\n\n')}
` : ''}
  const [${config.entityNameLower}] = await db
    .insert(${config.entityNameLower}Schema)
    .values({
${[
  ...regularFields.map(field => {
    if (field.type === 'date') {
      return `      ${field.name}: data.${field.name} ? new Date(data.${field.name}) : null`;
    }
    return `      ${field.name}: data.${field.name}`;
  }),
  ...belongsToFields.map(field => `      ${field.relation!.foreignKey}: data.${field.relation!.foreignKey}`)
].join(',\n')}
    } as any)
    .returning();

  if (!${config.entityNameLower}) {
    throw new Error('Failed to create ${config.entityNameLower}');
  }

  return ${config.entityNameLower};
}

/**
 * Get ${config.entityNamePlural} by owner with enhanced filtering and relations
 */
export async function get${config.entityName}sByOwner(
  params: ${config.entityName}ListParamsWithOwner
): Promise<${config.entityName}Db${relationFields.length > 0 ? ' | ' + config.entityName + 'WithRelations' : ''}[]> {
  const {
    ownerId,
    page = 1,
    limit = 10,
    search,
    sortBy = 'createdAt',
    sortOrder = 'desc',
    includeRelations = false,
  } = params;

  const offset = (page - 1) * limit;

  let query = db
    .select({
      // Main entity fields
      id: ${config.entityNameLower}Schema.id,
${[
  ...regularFields.map(f => `      ${f.name}: ${config.entityNameLower}Schema.${f.name}`),
  ...belongsToFields.map(f => `      ${f.relation!.foreignKey}: ${config.entityNameLower}Schema.${f.relation!.foreignKey}`)
].join(',\n')},
      createdAt: ${config.entityNameLower}Schema.createdAt,
      updatedAt: ${config.entityNameLower}Schema.updatedAt,
      ${belongsToFields.length > 0 ? `
      // Related entity data (only if includeRelations is true)
${belongsToFields.map(f => `      ${f.relation!.entityLower}: includeRelations ? {
        id: ${f.relation!.entityLower}Schema.id,
        ${f.relation!.displayField}: ${f.relation!.entityLower}Schema.${f.relation!.displayField},
      } : null`).join(',\n')}` : ''}
    })
    .from(${config.entityNameLower}Schema);

${belongsToFields.length > 0 ? `  // Add joins for belongsTo relations
  if (includeRelations) {
${belongsToFields.map(f => `    query = query.leftJoin(
      ${f.relation!.entityLower}Schema,
      eq(${config.entityNameLower}Schema.${f.relation!.foreignKey}, ${f.relation!.entityLower}Schema.id)
    );`).join('\n')}
  }` : ''}

  // Build where conditions safely
  let whereConditions = eq(${config.entityNameLower}Schema.ownerId, ownerId);

  if (search) {
    const searchTerm = \`%\${search}%\`;
    const searchCondition = or(
      ilike(${config.entityNameLower}Schema.${config.codeField}, searchTerm),
      ilike(${config.entityNameLower}Schema.${config.nameField}, searchTerm)${belongsToFields.length > 0 ? `,
${belongsToFields.map(f => `      ilike(${f.relation!.entityLower}Schema.${f.relation!.displayField}, searchTerm)`).join(',\n')}` : ''}
    );
    
    if (searchCondition) {
      whereConditions = and(whereConditions, searchCondition);
    }
  }

  // Safe sorting with switch statement
  let orderBy;
  switch (sortBy) {
    case 'createdAt':
      orderBy = sortOrder === 'asc' ? asc(${config.entityNameLower}Schema.createdAt) : desc(${config.entityNameLower}Schema.createdAt);
      break;
    case 'updatedAt':
      orderBy = sortOrder === 'asc' ? asc(${config.entityNameLower}Schema.updatedAt) : desc(${config.entityNameLower}Schema.updatedAt);
      break;
    case '${config.nameField}':
      orderBy = sortOrder === 'asc' ? asc(${config.entityNameLower}Schema.${config.nameField}) : desc(${config.entityNameLower}Schema.${config.nameField});
      break;
    case '${config.codeField}':
      orderBy = sortOrder === 'asc' ? asc(${config.entityNameLower}Schema.${config.codeField}) : desc(${config.entityNameLower}Schema.${config.codeField});
      break;
    default:
      orderBy = desc(${config.entityNameLower}Schema.createdAt);
  }

  const results = await query
    .where(whereConditions)
    .orderBy(orderBy)
    .limit(limit)
    .offset(offset);

  return results;
}

/**
 * Get ${config.entityNameLower} by ID with ownership check and relations
 */
export async function get${config.entityName}ById(
  id: number,
  ownerId: string,
  includeRelations = false
): Promise<${config.entityName}Db${relationFields.length > 0 ? ' | ' + config.entityName + 'WithRelations' : ''} | undefined> {
  let query = db
    .select({
      id: ${config.entityNameLower}Schema.id,
${[
  ...regularFields.map(f => `      ${f.name}: ${config.entityNameLower}Schema.${f.name}`),
  ...belongsToFields.map(f => `      ${f.relation!.foreignKey}: ${config.entityNameLower}Schema.${f.relation!.foreignKey}`)
].join(',\n')},
      createdAt: ${config.entityNameLower}Schema.createdAt,
      updatedAt: ${config.entityNameLower}Schema.updatedAt,
      ${belongsToFields.length > 0 ? `
      // Related entity data
${belongsToFields.map(f => `      ${f.relation!.entityLower}: includeRelations ? {
        id: ${f.relation!.entityLower}Schema.id,
        ${f.relation!.displayField}: ${f.relation!.entityLower}Schema.${f.relation!.displayField},
      } : null`).join(',\n')}` : ''}
    })
    .from(${config.entityNameLower}Schema);

${belongsToFields.length > 0 ? `  if (includeRelations) {
${belongsToFields.map(f => `    query = query.leftJoin(
      ${f.relation!.entityLower}Schema,
      eq(${config.entityNameLower}Schema.${f.relation!.foreignKey}, ${f.relation!.entityLower}Schema.id)
    );`).join('\n')}
  }` : ''}

  const [result] = await query
    .where(and(
      eq(${config.entityNameLower}Schema.id, id), 
      eq(${config.entityNameLower}Schema.ownerId, ownerId)
    ))
    .limit(1);

  return result;
}

/**
 * Update ${config.entityNameLower} with proper date handling and type safety
 */
export async function update${config.entityName}(
  id: number,
  ownerId: string,
  data: Update${config.entityName}Input,
): Promise<${config.entityName}Db> {
  // Get existing entity for conditional updates
  const existing${config.entityName} = await get${config.entityName}ById(id, ownerId);
  if (!existing${config.entityName}) {
    throw new Error('${config.entityName} not found or access denied');
  }

  // Build update data with proper type handling
  const updateData: Record<string, unknown> = {};
${[
  ...belongsToFields.map(field => `  if (data.${field.relation!.foreignKey} !== undefined) {
    updateData.${field.relation!.foreignKey} = data.${field.relation!.foreignKey};
  } else {
    updateData.${field.relation!.foreignKey} = existing${config.entityName}.${field.relation!.foreignKey};
  }`),
  ...regularFields.map(field => {
    if (field.type === 'date') {
      return `  if (data.${field.name} !== undefined) {
    updateData.${field.name} = data.${field.name} ? new Date(data.${field.name}) : null;
  } else {
    updateData.${field.name} = existing${config.entityName}.${field.name};
  }`;
    } else {
      return `  if (data.${field.name} !== undefined) {
    updateData.${field.name} = data.${field.name};
  } else {
    updateData.${field.name} = existing${config.entityName}.${field.name};
  }`;
    }
  })
].join('\n\n')}

  const [updated${config.entityName}] = await db
    .update(${config.entityNameLower}Schema)
    .set(updateData as any)
    .where(and(eq(${config.entityNameLower}Schema.id, id), eq(${config.entityNameLower}Schema.ownerId, ownerId)))
    .returning();

  if (!updated${config.entityName}) {
    throw new Error('Failed to update ${config.entityNameLower}');
  }

  return updated${config.entityName};
}

/**
 * Delete ${config.entityNameLower} with ownership check
 */
export async function delete${config.entityName}(id: number, ownerId: string): Promise<void> {
  const result = await db
    .delete(${config.entityNameLower}Schema)
    .where(and(eq(${config.entityNameLower}Schema.id, id), eq(${config.entityNameLower}Schema.ownerId, ownerId)));

  if (result.rowCount === 0) {
    throw new Error('${config.entityName} not found or access denied');
  }
}

${belongsToFields.length > 0 ? `
/**
 * Get relation options for dropdowns
 */
export async function get${config.entityName}RelationOptions(): Promise<{
${belongsToFields.map(f => `  ${f.relation!.entityLower}s: Array<{ id: number; ${f.relation!.displayField}: string }>;`).join('\n')}
}> {
  const [${belongsToFields.map(f => `${f.relation!.entityLower}Options`).join(', ')}] = await Promise.all([
${belongsToFields.map(f => `    db.select({
      id: ${f.relation!.entityLower}Schema.id,
      ${f.relation!.displayField}: ${f.relation!.entityLower}Schema.${f.relation!.displayField},
    }).from(${f.relation!.entityLower}Schema).orderBy(asc(${f.relation!.entityLower}Schema.${f.relation!.displayField}))`).join(',\n')}
  ]);

  return {
    ${belongsToFields.map(f => `${f.relation!.entityLower}s: ${f.relation!.entityLower}Options`).join(',\n    ')}
  };
}` : ''}

/**
 * Get ${config.entityNameLower} statistics
 */
export async function get${config.entityName}Stats(ownerId: string): Promise<${config.entityName}Stats> {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const thisWeekStart = new Date(today);
  thisWeekStart.setDate(today.getDate() - today.getDay());
  const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);

  const [totalResult, todayResult, thisWeekResult, thisMonthResult] = await Promise.all([
    db.select({ count: count() }).from(${config.entityNameLower}Schema).where(eq(${config.entityNameLower}Schema.ownerId, ownerId)),
    db.select({ count: count() }).from(${config.entityNameLower}Schema).where(
      and(eq(${config.entityNameLower}Schema.ownerId, ownerId), gte(${config.entityNameLower}Schema.createdAt, today))
    ),
    db.select({ count: count() }).from(${config.entityNameLower}Schema).where(
      and(eq(${config.entityNameLower}Schema.ownerId, ownerId), gte(${config.entityNameLower}Schema.createdAt, thisWeekStart))
    ),
    db.select({ count: count() }).from(${config.entityNameLower}Schema).where(
      and(eq(${config.entityNameLower}Schema.ownerId, ownerId), gte(${config.entityNameLower}Schema.createdAt, thisMonthStart))
    ),
  ]);

  return {
    total: totalResult[0]?.count ?? 0,
    today: todayResult[0]?.count ?? 0,
    thisWeek: thisWeekResult[0]?.count ?? 0,
    thisMonth: thisMonthResult[0]?.count ?? 0,
  };
}`;
}

/**
 * Write file to path with directory creation
 */
function writeFileToPath(targetPath: string, content: string): void {
  const targetDir = join(targetPath, '..');
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }
  writeFileSync(targetPath, content);
}

/**
 * Generate all API routes
 */
function generateAPIRoutes(config: EntityConfig): void {
  const apiDir = `src/app/api/${config.entityNamePlural}`;
  
  // Main CRUD route
  writeFileToPath(`${apiDir}/route.ts`, `/**
 * ${config.entityName} API Routes with Relations Support
 * Generated by enhanced entity generator script V3 (complete)
 */

import { auth } from '@clerk/nextjs/server';
import { NextRequest, NextResponse } from 'next/server';

import {
  create${config.entityName},
  get${config.entityName}sByOwner,
} from '@/libs/queries/${config.entityNameLower}';
import {
  validateCreate${config.entityName},
  validate${config.entityName}ListParams,
} from '@/libs/validations/${config.entityNameLower}';

// GET /api/${config.entityNamePlural}
export async function GET(request: NextRequest) {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const params = validate${config.entityName}ListParams({
      page: Number(searchParams.get('page')) || 1,
      limit: Number(searchParams.get('limit')) || 10,
      search: searchParams.get('search') || undefined,
      sortBy: searchParams.get('sortBy') || 'createdAt',
      sortOrder: searchParams.get('sortOrder') || 'desc',
      includeRelations: searchParams.get('includeRelations') === 'true',
    });

    const ${config.entityNamePlural} = await get${config.entityName}sByOwner({
      ...params,
      ownerId: userId,
    });

    return NextResponse.json({
      success: true,
      data: ${config.entityNamePlural},
      pagination: {
        page: params.page,
        limit: params.limit,
        total: Array.isArray(${config.entityNamePlural}) ? ${config.entityNamePlural}.length : 0,
        hasMore: Array.isArray(${config.entityNamePlural}) && ${config.entityNamePlural}.length === params.limit,
      },
    });
  } catch (error) {
    console.error('Error fetching ${config.entityNamePlural}:', error);
    return NextResponse.json(
      { error: 'Failed to fetch ${config.entityNamePlural}' },
      { status: 500 }
    );
  }
}

// POST /api/${config.entityNamePlural}
export async function POST(request: NextRequest) {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const validatedData = validateCreate${config.entityName}({
      ...body,
      ownerId: userId,
    });

    const ${config.entityNameLower} = await create${config.entityName}(validatedData);

    return NextResponse.json({
      success: true,
      data: ${config.entityNameLower},
      message: '${config.entityName} created successfully',
    });
  } catch (error) {
    console.error('Error creating ${config.entityNameLower}:', error);
    return NextResponse.json(
      { 
        error: error instanceof Error ? error.message : 'Failed to create ${config.entityNameLower}',
        code: 'CREATE_ERROR'
      },
      { status: 400 }
    );
  }
}`);

  // Single item route
  writeFileToPath(`${apiDir}/[id]/route.ts`, `/**
 * ${config.entityName} Single Item API Routes
 * Generated by enhanced entity generator script V3 (complete)
 */

import { auth } from '@clerk/nextjs/server';
import { NextRequest, NextResponse } from 'next/server';

import {
  get${config.entityName}ById,
  update${config.entityName},
  delete${config.entityName},
} from '@/libs/queries/${config.entityNameLower}';
import {
  validate${config.entityName}Id,
  validateUpdate${config.entityName},
} from '@/libs/validations/${config.entityNameLower}';

// GET /api/${config.entityNamePlural}/[id]
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = validate${config.entityName}Id({ id: params.id });
    const { searchParams } = new URL(request.url);
    const includeRelations = searchParams.get('includeRelations') === 'true';

    const ${config.entityNameLower} = await get${config.entityName}ById(id, userId, includeRelations);

    if (!${config.entityNameLower}) {
      return NextResponse.json(
        { error: '${config.entityName} not found' },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      data: ${config.entityNameLower},
    });
  } catch (error) {
    console.error('Error fetching ${config.entityNameLower}:', error);
    return NextResponse.json(
      { error: 'Failed to fetch ${config.entityNameLower}' },
      { status: 500 }
    );
  }
}

// PUT /api/${config.entityNamePlural}/[id]
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = validate${config.entityName}Id({ id: params.id });
    const body = await request.json();
    const validatedData = validateUpdate${config.entityName}(body);

    const ${config.entityNameLower} = await update${config.entityName}(id, userId, validatedData);

    return NextResponse.json({
      success: true,
      data: ${config.entityNameLower},
      message: '${config.entityName} updated successfully',
    });
  } catch (error) {
    console.error('Error updating ${config.entityNameLower}:', error);
    return NextResponse.json(
      { 
        error: error instanceof Error ? error.message : 'Failed to update ${config.entityNameLower}',
        code: 'UPDATE_ERROR'
      },
      { status: 400 }
    );
  }
}

// DELETE /api/${config.entityNamePlural}/[id]
export async function DELETE(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = validate${config.entityName}Id({ id: params.id });

    await delete${config.entityName}(id, userId);

    return NextResponse.json({
      success: true,
      message: '${config.entityName} deleted successfully',
    });
  } catch (error) {
    console.error('Error deleting ${config.entityNameLower}:', error);
    return NextResponse.json(
      { 
        error: error instanceof Error ? error.message : 'Failed to delete ${config.entityNameLower}',
        code: 'DELETE_ERROR'
      },
      { status: 400 }
    );
  }
}`);

  // Relations options route (if has relations)
  const relationFields = config.fields.filter(f => f.relation?.type === 'belongsTo');
  if (relationFields.length > 0) {
    writeFileToPath(`${apiDir}/relations/options/route.ts`, `/**
 * ${config.entityName} Relation Options API Route
 * Generated by enhanced entity generator script V3 (complete)
 */

import { auth } from '@clerk/nextjs/server';
import { NextResponse } from 'next/server';

import { get${config.entityName}RelationOptions } from '@/libs/queries/${config.entityNameLower}';

// GET /api/${config.entityNamePlural}/relations/options
export async function GET() {
  try {
    const { userId } = auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const relationOptions = await get${config.entityName}RelationOptions();

    return NextResponse.json({
      success: true,
      data: relationOptions,
    });
  } catch (error) {
    console.error('Error fetching relation options:', error);
    return NextResponse.json(
      { error: 'Failed to fetch relation options' },
      { status: 500 }
    );
  }
}`);
  }

  console.log(`✅ Generated: API routes for ${config.entityName}`);
}

/**
 * Generate React form component
 */
function generateFormComponent(config: EntityConfig): void {
  const relationFields = config.fields.filter(f => f.relation);
  const regularFields = config.fields.filter(f => !f.relation && f.name !== 'ownerId' && f.name !== 'id' && f.name !== 'createdAt' && f.name !== 'updatedAt');
  const belongsToFields = relationFields.filter(f => f.relation?.type === 'belongsTo');

  const formContent = `/**
 * ${config.entityName} Form Component with Relations Support
 * Generated by enhanced entity generator script V3 (complete)
 */

import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
${belongsToFields.length > 0 ? `import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';` : ''}

import { ${config.entityNameLower}FormSchema } from '@/libs/validations/${config.entityNameLower}';
import type { 
  ${config.entityName}FormData, 
  ${belongsToFields.length > 0 ? `${config.entityName}RelationOptions,` : ''}
  ${config.entityName}${relationFields.length > 0 ? 'WithRelations' : ''} 
} from '@/types/${config.entityNameLower}';

interface ${config.entityName}FormProps {
  ${config.entityNameLower}?: ${config.entityName}${relationFields.length > 0 ? 'WithRelations' : ''};
  onSubmit: (data: ${config.entityName}FormData) => Promise<void>;
  isLoading?: boolean;
}

export function ${config.entityName}Form({ ${config.entityNameLower}, onSubmit, isLoading }: ${config.entityName}FormProps) {
  ${belongsToFields.length > 0 ? `const [relationOptions, setRelationOptions] = useState<${config.entityName}RelationOptions>({
    ${belongsToFields.map(f => `${f.relation!.entityLower}s: []`).join(',\n    ')}
  });` : ''}

  const form = useForm<${config.entityName}FormData>({
    resolver: zodResolver(${config.entityNameLower}FormSchema),
    defaultValues: {
      ${[
        ...belongsToFields.map(f => `${f.relation!.foreignKey}: ${config.entityNameLower}?.${f.relation!.foreignKey} ?? undefined,`),
        ...regularFields.map(field => {
          if (field.type === 'boolean') {
            return `${field.name}: ${config.entityNameLower}?.${field.name} ?? false,`;
          } else if (field.type === 'number') {
            return `${field.name}: ${config.entityNameLower}?.${field.name} ?? 0,`;
          } else if (field.type === 'date') {
            return `${field.name}: ${config.entityNameLower}?.${field.name} ? new Date(${config.entityNameLower}.${field.name}).toISOString().split('T')[0] : '',`;
          } else {
            return `${field.name}: ${config.entityNameLower}?.${field.name} ?? '',`;
          }
        })
      ].join('\n      ')}
    },
  });

  ${belongsToFields.length > 0 ? `
  // Load relation options
  useEffect(() => {
    const loadRelationOptions = async () => {
      try {
        const response = await fetch('/api/${config.entityNamePlural}/relations/options');
        if (response.ok) {
          const data = await response.json();
          setRelationOptions(data.data);
        }
      } catch (error) {
        console.error('Failed to load relation options:', error);
      }
    };

    loadRelationOptions();
  }, []);` : ''}

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* BelongsTo Relation Fields */}
          ${belongsToFields.map(field => `
          <FormField
            control={form.control}
            name="${field.relation!.foreignKey}"
            render={({ field: formField }) => (
              <FormItem>
                <FormLabel>${field.label}</FormLabel>
                <Select 
                  onValueChange={(value) => formField.onChange(Number(value))}
                  value={formField.value?.toString()}
                >
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select ${field.label}" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    {relationOptions.${field.relation!.entityLower}s?.map((option) => (
                      <SelectItem key={option.id} value={option.id.toString()}>
                        {option.${field.relation!.displayField}}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />`).join('')}

          {/* Regular Fields */}
          ${regularFields.map(field => {
            if (field.type === 'text') {
              return `
          <div className="md:col-span-2">
            <FormField
              control={form.control}
              name="${field.name}"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>${field.label}</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Enter ${field.label.toLowerCase()}"
                      className="min-h-[100px]"
                      {...formField}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>`;
            } else if (field.type === 'date') {
              return `
          <FormField
            control={form.control}
            name="${field.name}"
            render={({ field: formField }) => (
              <FormItem>
                <FormLabel>${field.label}</FormLabel>
                <FormControl>
                  <Input
                    type="date"
                    {...formField}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />`;
            } else if (field.type === 'number') {
              return `
          <FormField
            control={form.control}
            name="${field.name}"
            render={({ field: formField }) => (
              <FormItem>
                <FormLabel>${field.label}</FormLabel>
                <FormControl>
                  <Input
                    type="number"
                    placeholder="Enter ${field.label.toLowerCase()}"
                    {...formField}
                    onChange={(e) => formField.onChange(Number(e.target.value))}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />`;
            } else {
              return `
          <FormField
            control={form.control}
            name="${field.name}"
            render={({ field: formField }) => (
              <FormItem>
                <FormLabel>${field.label}</FormLabel>
                <FormControl>
                  <Input
                    placeholder="Enter ${field.label.toLowerCase()}"
                    {...formField}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />`;
            }
          }).join('')}
        </div>

        <div className="flex justify-end gap-4">
          <Button type="submit" disabled={isLoading}>
            {isLoading ? 'Saving...' : ${config.entityNameLower} ? 'Update ${config.entityName}' : 'Create ${config.entityName}'}
          </Button>
        </div>
      </form>
    </Form>
  );
}`;

  writeFileToPath(`src/features/${config.entityNameLower}/${config.entityName}Form.tsx`, formContent);
  console.log(`✅ Generated: ${config.entityName}Form.tsx`);
}

/**
 * Main function with complete generation
 */
async function main() {
  const args = process.argv.slice(2);
  const entityName = args[0];
  const configFile = args[1];

  if (!entityName) {
    console.error('❌ Please provide entity name');
    console.log('Usage: npx tsx scripts/enhanced-generate-advanced-entity-V3-complete.ts [entityName] [configFile]');
    console.log('Example: npx tsx scripts/enhanced-generate-advanced-entity-V3-complete.ts plandetail configs/plandetail-config.ts');
    process.exit(1);
  }

  let config: EntityConfig;

  if (configFile) {
    // Load from external config file
    try {
      config = await loadEntityConfig(configFile, entityName);
    } catch (error) {
      console.error('❌ Failed to load config file');
      process.exit(1);
    }
  } else {
    // Use default config (fallback)
    config = {
      entityName: capitalizeFirst(entityName),
      entityNameLower: entityName.toLowerCase(),
      entityNamePlural: `${entityName.toLowerCase()}s`,
      tableName: entityName.toLowerCase(),
      codeField: 'code',
      nameField: 'name',
      fields: [
        {
          name: 'code',
          type: 'string',
          required: true,
          unique: true,
          maxLength: 50,
          label: 'Code',
          excelColumn: 'Code',
          dbColumnType: 'text',
        },
        {
          name: 'name',
          type: 'string',
          required: true,
          maxLength: 255,
          label: 'Name',
          excelColumn: 'Name',
          dbColumnType: 'text',
        },
        {
          name: 'ownerId',
          type: 'string',
          required: true,
          maxLength: 50,
          label: 'Owner ID',
          excelColumn: 'Owner ID',
          dbColumnType: 'text',
        },
      ],
      features: {
        pagination: true,
        search: true,
        sorting: true,
        stats: true,
        excelImport: true,
        excelExport: true,
        uniqueCode: true,
        batchOperations: true,
        relationships: false,
      },
      uiType: 'table',
    };
  }

  console.log(`🚀 Generating ${config.entityName} entity (Complete Version)...`);

  try {
    // Generate core files
    writeFileToPath(`src/models/Schema/${config.entityNameLower}.ts`, generateSchemaWithRelations(config));
    console.log(`✅ Generated: Schema with Relations`);

    writeFileToPath(`src/types/${config.entityNameLower}.ts`, generateCompleteTypesContent(config));
    console.log(`✅ Generated: Complete Types with Relations`);

    writeFileToPath(`src/libs/validations/${config.entityNameLower}.ts`, generateValidationContent(config));
    console.log(`✅ Generated: Validation Schemas`);

    writeFileToPath(`src/libs/queries/${config.entityNameLower}.ts`, generateQueriesContent(config));
    console.log(`✅ Generated: Database Queries with Relations`);

    // Generate API routes
    generateAPIRoutes(config);

    // Generate React components
    generateFormComponent(config);

    console.log(`\n🎉 ${config.entityName} entity generated successfully (Complete Version)!`);
    console.log('\n📋 Generated Files:');
    console.log('✅ Database Schema with Relations');
    console.log('✅ TypeScript Types with Relations');
    console.log('✅ Validation Schemas');
    console.log('✅ Database Queries with Joins');
    console.log('✅ Complete API Routes');
    console.log('✅ React Form Component');
    
    if (config.features.relationships) {
      console.log('\n📋 Relations Generated:');
      const relationFields = config.fields.filter(f => f.relation);
      relationFields.forEach(field => {
        const rel = field.relation!;
        console.log(`✅ ${rel.type}: ${config.entityName} -> ${rel.entity} (${rel.displayField})`);
      });
    }

    console.log('\n📋 Next steps:');
    console.log('1. Update src/models/Schema.ts to export new schemas');
    console.log('2. Run type check: npm run type-check');
    console.log('3. Test the generated entity');

  } catch (error) {
    console.error('❌ Error during generation:', error);
    process.exit(1);
  }
}

if (require.main === module) {
  main().catch(console.error);
}
