#!/usr/bin/env node

/**
 * Enhanced Advanced Entity Generator Script V3 - WITH RELATIONSHIPS SUPPORT
 * Modified for OutsourceOrderDetail entity
 * 
 * Usage: npx ts-node scripts/generate-outsource-order-detail.ts
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { outsourceOrderDetailConfig } from './outsource-order-detail-config';

// Import all the utility functions from the original script
// (Copy all the utility functions from enhanced-generate-advanced-entity-V3-with-relations.ts)

type FieldConfig = {
  name: string;
  type: 'string' | 'text' | 'number' | 'boolean' | 'date' | 'decimal' | 'relation';
  required: boolean;
  unique?: boolean;
  maxLength?: number;
  label: string;
  excelColumn?: string;
  dbColumnType?: 'text' | 'integer' | 'decimal' | 'boolean' | 'date' | 'timestamp';
  
  relation?: {
    type: 'belongsTo' | 'hasMany' | 'manyToMany';
    entity: string;
    entityLower: string;
    foreignKey: string;
    referenceKey?: string;
    displayField: string;
    nullable?: boolean;
    onDelete?: 'cascade' | 'restrict' | 'setNull';
    
    junctionTable?: string;
    junctionFields?: {
      currentKey: string;
      relatedKey: string;
    };
  };
};

type EntityConfig = {
  entityName: string;
  entityNameLower: string;
  entityNamePlural: string;
  tableName: string;
  codeField: string;
  nameField: string;
  fields: FieldConfig[];
  features: {
    pagination: boolean;
    search: boolean;
    sorting: boolean;
    stats: boolean;
    excelImport: boolean;
    excelExport: boolean;
    uniqueCode: boolean;
    batchOperations: boolean;
    relationships: boolean;
  };
  uiType: 'table' | 'cards';
};

/**
 * 🆕 Generate database schema with relationships
 */
function generateSchemaWithRelations(config: EntityConfig): string {
  const relationFields = config.fields.filter(f => f.relation);
  const regularFields = config.fields.filter(f => !f.relation && f.name !== 'id' && f.name !== 'createdAt' && f.name !== 'updatedAt');
  
  let schemaContent = `/**
 * ${config.entityName} Database Schema with Relations
 * Generated by enhanced entity generator script V3
 */

import { relations } from 'drizzle-orm';
import { pgTable, serial, text, integer, timestamp, boolean, decimal, date } from 'drizzle-orm/pg-core';
${relationFields.length > 0 ? `\n// Import related schemas\n${relationFields
    .map(f => `import { ${f.relation!.entityLower}Schema } from './${f.relation!.entityLower}';`)
    .join('\n')}` : ''}

export const ${config.entityNameLower}Schema = pgTable('${config.tableName}', {
  id: serial('id').primaryKey(),
  
  // Regular fields
${regularFields.map(field => {
    const column = getColumnDefinition(field);
    return `  ${field.name}: ${column},`;
  }).join('\n')}

  // Foreign key fields
${relationFields
    .filter(f => f.relation?.type === 'belongsTo')
    .map(field => {
      const nullable = field.relation?.nullable ? '' : '.notNull()';
      const onDelete = field.relation?.onDelete || 'restrict';
      return `  ${field.relation!.foreignKey}: integer('${field.relation!.foreignKey}')${nullable}.references(() => ${field.relation!.entityLower}Schema.id, { onDelete: '${onDelete}' }),`;
    }).join('\n')}

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

// Relations configuration
export const ${config.entityNameLower}Relations = relations(${config.entityNameLower}Schema, ({ one, many }) => ({
${relationFields.map(field => {
    const rel = field.relation!;
    if (rel.type === 'belongsTo') {
      return `  ${rel.entityLower}: one(${rel.entityLower}Schema, {
    fields: [${config.entityNameLower}Schema.${rel.foreignKey}],
    references: [${rel.entityLower}Schema.${rel.referenceKey || 'id'}],
    relationName: '${config.entityNameLower}_${rel.entityLower}',
  }),`;
    }
    return '';
  }).filter(Boolean).join('\n')}
}));`;

  return schemaContent;
}

/**
 * Get column definition for database schema
 */
function getColumnDefinition(field: FieldConfig): string {
  const nullable = field.required ? '.notNull()' : '';
  const unique = field.unique ? '.unique()' : '';
  
  switch (field.dbColumnType) {
    case 'text':
      return `text('${field.name}')${field.maxLength ? `.max(${field.maxLength})` : ''}${nullable}${unique}`;
    case 'integer':
      return `integer('${field.name}')${nullable}${unique}`;
    case 'decimal':
      return `decimal('${field.name}', { precision: 12, scale: 2 })${nullable}${unique}`;
    case 'boolean':
      return `boolean('${field.name}')${nullable}`;
    case 'date':
      return `date('${field.name}')${nullable}`;
    case 'timestamp':
      return `timestamp('${field.name}')${nullable}`;
    default:
      return `text('${field.name}')${nullable}${unique}`;
  }
}

// Copy other utility functions from the original script...
// (generateInsertValues, generateUpdateValues, generateValidationSchema, etc.)

/**
 * Write file to path with directory creation
 */
function writeFileToPath(targetPath: string, content: string): void {
  const targetDir = join(targetPath, '..');
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }
  writeFileSync(targetPath, content);
}

/**
 * Enhanced file generation with better error handling and relations support
 */
function generateFile(sourcePath: string, targetPath: string, config: EntityConfig): void {
  try {
    // Special handling for schema files
    if (targetPath.includes('models/Schema') && targetPath.endsWith('.ts')) {
      const generatedContent = generateSchemaWithRelations(config);
      writeFileToPath(targetPath, generatedContent);
      console.log(`✅ Generated (Schema with Relations): ${targetPath}`);
      return;
    }

    // Handle other specialized files...
    // (Copy the generateFile logic from original script)
    
    console.log(`✅ Generated: ${targetPath}`);
  } catch (error) {
    console.error(`❌ Error generating ${targetPath}:`, error);
  }
}

/**
 * Main function for OutsourceOrderDetail generation
 */
function main() {
  const config = outsourceOrderDetailConfig;

  console.log(`🚀 Generating ${config.entityName} entity with Relations Support...`);

  // Enhanced file mappings with relations support
  const fileMappings = [
    // Core files - generate from scratch with relations
    ['', `src/models/Schema/${config.entityNameLower}.ts`],
    ['', `src/types/${config.entityNameLower}.ts`],
    ['', `src/libs/queries/${config.entityNameLower}.ts`],
    ['', `src/libs/validations/${config.entityNameLower}.ts`],

    // API routes with relations support
    ['', `src/app/api/${config.entityNamePlural}/route.ts`],
    ['', `src/app/api/${config.entityNamePlural}/[id]/route.ts`],
    ['', `src/app/api/${config.entityNamePlural}/stats/route.ts`],
    ['', `src/app/api/${config.entityNamePlural}/export/route.ts`],
    ['', `src/app/api/${config.entityNamePlural}/import/route.ts`],
    
    // Relations API routes
    ['', `src/app/api/${config.entityNamePlural}/relations/options/route.ts`],

    // React components with relations support
    ['', `src/features/${config.entityNameLower}/${config.entityName}Form.tsx`],
    ['', `src/features/${config.entityNameLower}/${config.entityName}List.tsx`],
    ['', `src/features/${config.entityNameLower}/${config.entityName}Skeleton.tsx`],

    // Hooks with relations support
    ['', `src/hooks/use${config.entityName}s.ts`],
    ['', `src/hooks/use${config.entityName}Mutations.ts`],
    ['', `src/hooks/use${config.entityName}Relations.ts`],

    // Pages
    ['', `src/app/[locale]/(auth)/dashboard/${config.entityNamePlural}/page.tsx`],
  ];

  // Generate all files
  fileMappings.forEach(([source, target]) => {
    generateFile(source, target, config);
  });

  console.log(`\n🎉 ${config.entityName} entity generated successfully with Relations Support!`);
  console.log('\n📋 Generated Relations:');
  const relationFields = config.fields.filter(f => f.relation);
  relationFields.forEach(field => {
    const rel = field.relation!;
    console.log(`✅ ${rel.type}: ${config.entityName} -> ${rel.entity} (${rel.displayField})`);
  });

  console.log('\n📋 Next steps:');
  console.log('1. Update src/models/Schema.ts to export new schemas');
  console.log('2. Run database migration if needed');
  console.log('3. Run type check: npm run type-check');
  console.log('4. Test the generated entity with relations');
}

if (require.main === module) {
  main();
}
