#!/usr/bin/env node

/**
 * Simple PlanDetail Entity Generator
 * Direct generation without external config complexity
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Import the config directly
const planDetailConfig = {
  entityName: 'PlanDetail',
  entityNameLower: 'plandetail',
  entityNamePlural: 'plandetails',
  tableName: 'plan_detail',
  codeField: 'locationCode',
  nameField: 'productSubCode',
  fields: [
    // Plan Relationship (belongsTo - required)
    {
      name: 'plan',
      type: 'relation',
      required: true,
      label: 'Plan',
      excelColumn: 'Plan Code',
      relation: {
        type: 'belongsTo',
        entity: 'Plan',
        entityLower: 'plan',
        foreignKey: 'planId',
        displayField: 'planCode',
        onDelete: 'cascade'
      }
    },
    // Location & Resource Allocation
    {
      name: 'locationCode',
      type: 'string',
      required: true,
      maxLength: 50,
      label: 'Location Code',
      excelColumn: 'Location Code',
      dbColumnType: 'text',
    },
    {
      name: 'locationType',
      type: 'string',
      required: false,
      maxLength: 50,
      label: 'Location Type',
      excelColumn: 'Location Type',
      dbColumnType: 'text',
    },
    // Product Reference
    {
      name: 'productCode',
      type: 'string',
      required: true,
      maxLength: 50,
      label: 'Product Code',
      excelColumn: 'Product Code',
      dbColumnType: 'text',
    },
    {
      name: 'productSubCode',
      type: 'string',
      required: true,
      maxLength: 100,
      label: 'Product Sub Code',
      excelColumn: 'Product Sub Code',
      dbColumnType: 'text',
    },
    // Quantity Planning
    {
      name: 'plannedQuantity',
      type: 'number',
      required: true,
      label: 'Planned Quantity',
      excelColumn: 'Planned Quantity',
      dbColumnType: 'integer',
    },
    {
      name: 'actualQuantity',
      type: 'number',
      required: false,
      label: 'Actual Quantity',
      excelColumn: 'Actual Quantity',
      dbColumnType: 'integer',
    },
    // Scheduling
    {
      name: 'plannedStartDate',
      type: 'date',
      required: false,
      label: 'Planned Start Date',
      excelColumn: 'Planned Start Date',
      dbColumnType: 'date',
    },
    {
      name: 'plannedEndDate',
      type: 'date',
      required: false,
      label: 'Planned End Date',
      excelColumn: 'Planned End Date',
      dbColumnType: 'date',
    },
    {
      name: 'actualStartDate',
      type: 'date',
      required: false,
      label: 'Actual Start Date',
      excelColumn: 'Actual Start Date',
      dbColumnType: 'date',
    },
    {
      name: 'actualEndDate',
      type: 'date',
      required: false,
      label: 'Actual End Date',
      excelColumn: 'Actual End Date',
      dbColumnType: 'date',
    },
    // Status & Priority
    {
      name: 'status',
      type: 'string',
      required: false,
      maxLength: 50,
      label: 'Status',
      excelColumn: 'Status',
      dbColumnType: 'text',
    },
    {
      name: 'priority',
      type: 'number',
      required: false,
      label: 'Priority',
      excelColumn: 'Priority',
      dbColumnType: 'integer',
    },
    {
      name: 'note',
      type: 'text',
      required: false,
      label: 'Note',
      excelColumn: 'Note',
      dbColumnType: 'text',
    },
    // Owner (always required for multi-tenancy)
    {
      name: 'ownerId',
      type: 'string',
      required: true,
      maxLength: 50,
      label: 'Owner ID',
      excelColumn: 'Owner ID',
      dbColumnType: 'text',
    },
  ],
  features: {
    pagination: true,
    search: true,
    sorting: true,
    stats: true,
    excelImport: true,
    excelExport: true,
    uniqueCode: false,
    batchOperations: true,
    relationships: true,
  },
  uiType: 'table',
};

/**
 * Generate TypeScript types file
 */
function generateTypesFile() {
  const content = `/**
 * PlanDetail-related TypeScript types and interfaces
 * Enhanced version with proper error handling, type safety and relationships support
 * Generated by simple PlanDetail generator
 */

import type { planDetailSchema } from '@/models/Schema';
import type { Plan } from '@/types/plan';

// Infer the PlanDetailDb type from Drizzle schema
export type PlanDetailDb = typeof planDetailSchema.$inferSelect;

// Client-side PlanDetail type with proper date handling
export type PlanDetail = Omit<PlanDetailDb, 'createdAt' | 'updatedAt'> & {
  readonly createdAt: string | Date;
  readonly updatedAt: string | Date;
};

// PlanDetail with relations
export type PlanDetailWithRelations = PlanDetail & {
  plan?: Pick<Plan, 'id' | 'planCode'>;
};

// Form data type for React Hook Form
export type PlanDetailFormData = {
  planId: number;
  locationCode: string;
  locationType?: string;
  productCode: string;
  productSubCode: string;
  plannedQuantity: number;
  actualQuantity?: number;
  plannedStartDate?: string;
  plannedEndDate?: string;
  actualStartDate?: string;
  actualEndDate?: string;
  status?: string;
  priority?: number;
  note?: string;
};

// Input types for CRUD operations
export type CreatePlanDetailInput = {
  readonly ownerId: string;
  planId: number;
  locationCode: string;
  locationType?: string;
  productCode: string;
  productSubCode: string;
  plannedQuantity: number;
  actualQuantity?: number;
  plannedStartDate?: Date | string;
  plannedEndDate?: Date | string;
  actualStartDate?: Date | string;
  actualEndDate?: Date | string;
  status?: string;
  priority?: number;
  note?: string;
};

export type UpdatePlanDetailInput = {
  planId?: number;
  locationCode?: string;
  locationType?: string;
  productCode?: string;
  productSubCode?: string;
  plannedQuantity?: number;
  actualQuantity?: number;
  plannedStartDate?: Date | string;
  plannedEndDate?: Date | string;
  actualStartDate?: Date | string;
  actualEndDate?: Date | string;
  status?: string;
  priority?: number;
  note?: string;
};

// Relation options for dropdowns
export type PlanDetailRelationOptions = {
  readonly plans: readonly Pick<Plan, 'id' | 'planCode'>[];
};

// API Response types
export type PlanDetailResponse = {
  readonly success: true;
  readonly data: PlanDetailWithRelations;
  readonly message?: string;
};

export type PlanDetailsResponse = {
  readonly success: true;
  readonly data: readonly PlanDetailWithRelations[];
  readonly pagination: {
    readonly page: number;
    readonly limit: number;
    readonly total: number;
    readonly hasMore: boolean;
  };
};

export type PlanDetailErrorResponse = {
  readonly success: false;
  readonly error: string;
  readonly code: string;
  readonly details?: unknown;
};

// List parameters
export type PlanDetailListParams = {
  readonly page?: number;
  readonly limit?: number;
  readonly search?: string;
  readonly sortBy?: 'createdAt' | 'updatedAt' | 'productSubCode' | 'locationCode';
  readonly sortOrder?: 'asc' | 'desc';
  readonly showAll?: boolean;
  readonly includeRelations?: boolean;
};

export type PlanDetailListParamsWithOwner = PlanDetailListParams & {
  readonly ownerId: string;
};

// Export parameters for Excel functionality
export type PlanDetailExportParams = PlanDetailListParams;

// Import validation result
export type ImportPlanDetailResult = {
  readonly success: boolean;
  readonly imported: number;
  readonly failed: number;
  readonly errors: readonly string[];
  readonly plandetails: readonly PlanDetail[];
};

// Statistics type
export type PlanDetailStats = {
  readonly total: number;
  readonly today: number;
  readonly thisWeek: number;
  readonly thisMonth: number;
};

export type PlanDetailStatsResponse = {
  readonly success: true;
  readonly data: PlanDetailStats;
};

// Filter state
export type PlanDetailFilters = {
  search: string;
  sortBy: 'createdAt' | 'updatedAt' | 'productSubCode' | 'locationCode';
  sortOrder: 'asc' | 'desc';
};`;

  return content;
}

/**
 * Generate validation file
 */
function generateValidationFile() {
  return `/**
 * PlanDetail validation schemas with Relations Support
 * Enhanced version with proper error handling, type safety and relationships
 * Generated by simple PlanDetail generator
 */

import { z } from 'zod';

// Form validation schema with relations
export const planDetailFormSchema = z.object({
  planId: z.number().int().positive('Plan is required'),
  locationCode: z.string().trim().min(1, 'Location Code is required').max(50, 'Location Code must be 50 characters or less').regex(/^[\\w-]+$/, 'Location Code can only contain letters, numbers, underscores and dashes'),
  locationType: z.string().trim().max(50, 'Location Type must be 50 characters or less').optional(),
  productCode: z.string().trim().min(1, 'Product Code is required').max(50, 'Product Code must be 50 characters or less').regex(/^[\\w-]+$/, 'Product Code can only contain letters, numbers, underscores and dashes'),
  productSubCode: z.string().trim().min(1, 'Product Sub Code is required').max(100, 'Product Sub Code must be 100 characters or less').regex(/^[\\w-]+$/, 'Product Sub Code can only contain letters, numbers, underscores and dashes'),
  plannedQuantity: z.number().int().min(0),
  actualQuantity: z.number().int().min(0).optional(),
  plannedStartDate: z.union([z.string(), z.date()]).optional(),
  plannedEndDate: z.union([z.string(), z.date()]).optional(),
  actualStartDate: z.union([z.string(), z.date()]).optional(),
  actualEndDate: z.union([z.string(), z.date()]).optional(),
  status: z.string().trim().max(50, 'Status must be 50 characters or less').optional(),
  priority: z.number().int().min(1).max(10).optional(),
  note: z.string().trim().optional(),
});

// Create plandetail schema (same as form + ownerId)
export const createPlanDetailSchema = planDetailFormSchema.extend({
  ownerId: z.string().min(1, 'Owner ID is required'),
});

// Update plandetail schema (all fields optional)
export const updatePlanDetailSchema = z.object({
  planId: z.number().int().positive().optional(),
  locationCode: z.string().trim().min(1, 'Location Code is required').max(50, 'Location Code must be 50 characters or less').regex(/^[\\w-]+$/, 'Location Code can only contain letters, numbers, underscores and dashes').optional(),
  locationType: z.string().trim().max(50, 'Location Type must be 50 characters or less').optional(),
  productCode: z.string().trim().min(1, 'Product Code is required').max(50, 'Product Code must be 50 characters or less').regex(/^[\\w-]+$/, 'Product Code can only contain letters, numbers, underscores and dashes').optional(),
  productSubCode: z.string().trim().min(1, 'Product Sub Code is required').max(100, 'Product Sub Code must be 100 characters or less').regex(/^[\\w-]+$/, 'Product Sub Code can only contain letters, numbers, underscores and dashes').optional(),
  plannedQuantity: z.number().int().min(0).optional(),
  actualQuantity: z.number().int().min(0).optional(),
  plannedStartDate: z.union([z.string(), z.date()]).optional(),
  plannedEndDate: z.union([z.string(), z.date()]).optional(),
  actualStartDate: z.union([z.string(), z.date()]).optional(),
  actualEndDate: z.union([z.string(), z.date()]).optional(),
  status: z.string().trim().max(50, 'Status must be 50 characters or less').optional(),
  priority: z.number().int().min(1).max(10).optional(),
  note: z.string().trim().optional(),
});

// List parameters validation
export const planDetailListParamsSchema = z.object({
  page: z.number().int().min(1).default(1),
  limit: z.number().int().min(1).max(100).default(10),
  search: z.string().trim().max(255).optional(),
  sortBy: z.enum(['createdAt', 'updatedAt', 'productSubCode', 'locationCode']).default('createdAt'),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
  showAll: z.boolean().default(false),
  includeRelations: z.boolean().default(false),
});

// Export parameters validation
export type PlanDetailExportParams = z.infer<typeof planDetailListParamsSchema>;

// Import row validation for Excel import with relations
export const importPlanDetailRowSchema = z.object({
  planId: z.number().int().positive('Plan is required'),
  locationCode: z.string().trim().min(1, 'Location Code is required').max(50, 'Location Code must be 50 characters or less').regex(/^[\\w-]+$/, 'Location Code can only contain letters, numbers, underscores and dashes'),
  locationType: z.string().trim().max(50, 'Location Type must be 50 characters or less').optional(),
  productCode: z.string().trim().min(1, 'Product Code is required').max(50, 'Product Code must be 50 characters or less').regex(/^[\\w-]+$/, 'Product Code can only contain letters, numbers, underscores and dashes'),
  productSubCode: z.string().trim().min(1, 'Product Sub Code is required').max(100, 'Product Sub Code must be 100 characters or less').regex(/^[\\w-]+$/, 'Product Sub Code can only contain letters, numbers, underscores and dashes'),
  plannedQuantity: z.number().int().min(0),
  actualQuantity: z.number().int().min(0).optional(),
  plannedStartDate: z.union([z.string(), z.date()]).optional(),
  plannedEndDate: z.union([z.string(), z.date()]).optional(),
  actualStartDate: z.union([z.string(), z.date()]).optional(),
  actualEndDate: z.union([z.string(), z.date()]).optional(),
  status: z.string().trim().max(50, 'Status must be 50 characters or less').optional(),
  priority: z.number().int().min(1).max(10).optional(),
  note: z.string().trim().optional(),
  rowNumber: z.number().int().positive(),
});

// ID validation
export const planDetailIdSchema = z.object({
  id: z.string().regex(/^\\d+$/, 'ID must be a valid number').transform(Number),
});

// Validation helper functions
export function validatePlanDetailId(data: unknown) {
  return planDetailIdSchema.parse(data);
}

export function validatePlanDetailForm(data: unknown) {
  return planDetailFormSchema.parse(data);
}

export function validateCreatePlanDetail(data: unknown) {
  return createPlanDetailSchema.parse(data);
}

export function validateUpdatePlanDetail(data: unknown) {
  return updatePlanDetailSchema.parse(data);
}

export function validatePlanDetailListParams(data: unknown) {
  return planDetailListParamsSchema.parse(data);
}`;
}

/**
 * Write file to path with directory creation
 */
function writeFileToPath(targetPath: string, content: string): void {
  const targetDir = join(targetPath, '..');
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }
  writeFileSync(targetPath, content);
}

/**
 * Main generation function
 */
function main() {
  console.log('🚀 Generating PlanDetail entity (simple version)...');

  try {
    // Generate types file
    const typesContent = generateTypesFile();
    writeFileToPath('src/types/plandetail.ts', typesContent);
    console.log('✅ Generated: src/types/plandetail.ts');

    // Generate validation file
    const validationContent = generateValidationFile();
    writeFileToPath('src/libs/validations/plandetail.ts', validationContent);
    console.log('✅ Generated: src/libs/validations/plandetail.ts');

    console.log('\\n🎉 PlanDetail entity generated successfully!');
    console.log('\\n📋 Generated Files:');
    console.log('✅ src/types/plandetail.ts - TypeScript types');
    console.log('✅ src/libs/validations/plandetail.ts - Zod validation schemas');
    
    console.log('\\n📋 Next steps:');
    console.log('1. Review generated files');
    console.log('2. Run type check: npm run type-check');
    console.log('3. Generate remaining files (queries, API routes, components) as needed');

  } catch (error) {
    console.error('❌ Error generating files:', error);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}
