/**
 * EmployeeSalaryEntry Enhanced Form Component with Complex Features
 * Generated by enhanced entity generator script V4
 * 🆕 Features: Text FK Support, Decimal Formatting, Business Logic, Complex Validation
 */

import { zodResolver } from '@hookform/resolvers/zod';
import { format } from 'date-fns';
import { CalendarIcon } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useCallback, useEffect, useState } from 'react';
import { FormProvider, useForm, useWatch } from 'react-hook-form';

import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { employeeSalaryEntryFormSchema } from '@/libs/validations/employeeSalaryEntry';
import type {
  EmployeeSalaryEntryFormData,
  EmployeeSalaryEntryRelationOptions,
  EmployeeSalaryEntryWithRelations,
} from '@/types/employeeSalaryEntry';

// Hàm cn: nối className tiện dụng
function cn(...args: (string | undefined | false | null)[]) {
  return args.filter(Boolean).join(' ');
}

type EmployeeSalaryEntryFormProps = {
  employeeSalaryEntry?: EmployeeSalaryEntryWithRelations;
  onSubmit: (data: EmployeeSalaryEntryFormData) => Promise<void>;
  isLoading?: boolean;
  mode?: 'create' | 'edit';
  onSuccess?: (employeeSalaryEntry: EmployeeSalaryEntryWithRelations) => void;
  onCancel?: () => void;
};

export function EmployeeSalaryEntryForm({
  employeeSalaryEntry,
  onSubmit,
  isLoading = false,
  mode = 'create',
  onSuccess,
  onCancel,
}: EmployeeSalaryEntryFormProps) {
  const [relationOptions, setRelationOptions] = useState<EmployeeSalaryEntryRelationOptions>({
    userSyncs: [],
    productionStepDetails: [],
    plans: [],
    products: [], // 🆕 Add products array
  });

  // 🆕 State for filtered production step details based on selected product
  const [filteredProductionStepDetails, setFilteredProductionStepDetails] = useState<{
    id: number;
    stepName?: string;
  }[]>([]);

  // 🆕 State for shortcut functionality
  const [shortcutValue, setShortcutValue] = useState('');
  const [shortcutMessage, setShortcutMessage] = useState('');
  const [shortcutError, setShortcutError] = useState('');

  // 🆕 State for product code functionality
  const [productCodeValue, setProductCodeValue] = useState('');
  const [productCodeMessage, setProductCodeMessage] = useState('');
  const [productCodeError, setProductCodeError] = useState('');

  // 🆕 State for form error
  const [formError, setFormError] = useState<string | null>(null);

  const form = useForm<EmployeeSalaryEntryFormData>({
    resolver: zodResolver(employeeSalaryEntryFormSchema),
    defaultValues: {
      workDate: employeeSalaryEntry?.workDate ? new Date(employeeSalaryEntry.workDate).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
      entryDate: employeeSalaryEntry?.entryDate
        ? new Date(employeeSalaryEntry.entryDate).toISOString().split('T')[0]
        : new Date().toISOString().split('T')[0],
      actualQuantity: employeeSalaryEntry?.actualQuantity ?? 0,
      plannedQuantity: employeeSalaryEntry?.plannedQuantity ?? undefined,
      limitQuantity: employeeSalaryEntry?.limitQuantity ?? undefined,
      previousEnteredQuantity: employeeSalaryEntry?.previousEnteredQuantity ?? undefined,
      unitPrice: typeof employeeSalaryEntry?.unitPrice === 'number' ? employeeSalaryEntry.unitPrice : undefined,
      totalAmount: typeof employeeSalaryEntry?.totalAmount === 'number' ? employeeSalaryEntry.totalAmount : undefined,
      salaryNote: employeeSalaryEntry?.salaryNote ?? '',
      status: employeeSalaryEntry?.status || 'draft', // Force draft for new entries
      approvedBy: employeeSalaryEntry?.approvedBy ?? '',
      approvedAt: undefined,
      startTime: undefined,
      endTime: undefined,
      workDurationMinutes: undefined,
      userId: employeeSalaryEntry?.userId ?? undefined,
      productionStepDetailId: typeof employeeSalaryEntry?.productionStepDetail === 'object' && employeeSalaryEntry.productionStepDetail !== null && typeof employeeSalaryEntry.productionStepDetail.id === 'number'
        ? employeeSalaryEntry.productionStepDetail.id
        : undefined,
      planId: employeeSalaryEntry?.planId ?? undefined,
      productId: employeeSalaryEntry?.productId ?? undefined, // 🆕 Add productId default
    },
  });

  const t = useTranslations('EmployeeSalaryEntryForm');

  // 🆕 V4: Load relation options with error handling
  useEffect(() => {
    const loadRelationOptions = async () => {
      try {
        const response = await fetch('/api/employeeSalaryEntries/relations/options');
        if (response.ok) {
          const data = await response.json();
          setRelationOptions(data.data);
        } else {
          console.error('Failed to load relation options:', response.statusText);
        }
      } catch (error) {
        console.error('Error loading relation options:', error);
      }
    };

    loadRelationOptions();
  }, []);

  // 🆕 Function to handle shortcut search
  const handleShortcutSearch = useCallback((shortcut: string) => {
    setShortcutValue(shortcut);
    setShortcutError('');
    setShortcutMessage('');

    if (!shortcut.trim()) {
      return;
    }

    // Find employee by shortcut
    const matchedEmployee = relationOptions.userSyncs.find(
      user => user.shortcut && user.shortcut.toLowerCase() === shortcut.toLowerCase().trim(),
    );

    if (matchedEmployee) {
      // Auto-populate employee selection
      form.setValue('userId', matchedEmployee.userId);
      setShortcutMessage(`✅ Found: ${matchedEmployee.fullName}`);
    } else {
      setShortcutError(`❌ No employee found with shortcut: "${shortcut}"`);
    }
  }, [relationOptions.userSyncs, form]);

  // 🆕 Function to handle product code search
  const handleProductCodeSearch = useCallback((productCode: string) => {
    setProductCodeValue(productCode);
    setProductCodeError('');
    setProductCodeMessage('');

    if (!productCode.trim()) {
      return;
    }

    // Find product by product code
    const matchedProduct = relationOptions.products.find(
      product => product.productCode && product.productCode.toLowerCase() === productCode.toLowerCase().trim(),
    );

    if (matchedProduct) {
      // Auto-populate product selection
      form.setValue('productId', matchedProduct.id);
      setProductCodeMessage(`✅ Found: ${matchedProduct.productName}`);
    } else {
      setProductCodeError(`❌ No product found with code: "${productCode}"`);
    }
  }, [relationOptions.products, form]);

  // 🆕 V4: Watch for changes in actualQuantity and unitPrice to auto-calculate totalAmount
  const actualQuantity = useWatch({ control: form.control, name: 'actualQuantity' });
  const unitPrice = useWatch({ control: form.control, name: 'unitPrice' });

  // 🆕 Watch for productId changes to load filtered production step details
  const productId = useWatch({ control: form.control, name: 'productId' });

  useEffect(() => {
    if (actualQuantity && unitPrice) {
      const calculatedTotal = Number(actualQuantity) * Number(unitPrice);
      form.setValue('totalAmount', calculatedTotal);
    }
  }, [actualQuantity, unitPrice, form]);

  // 🆕 Load filtered production step details when product changes
  useEffect(() => {
    const loadProductionStepDetails = async () => {
      if (productId) {
        try {
          const response = await fetch(`/api/employeeSalaryEntries/relations/production-step-details?productId=${productId}`);
          if (response.ok) {
            const data = await response.json();
            setFilteredProductionStepDetails(data.data);
            // Reset productionStepDetailId when product changes
            form.setValue('productionStepDetailId', undefined);
          } else {
            console.error('Failed to load production step details:', response.statusText);
            setFilteredProductionStepDetails([]);
          }
        } catch (error) {
          console.error('Error loading production step details:', error);
          setFilteredProductionStepDetails([]);
        }
      } else {
        // Clear production step details if no product selected
        setFilteredProductionStepDetails([]);
        form.setValue('productionStepDetailId', undefined);
      }
    };

    loadProductionStepDetails();
  }, [productId, form]);

  // 🆕 V4: Auto-calculate work duration from start/end times
  const startTime = useWatch({ control: form.control, name: 'startTime' });
  const endTime = useWatch({ control: form.control, name: 'endTime' });

  useEffect(() => {
    if (startTime && endTime) {
      const start = new Date(startTime);
      const end = new Date(endTime);
      if (end > start) {
        const durationMs = end.getTime() - start.getTime();
        const durationMinutes = Math.round(durationMs / (1000 * 60));
        form.setValue('workDurationMinutes', durationMinutes);
      }
    }
  }, [startTime, endTime, form]);

  // 🆕 V4: Enhanced form submission with validation
  const handleSubmit = useCallback(async (data: EmployeeSalaryEntryFormData) => {
    try {
      // Check for required fields before submission
      if (!data.userId) {
        setFormError('Please select an Employee');
        return;
      }
      if (!data.productionStepDetailId) {
        setFormError('Please select a Production Step Detail');
        return;
      }
      if (!data.planId) {
        setFormError('Please select a Plan');
        return;
      }
      if (!data.productId) {
        setFormError('Please select a Product');
        return;
      }

      // Force set status to draft if empty
      if (!data.status || data.status.trim() === '') {
        data.status = 'draft';
      }

      // Xóa lỗi trước khi submit
      setFormError(null);
      await onSubmit(data);
      if (onSuccess) {
        onSuccess(employeeSalaryEntry!);
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to save';
      setFormError(errorMessage);
    }
  }, [onSubmit, onSuccess, employeeSalaryEntry]);

  return (
    <FormProvider {...form}>
      <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-6">
        {formError && (
          <div className="mb-4 rounded border border-red-300 bg-red-100 px-4 py-2 text-red-700">
            {(() => {
              if (formError === 'Please select an Employee') {
                return t('required_employee');
              }
              if (formError === 'Please select a Production Step Detail') {
                return t('required_production_step_detail');
              }
              if (formError === 'Please select a Plan') {
                return t('required_plan');
              }
              if (formError === 'Please select a Product') {
                return t('required_product');
              }
              if (formError === 'Failed to save') {
                return t('failed_to_save');
              }
              return formError;
            })()}
          </div>
        )}
        <div className="flex flex-col gap-6">

          {/* Employee Section */}
          <div className="flex flex-row items-center gap-4 rounded-lg p-2" style={{ background: 'var(--field-bg-employee, #e0f2fe)' }}>
            {/* 🆕 Shortcut Input Field */}
            <div className="w-1/5 min-w-[180px]">
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="employee-shortcut">{t('employee_shortcut')}</label>
                <Input
                  id="employee-shortcut"
                  placeholder={t('employee_shortcut_placeholder')}
                  value={shortcutValue}
                  onChange={e => handleShortcutSearch(e.target.value)}
                  className="text-sm"
                />
                {shortcutMessage && (
                  <p className="text-xs font-medium text-green-600">{t('employee_shortcut_found', { name: shortcutMessage.replace('✅ Found: ', '') })}</p>
                )}
                {shortcutError && (
                  <p className="text-xs font-medium text-red-600">{t('employee_shortcut_not_found', { shortcut: shortcutValue })}</p>
                )}
              </div>
            </div>

            <div className="w-1/4 min-w-[220px]">
              <FormField
                control={form.control}
                name="userId"
                render={({ field: formField }) => (
                  <FormItem>
                    <FormLabel>{t('employee')}</FormLabel>
                    <Select
                      onValueChange={(value) => {
                        formField.onChange(value);
                        // Clear shortcut messages when manually selecting
                        setShortcutMessage('');
                        setShortcutError('');
                      }}
                      value={formField.value?.toString()}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('select_employee')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.userSyncs?.map(option => (
                          <SelectItem key={option.userId} value={option.userId.toString()}>
                            {option.fullName}
                            {' '}
                            {option.shortcut ? `(${option.shortcut})` : ''}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <div className="flex h-full min-w-[200px] items-center text-sm text-muted-foreground">
              {/* Hiển thị tên nhân viên đã chọn, nổi bật, lớn hơn, căn phải */}
              <div className="flex flex-1 items-center justify-end">
                {(() => {
                  const selected = relationOptions.userSyncs.find(u => u.userId.toString() === form.watch('userId'));
                  if (selected && selected.fullName) {
                    return <span className="text-2xl font-semibold text-gray-900">{selected.fullName}</span>;
                  }
                  return null;
                })()}
              </div>
            </div>
          </div>

          {/* Product Section - moved up */}
          <div className="flex flex-row items-center gap-4 rounded-lg p-2" style={{ background: 'var(--field-bg-product, #f0fdf4)' }}>
            {/* 🆕 Product Code Input Field */}
            <div className="w-1/5 min-w-[180px]">
              <div className="space-y-2">
                <label className="text-sm font-medium" htmlFor="product-code">{t('product_code')}</label>
                <Input
                  id="product-code"
                  placeholder={t('product_code_placeholder')}
                  value={productCodeValue}
                  onChange={e => handleProductCodeSearch(e.target.value)}
                  className="text-sm"
                />
                {productCodeMessage && (
                  <p className="text-xs font-medium text-green-600">{t('product_code_found', { name: productCodeMessage.replace('✅ Found: ', '') })}</p>
                )}
                {productCodeError && (
                  <p className="text-xs font-medium text-red-600">{t('product_code_not_found', { code: productCodeValue })}</p>
                )}
              </div>
            </div>

            <div className="w-1/4 min-w-[220px]">
              <FormField
                control={form.control}
                name="productId"
                render={({ field: formField }) => (
                  <FormItem>
                    <FormLabel>{t('product')}</FormLabel>
                    <Select
                      onValueChange={(value) => {
                        formField.onChange(Number(value));
                        // Clear product code messages when manually selecting
                        setProductCodeMessage('');
                        setProductCodeError('');
                      }}
                      value={formField.value?.toString()}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('select_product')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.products?.map(option => (
                          <SelectItem key={option.id} value={option.id.toString()}>
                            {option.productName}
                            {' '}
                            (
                            {option.productCode}
                            )
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <div className="flex h-full min-w-[200px] items-center text-sm text-muted-foreground">
              {/* Hiển thị tên product đã chọn, nổi bật, lớn hơn, căn phải */}
              <div className="flex flex-1 items-center justify-end">
                {(() => {
                  const selected = relationOptions.products.find(p => p.id === form.watch('productId'));
                  if (selected && selected.productName) {
                    return <span className="text-2xl font-semibold text-gray-900">{selected.productName}</span>;
                  }
                  return null;
                })()}
              </div>
            </div>
          </div>

          <div className="flex flex-row items-center gap-4 rounded-lg p-2" style={{ background: 'var(--field-bg-step, #fef9c3)' }}>
            <div className="w-1/4 min-w-[220px]">
              <FormField
                control={form.control}
                name="productionStepDetailId"
                render={({ field: formField }) => (
                  <FormItem>
                    <FormLabel>{t('production_step_detail')}</FormLabel>
                    <Select
                      onValueChange={(value) => {
                        formField.onChange(Number(value));
                      }}
                      value={formField.value?.toString()}
                      disabled={!productId} // 🆕 Disable if no product selected
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={
                            !productId
                              ? t('select_product_first')
                              : filteredProductionStepDetails.length === 0
                                ? t('no_steps_available')
                                : t('select_production_step_detail')
                          }
                          />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {filteredProductionStepDetails.map(option => (
                          <SelectItem key={option.id} value={option.id.toString()}>
                            {option.stepName || `Step ${option.id}`}
                            {' '}
                            {/* 🆕 Show stepName */}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <div className="flex h-full min-w-[200px] items-center text-sm text-muted-foreground">
              {/* 🆕 Hiển thị step name đã chọn */}
              <div className="flex flex-1 items-center justify-end">
                {(() => {
                  const selected = filteredProductionStepDetails.find(p => p.id === form.watch('productionStepDetailId'));
                  if (selected && selected.stepName) {
                    return <span className="text-lg font-semibold text-gray-900">{selected.stepName}</span>;
                  }
                  return null;
                })()}
              </div>
            </div>
          </div>

          <div className="flex flex-row items-center gap-4 rounded-lg p-2" style={{ background: 'var(--field-bg-plan, #ede9fe)' }}>
            <div className="w-1/4 min-w-[220px]">
              <FormField
                control={form.control}
                name="planId"
                render={({ field: formField }) => (
                  <FormItem>
                    <FormLabel>{t('plan')}</FormLabel>
                    <Select
                      onValueChange={(value) => {
                        formField.onChange(Number(value));
                      }}
                      value={formField.value?.toString()}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder={t('select_plan')} />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {relationOptions.plans?.map(option => (
                          <SelectItem key={option.id} value={option.id.toString()}>
                            {option.planName}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <div className="flex h-full min-w-[200px] items-center text-sm text-muted-foreground">
              {/* Hiển thị tên kế hoạch đã chọn */}
              {(() => {
                const selected = relationOptions.plans.find(p => p.id === form.watch('planId'));
                return selected ? `Tên kế hoạch: ${selected.planName}` : '';
              })()}
            </div>
          </div>

          {/* 🆕 V4: Regular Fields with Enhanced Types */}

          <div className="flex flex-row items-center gap-4">
            <div className="w-1/4 min-w-[180px]">
              <FormField
                control={form.control}
                name="workDate"
                render={({ field: formField }) => (
                  <FormItem>
                    <FormLabel>{t('work_date')}</FormLabel>
                    <Popover>
                      <PopoverTrigger asChild>
                        <FormControl>
                          <Button
                            variant="outline"
                            className={cn(
                              'w-full pl-3 text-left font-normal',
                              !formField.value && 'text-muted-foreground',
                            )}
                          >
                            {formField.value
                              ? (
                                  format(new Date(formField.value), 'PPP')
                                )
                              : (
                                  <span>{t('pick_work_date')}</span>
                                )}
                            <CalendarIcon className="ml-auto size-4 opacity-50" />
                          </Button>
                        </FormControl>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0" align="start">
                        <Calendar
                          mode="single"
                          selected={formField.value ? new Date(formField.value) : undefined}
                          onSelect={(date) => {
                            formField.onChange(date ? date.toISOString().split('T')[0] : '');
                          }}
                          disabled={date =>
                            date > new Date() || date < new Date('1900-01-01')}
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
            <div className="w-1/4 min-w-[180px]">
              <FormField
                control={form.control}
                name="entryDate"
                render={({ field: formField }) => (
                  <FormItem>
                    <FormLabel>{t('entry_date')}</FormLabel>
                    <Popover>
                      <PopoverTrigger asChild>
                        <FormControl>
                          <Button
                            variant="outline"
                            className={cn(
                              'w-full pl-3 text-left font-normal',
                              !formField.value && 'text-muted-foreground',
                            )}
                          >
                            {formField.value
                              ? (
                                  format(new Date(formField.value), 'PPP')
                                )
                              : (
                                  <span>{t('pick_entry_date')}</span>
                                )}
                            <CalendarIcon className="ml-auto size-4 opacity-50" />
                          </Button>
                        </FormControl>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0" align="start">
                        <Calendar
                          mode="single"
                          selected={formField.value ? new Date(formField.value) : undefined}
                          onSelect={(date) => {
                            formField.onChange(date ? date.toISOString().split('T')[0] : '');
                          }}
                          disabled={false}
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>
          </div>

          <div className="rounded-lg p-2" style={{ background: '#fef3c7' }}>
            <FormField
              control={form.control}
              name="actualQuantity"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>{t('actual_quantity')}</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      placeholder={t('actual_quantity_placeholder')}
                      {...formField}
                      onChange={e => formField.onChange(e.target.value ? Number(e.target.value) : undefined)}
                      value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          <div className="rounded-lg p-2" style={{ background: '#e0e7ff' }}>
            <FormField
              control={form.control}
              name="plannedQuantity"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>{t('planned_quantity')}</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      placeholder={t('planned_quantity_placeholder')}
                      {...formField}
                      onChange={e => formField.onChange(e.target.value ? Number(e.target.value) : undefined)}
                      value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          <div className="rounded-lg p-2" style={{ background: '#fce7f3' }}>
            <FormField
              control={form.control}
              name="limitQuantity"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>{t('limit_quantity')}</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      placeholder={t('limit_quantity_placeholder')}
                      {...formField}
                      onChange={e => formField.onChange(e.target.value ? Number(e.target.value) : undefined)}
                      value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          <div className="rounded-lg p-2" style={{ background: '#f1f5f9' }}>
            <FormField
              control={form.control}
              name="previousEnteredQuantity"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>{t('previous_entered_quantity')}</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      placeholder={t('previous_entered_quantity_placeholder')}
                      {...formField}
                      onChange={e => formField.onChange(e.target.value ? Number(e.target.value) : undefined)}
                      value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          <div className="rounded-lg p-2" style={{ background: '#d1fae5' }}>
            <FormField
              control={form.control}
              name="unitPrice"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>{t('unit_price')}</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      step="0.01"
                      placeholder={t('unit_price_placeholder')}
                      {...formField}
                      onChange={e => formField.onChange(e.target.value ? Number(e.target.value) : undefined)}
                      value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          <div className="rounded-lg p-2" style={{ background: '#fef08a' }}>
            <FormField
              control={form.control}
              name="totalAmount"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>{t('total_amount')}</FormLabel>
                  <FormControl>
                    <Input
                      type="number"
                      step="0.01"
                      placeholder={t('total_amount_placeholder')}
                      {...formField}
                      onChange={e => formField.onChange(e.target.value ? Number(e.target.value) : undefined)}
                      value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                      readOnly
                      className="bg-gray-50"
                    />
                  </FormControl>
                  <FormMessage />
                  <p className="text-xs text-muted-foreground">{t('auto_calculated')}</p>
                </FormItem>
              )}
            />
          </div>

          <div>
            <FormField
              control={form.control}
              name="salaryNote"
              render={({ field: formField }) => (
                <FormItem>
                  <FormLabel>{t('salary_note')}</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder={t('salary_note_placeholder')}
                      className="min-h-[100px]"
                      {...formField}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>
        </div>

        {/* 🆕 V4: Many-to-Many Relation Fields */}

        {/* 🆕 V4: Enhanced Action Buttons */}
        <div className="flex justify-end gap-4 border-t pt-4">
          <Button
            type="button"
            variant="outline"
            onClick={() => {
              form.reset({
                workDate: new Date().toISOString().split('T')[0],
                entryDate: new Date().toISOString().split('T')[0],
                actualQuantity: 0,
                salaryNote: '',
                status: 'draft', // Always keep draft
                approvedBy: '',
                userId: undefined,
                productionStepDetailId: undefined,
                planId: undefined,
                productId: undefined, // 🆕 Add productId reset
              });
              // 🆕 Reset shortcut state
              setShortcutValue('');
              setShortcutMessage('');
              setShortcutError('');
              // 🆕 Reset product code state
              setProductCodeValue('');
              setProductCodeMessage('');
              setProductCodeError('');
              // 🆕 Reset filtered production step details
              setFilteredProductionStepDetails([]);
            }}
          >
            {t('reset')}
          </Button>
          <Button type="submit" disabled={isLoading}>
            {isLoading
              ? (
                  <>
                    <div className="mr-2 size-4 animate-spin rounded-full border-2 border-white border-t-transparent" />
                    {mode === 'create' ? t('creating') : t('updating')}
                  </>
                )
              : (
                  mode === 'create' ? t('create') : t('update')
                )}
          </Button>
          {onCancel && (
            <Button type="button" variant="outline" onClick={onCancel}>
              {t('cancel')}
            </Button>
          )}
        </div>

        {/* 🆕 V4: Form Debug Info (Development Only) */}
        {process.env.NODE_ENV === 'development' && (
          <details className="mt-4 rounded-md bg-gray-50 p-4">
            <summary className="cursor-pointer text-sm font-medium">Debug Form State</summary>
            <pre className="mt-2 overflow-auto text-xs">
              {JSON.stringify(form.formState.errors, null, 2)}
            </pre>
            <pre className="mt-2 overflow-auto text-xs">
              {JSON.stringify(form.getValues(), null, 2)}
            </pre>
          </details>
        )}
      </form>
    </FormProvider>
  );
}
