/**
 * EmployeeSalaryEntry Enhanced Form Component with Complex Features
 * Generated by enhanced entity generator script V4
 * 🆕 Features: Text FK Support, Decimal Formatting, Business Logic, Complex Validation
 */

import { zodResolver } from '@hookform/resolvers/zod';
import { useTranslations } from 'next-intl';
import { useCallback, useEffect, useState } from 'react';
import { FormProvider, useForm, useWatch } from 'react-hook-form';

import { Button } from '@/components/ui/button';
import { FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { employeeSalaryEntryFormSchema } from '@/libs/validations/employeeSalaryEntry';
import type {
  EmployeeSalaryEntryFormData,
  EmployeeSalaryEntryRelationOptions,
  EmployeeSalaryEntryWithRelations,
} from '@/types/employeeSalaryEntry';
import { useProductionStepDetailQuantityLimit } from '@/hooks/useProductionStepDetailQuantityLimit';

type EmployeeSalaryEntryFormProps = {
  employeeSalaryEntry?: EmployeeSalaryEntryWithRelations;
  onSubmit: (data: EmployeeSalaryEntryFormData) => Promise<void>;
  isLoading?: boolean;
  mode?: 'create' | 'edit';
  onSuccess?: (employeeSalaryEntry: EmployeeSalaryEntryWithRelations) => void;
  onCancel?: () => void;
};

export function EmployeeSalaryEntryForm({
  employeeSalaryEntry,
  onSubmit,
  isLoading = false,
  mode = 'create',
  onSuccess,
  onCancel,
}: EmployeeSalaryEntryFormProps) {
  const [relationOptions, setRelationOptions] = useState<EmployeeSalaryEntryRelationOptions>({
    userSyncs: [],
    productionStepDetails: [],
    plans: [],
    products: [], // 🆕 Add products array
  });

  // 🆕 State for filtered production step details based on selected product
  const [filteredProductionStepDetails, setFilteredProductionStepDetails] = useState<{
    id: number;
    stepName?: string;
  }[]>([]);

  // 🆕 State for shortcut functionality
  const [shortcutValue, setShortcutValue] = useState('');
  const [shortcutMessage, setShortcutMessage] = useState('');
  const [shortcutError, setShortcutError] = useState('');

  // 🆕 State for product code functionality
  const [productCodeValue, setProductCodeValue] = useState('');
  const [productCodeMessage, setProductCodeMessage] = useState('');
  const [productCodeError, setProductCodeError] = useState('');

  // 🆕 State for form error
  const [formError, setFormError] = useState<string | null>(null);

  // 🆕 Hook for fetching production step detail quantity limit
  const { quantityLimit, fetchQuantityLimit } = useProductionStepDetailQuantityLimit();

  const form = useForm<EmployeeSalaryEntryFormData>({
    resolver: zodResolver(employeeSalaryEntryFormSchema),
    defaultValues: {
      workDate: employeeSalaryEntry?.workDate ? new Date(employeeSalaryEntry.workDate).toISOString().split('T')[0] : new Date().toISOString().split('T')[0],
      entryDate: employeeSalaryEntry?.entryDate
        ? new Date(employeeSalaryEntry.entryDate).toISOString().split('T')[0]
        : new Date().toISOString().split('T')[0],
      actualQuantity: employeeSalaryEntry?.actualQuantity ?? 0,
      plannedQuantity: employeeSalaryEntry?.plannedQuantity ?? undefined,
      limitQuantity: employeeSalaryEntry?.limitQuantity ?? undefined,
      previousEnteredQuantity: employeeSalaryEntry?.previousEnteredQuantity ?? undefined,
      unitPrice: typeof employeeSalaryEntry?.unitPrice === 'number' ? employeeSalaryEntry.unitPrice : undefined,
      totalAmount: typeof employeeSalaryEntry?.totalAmount === 'number' ? employeeSalaryEntry.totalAmount : undefined,
      salaryNote: employeeSalaryEntry?.salaryNote ?? '',
      status: employeeSalaryEntry?.status || 'draft', // Force draft for new entries
      approvedBy: employeeSalaryEntry?.approvedBy ?? '',
      approvedAt: undefined,
      startTime: undefined,
      endTime: undefined,
      workDurationMinutes: undefined,
      userId: employeeSalaryEntry?.userId ?? undefined,
      productionStepDetailId: typeof employeeSalaryEntry?.productionStepDetail === 'object' && employeeSalaryEntry.productionStepDetail !== null && typeof employeeSalaryEntry.productionStepDetail.id === 'number'
        ? employeeSalaryEntry.productionStepDetail.id
        : undefined,
      planId: employeeSalaryEntry?.planId ?? undefined,
      productId: employeeSalaryEntry?.productId ?? undefined, // 🆕 Add productId default
    },
  });

  const t = useTranslations('EmployeeSalaryEntryForm');

  // 🆕 V4: Load relation options with error handling
  useEffect(() => {
    const loadRelationOptions = async () => {
      try {
        const response = await fetch('/api/employeeSalaryEntries/relations/options');
        if (response.ok) {
          const data = await response.json();
          setRelationOptions(data.data);
        } else {
          console.error('Failed to load relation options:', response.statusText);
        }
      } catch (error) {
        console.error('Error loading relation options:', error);
      }
    };

    loadRelationOptions();
  }, []);

  // 🆕 Function to handle shortcut search
  const handleShortcutSearch = useCallback((shortcut: string) => {
    setShortcutValue(shortcut);
    setShortcutError('');
    setShortcutMessage('');

    if (!shortcut.trim()) {
      return;
    }

    // Find employee by shortcut
    const matchedEmployee = relationOptions.userSyncs.find(
      user => user.shortcut && user.shortcut.toLowerCase() === shortcut.toLowerCase().trim(),
    );

    if (matchedEmployee) {
      // Auto-populate employee selection
      form.setValue('userId', matchedEmployee.userId);
      setShortcutMessage(`✅ Found: ${matchedEmployee.fullName}`);
    } else {
      setShortcutError(`❌ No employee found with shortcut: "${shortcut}"`);
    }
  }, [relationOptions.userSyncs, form]);

  // 🆕 Function to handle product code search
  const handleProductCodeSearch = useCallback((productCode: string) => {
    setProductCodeValue(productCode);
    setProductCodeError('');
    setProductCodeMessage('');

    if (!productCode.trim()) {
      return;
    }

    // Find product by product code
    const matchedProduct = relationOptions.products.find(
      product => product.productCode && product.productCode.toLowerCase() === productCode.toLowerCase().trim(),
    );

    if (matchedProduct) {
      // Auto-populate product selection
      form.setValue('productId', matchedProduct.id);
      setProductCodeMessage(`✅ Found: ${matchedProduct.productName}`);
    } else {
      setProductCodeError(`❌ No product found with code: "${productCode}"`);
    }
  }, [relationOptions.products, form]);

  // 🆕 V4: Watch for changes in actualQuantity and unitPrice to auto-calculate totalAmount
  const actualQuantity = useWatch({ control: form.control, name: 'actualQuantity' });
  const unitPrice = useWatch({ control: form.control, name: 'unitPrice' });

  // 🆕 Watch for productId changes to load filtered production step details
  const productId = useWatch({ control: form.control, name: 'productId' });
  
  // 🆕 Watch for productionStepDetailId changes to update limit quantity
  const productionStepDetailId = useWatch({ control: form.control, name: 'productionStepDetailId' });

  useEffect(() => {
    if (actualQuantity && unitPrice) {
      const calculatedTotal = Number(actualQuantity) * Number(unitPrice);
      form.setValue('totalAmount', calculatedTotal);
    }
  }, [actualQuantity, unitPrice, form]);

  // 🆕 Load filtered production step details when product changes
  useEffect(() => {
    const loadProductionStepDetails = async () => {
      if (productId) {
        try {
          const response = await fetch(`/api/employeeSalaryEntries/relations/production-step-details?productId=${productId}`);
          if (response.ok) {
            const data = await response.json();
            setFilteredProductionStepDetails(data.data);
            // Reset productionStepDetailId when product changes
            form.setValue('productionStepDetailId', undefined);
          } else {
            console.error('Failed to load production step details:', response.statusText);
            setFilteredProductionStepDetails([]);
          }
        } catch (error) {
          console.error('Error loading production step details:', error);
          setFilteredProductionStepDetails([]);
        }
      } else {
        // Clear production step details if no product selected
        setFilteredProductionStepDetails([]);
        form.setValue('productionStepDetailId', undefined);
      }
    };

    loadProductionStepDetails();
  }, [productId, form]);

  // 🆕 V4: Auto-calculate work duration from start/end times
  const startTime = useWatch({ control: form.control, name: 'startTime' });
  const endTime = useWatch({ control: form.control, name: 'endTime' });

  useEffect(() => {
    if (startTime && endTime) {
      const start = new Date(startTime);
      const end = new Date(endTime);
      if (end > start) {
        const durationMs = end.getTime() - start.getTime();
        const durationMinutes = Math.round(durationMs / (1000 * 60));
        form.setValue('workDurationMinutes', durationMinutes);
      }
    }
  }, [startTime, endTime, form]);

  // 🆕 Auto-update limit quantity when production step detail is selected
  useEffect(() => {
    const updateLimitQuantity = async () => {
      if (productionStepDetailId) {
        const limitData = await fetchQuantityLimit(productionStepDetailId);
        if (limitData && limitData.effectiveLimit !== null) {
          // Automatically set the limit quantity from production step detail
          form.setValue('limitQuantity', limitData.effectiveLimit);
        }
      } else {
        // Clear limit quantity when no production step detail is selected
        form.setValue('limitQuantity', undefined);
      }
    };

    updateLimitQuantity();
  }, [productionStepDetailId, fetchQuantityLimit, form]);

  // 🆕 V4: Enhanced form submission with validation
  const handleSubmit = useCallback(async (data: EmployeeSalaryEntryFormData) => {
    try {
      // Check for required fields before submission
      if (!data.userId) {
        setFormError('Please select an Employee');
        return;
      }
      if (!data.productionStepDetailId) {
        setFormError('Please select a Production Step Detail');
        return;
      }
      if (!data.planId) {
        setFormError('Please select a Plan');
        return;
      }
      if (!data.productId) {
        setFormError('Please select a Product');
        return;
      }

      // Force set status to draft if empty
      if (!data.status || data.status.trim() === '') {
        data.status = 'draft';
      }

      // Xóa lỗi trước khi submit
      setFormError(null);
      await onSubmit(data);
      if (onSuccess) {
        onSuccess(employeeSalaryEntry!);
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to save';
      setFormError(errorMessage);
    }
  }, [onSubmit, onSuccess, employeeSalaryEntry]);

  return (
    <FormProvider {...form}>
      <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-6">
        {formError && (
          <div className="mb-4 rounded border border-red-300 bg-red-100 px-4 py-2 text-red-700">
            {(() => {
              if (formError === 'Please select an Employee') {
                return t('required_employee');
              }
              if (formError === 'Please select a Production Step Detail') {
                return t('required_production_step_detail');
              }
              if (formError === 'Please select a Plan') {
                return t('required_plan');
              }
              if (formError === 'Please select a Product') {
                return t('required_product');
              }
              if (formError === 'Failed to save') {
                return t('failed_to_save');
              }
              return formError;
            })()}
          </div>
        )}
        <div className="grid grid-cols-1 gap-4 max-h-[85vh] overflow-hidden">
          
          {/* Main Content Grid - 2 columns layout */}
          <div className="grid grid-cols-2 gap-6">
            
            {/* Left Column */}
            <div className="space-y-4">
              
              {/* Employee Section - Compact */}
              <div className="rounded-lg border-2 border-blue-200 bg-blue-50 p-3">
                <h3 className="mb-3 text-lg font-bold text-blue-900">👤 NHÂN VIÊN</h3>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="mb-1 block text-sm font-semibold text-blue-800">Mã NV</label>
                    <Input
                      placeholder="Nhập mã..."
                      value={shortcutValue}
                      onChange={e => handleShortcutSearch(e.target.value)}
                      className="h-12 text-lg font-bold border-2 border-blue-300"
                    />
                    {shortcutMessage && (
                      <p className="mt-1 text-xs font-medium text-green-600">✅ Tìm thấy</p>
                    )}
                    {shortcutError && (
                      <p className="mt-1 text-xs font-medium text-red-600">❌ Không tìm thấy</p>
                    )}
                  </div>
                  <div>
                    <FormField
                      control={form.control}
                      name="userId"
                      render={({ field: formField }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-semibold text-blue-800">Chọn nhân viên</FormLabel>
                          <Select
                            onValueChange={(value) => {
                              formField.onChange(value);
                              setShortcutMessage('');
                              setShortcutError('');
                            }}
                            value={formField.value?.toString()}
                          >
                            <FormControl>
                              <SelectTrigger className="h-12 text-lg border-2 border-blue-300">
                                <SelectValue placeholder="Chọn..." />
                              </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                              {relationOptions.userSyncs?.map(option => (
                                <SelectItem key={option.userId} value={option.userId.toString()}>
                                  <span className="text-lg">{option.fullName} {option.shortcut ? `(${option.shortcut})` : ''}</span>
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
                {/* Selected Employee Display */}
                <div className="mt-2 min-h-[40px] flex items-center justify-center bg-white rounded border-2 border-blue-300">
                  {(() => {
                    const selected = relationOptions.userSyncs.find(u => u.userId.toString() === form.watch('userId'));
                    return selected ? (
                      <span className="text-xl font-bold text-blue-900">{selected.fullName}</span>
                    ) : (
                      <span className="text-gray-400">Chưa chọn nhân viên</span>
                    );
                  })()}
                </div>
              </div>

              {/* Product Section - Compact */}
              <div className="rounded-lg border-2 border-green-200 bg-green-50 p-3">
                <h3 className="mb-3 text-lg font-bold text-green-900">📦 SẢN PHẨM</h3>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="mb-1 block text-sm font-semibold text-green-800">Mã SP</label>
                    <Input
                      placeholder="Nhập mã..."
                      value={productCodeValue}
                      onChange={e => handleProductCodeSearch(e.target.value)}
                      className="h-12 text-lg font-bold border-2 border-green-300"
                    />
                    {productCodeMessage && (
                      <p className="mt-1 text-xs font-medium text-green-600">✅ Tìm thấy</p>
                    )}
                    {productCodeError && (
                      <p className="mt-1 text-xs font-medium text-red-600">❌ Không tìm thấy</p>
                    )}
                  </div>
                  <div>
                    <FormField
                      control={form.control}
                      name="productId"
                      render={({ field: formField }) => (
                        <FormItem>
                          <FormLabel className="text-sm font-semibold text-green-800">Chọn sản phẩm</FormLabel>
                          <Select
                            onValueChange={(value) => {
                              formField.onChange(Number(value));
                              setProductCodeMessage('');
                              setProductCodeError('');
                            }}
                            value={formField.value?.toString()}
                          >
                            <FormControl>
                              <SelectTrigger className="h-12 text-lg border-2 border-green-300">
                                <SelectValue placeholder="Chọn..." />
                              </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                              {relationOptions.products?.map(option => (
                                <SelectItem key={option.id} value={option.id.toString()}>
                                  <span className="text-lg">{option.productName} ({option.productCode})</span>
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
                <div className="mt-2 min-h-[40px] flex items-center justify-center bg-white rounded border-2 border-green-300">
                  {(() => {
                    const selected = relationOptions.products.find(p => p.id === form.watch('productId'));
                    return selected ? (
                      <span className="text-xl font-bold text-green-900">{selected.productName}</span>
                    ) : (
                      <span className="text-gray-400">Chưa chọn sản phẩm</span>
                    );
                  })()}
                </div>
              </div>
            </div>

            {/* Right Column */}
            <div className="space-y-4">
              
              {/* Production Step Section */}
              <div className="rounded-lg border-2 border-yellow-200 bg-yellow-50 p-3">
                <h3 className="mb-3 text-lg font-bold text-yellow-900">⚙️ CÔNG ĐOẠN</h3>
                <FormField
                  control={form.control}
                  name="productionStepDetailId"
                  render={({ field: formField }) => (
                    <FormItem>
                      <FormLabel className="text-sm font-semibold text-yellow-800">Chọn công đoạn</FormLabel>
                      <Select
                        onValueChange={(value) => formField.onChange(Number(value))}
                        value={formField.value?.toString()}
                        disabled={!productId}
                      >
                        <FormControl>
                          <SelectTrigger className="h-12 text-lg border-2 border-yellow-300">
                            <SelectValue placeholder={
                              !productId ? "Chọn sản phẩm trước" : 
                              filteredProductionStepDetails.length === 0 ? "Không có công đoạn" : 
                              "Chọn công đoạn..."
                            } />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {filteredProductionStepDetails.map(option => (
                            <SelectItem key={option.id} value={option.id.toString()}>
                              <span className="text-lg">{option.stepName || `Bước ${option.id}`}</span>
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <div className="mt-2 min-h-[40px] flex items-center justify-center bg-white rounded border-2 border-yellow-300">
                  {(() => {
                    const selected = filteredProductionStepDetails.find(p => p.id === form.watch('productionStepDetailId'));
                    return selected ? (
                      <span className="text-xl font-bold text-yellow-900">{selected.stepName}</span>
                    ) : (
                      <span className="text-gray-400">Chưa chọn công đoạn</span>
                    );
                  })()}
                </div>
              </div>

              {/* Plan Section */}
              <div className="rounded-lg border-2 border-purple-200 bg-purple-50 p-3">
                <h3 className="mb-3 text-lg font-bold text-purple-900">📋 KẾ HOẠCH</h3>
                <FormField
                  control={form.control}
                  name="planId"
                  render={({ field: formField }) => (
                    <FormItem>
                      <FormLabel className="text-sm font-semibold text-purple-800">Chọn kế hoạch</FormLabel>
                      <Select
                        onValueChange={(value) => formField.onChange(Number(value))}
                        value={formField.value?.toString()}
                      >
                        <FormControl>
                          <SelectTrigger className="h-12 text-lg border-2 border-purple-300">
                            <SelectValue placeholder="Chọn kế hoạch..." />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {relationOptions.plans?.map(option => (
                            <SelectItem key={option.id} value={option.id.toString()}>
                              <span className="text-lg">{option.planName}</span>
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
                <div className="mt-2 min-h-[40px] flex items-center justify-center bg-white rounded border-2 border-purple-300">
                  {(() => {
                    const selected = relationOptions.plans.find(p => p.id === form.watch('planId'));
                    return selected ? (
                      <span className="text-xl font-bold text-purple-900">{selected.planName}</span>
                    ) : (
                      <span className="text-gray-400">Chưa chọn kế hoạch</span>
                    );
                  })()}
                </div>
              </div>
            </div>
          </div>

          {/* Quantity Fields - Horizontal Layout */}
          <div className="rounded-lg border-2 border-orange-200 bg-orange-50 p-4">
            <h3 className="mb-4 text-lg font-bold text-orange-900">🔢 SỐ LƯỢNG</h3>
            <div className="grid grid-cols-4 gap-4">
              
              <div className="rounded-lg bg-white border-2 border-orange-300 p-3">
                <FormField
                  control={form.control}
                  name="actualQuantity"
                  render={({ field: formField }) => (
                    <FormItem>
                      <FormLabel className="text-sm font-bold text-orange-800">Thực tế</FormLabel>
                      <FormControl>
                        <Input
                          type="text"
                          inputMode="numeric"
                          placeholder="0"
                          className="h-12 text-2xl font-bold text-center border-2 border-orange-400"
                          {...formField}
                          onChange={e => {
                            const value = e.target.value.replace(/[^0-9]/g, '');
                            formField.onChange(value ? Number(value) : undefined);
                          }}
                          value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="rounded-lg bg-white border-2 border-orange-300 p-3">
                <FormField
                  control={form.control}
                  name="plannedQuantity"
                  render={({ field: formField }) => (
                    <FormItem>
                      <FormLabel className="text-sm font-bold text-orange-800">Kế hoạch</FormLabel>
                      <FormControl>
                        <Input
                          type="text"
                          inputMode="numeric"
                          placeholder="0"
                          className="h-12 text-2xl font-bold text-center border-2 border-orange-400"
                          {...formField}
                          onChange={e => {
                            const value = e.target.value.replace(/[^0-9]/g, '');
                            formField.onChange(value ? Number(value) : undefined);
                          }}
                          value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="rounded-lg bg-white border-2 border-orange-300 p-3">
                <FormField
                  control={form.control}
                  name="limitQuantity"
                  render={({ field: formField }) => (
                    <FormItem>
                      <div className="flex items-center gap-2 mb-2">
                        <FormLabel className="text-sm font-bold text-orange-800">Giới hạn</FormLabel>
                        {quantityLimit && (
                          <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded">
                            🔄 Tự động
                          </span>
                        )}
                      </div>
                      <FormControl>
                        <Input
                          type="text"
                          inputMode="numeric"
                          placeholder="0"
                          className={`h-12 text-2xl font-bold text-center border-2 ${
                            quantityLimit ? 'border-green-400 bg-green-50' : 'border-orange-400'
                          }`}
                          {...formField}
                          onChange={e => {
                            const value = e.target.value.replace(/[^0-9]/g, '');
                            formField.onChange(value ? Number(value) : undefined);
                          }}
                          value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="rounded-lg bg-white border-2 border-orange-300 p-3">
                <FormField
                  control={form.control}
                  name="previousEnteredQuantity"
                  render={({ field: formField }) => (
                    <FormItem>
                      <FormLabel className="text-sm font-bold text-orange-800">Trước đó</FormLabel>
                      <FormControl>
                        <Input
                          type="text"
                          inputMode="numeric"
                          placeholder="0"
                          className="h-12 text-2xl font-bold text-center border-2 border-orange-400"
                          {...formField}
                          onChange={e => {
                            const value = e.target.value.replace(/[^0-9]/g, '');
                            formField.onChange(value ? Number(value) : undefined);
                          }}
                          value={formField.value !== undefined && formField.value !== null ? formField.value : ''}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </div>
          </div>



        </div>

        {/* 🆕 V4: Many-to-Many Relation Fields */}

        {/* Enhanced Action Buttons - User Friendly */}
        <div className="flex justify-center gap-6 border-t-4 border-gray-300 pt-6">
          <Button
            type="button"
            variant="outline"
            size="lg"
            className="h-14 px-8 text-lg font-bold border-2 border-gray-400 hover:bg-gray-100"
            onClick={() => {
              form.reset({
                workDate: new Date().toISOString().split('T')[0],
                entryDate: new Date().toISOString().split('T')[0],
                actualQuantity: 0,
                salaryNote: '',
                status: 'draft',
                approvedBy: '',
                userId: undefined,
                productionStepDetailId: undefined,
                planId: undefined,
                productId: undefined,
              });
              setShortcutValue('');
              setShortcutMessage('');
              setShortcutError('');
              setProductCodeValue('');
              setProductCodeMessage('');
              setProductCodeError('');
              setFilteredProductionStepDetails([]);
            }}
          >
            🔄 XÓA HẾT
          </Button>
          
          <Button 
            type="submit" 
            disabled={isLoading}
            size="lg"
            className="h-14 px-12 text-xl font-bold bg-green-600 hover:bg-green-700 text-white border-2 border-green-700"
          >
            {isLoading
              ? (
                  <>
                    <div className="mr-2 size-6 animate-spin rounded-full border-3 border-white border-t-transparent" />
                    ⏳ ĐANG LƯU...
                  </>
                )
              : (
                  mode === 'create' ? '💾 LƯU MỚI' : '💾 CẬP NHẬT'
                )}
          </Button>
          
          {onCancel && (
            <Button 
              type="button" 
              variant="outline" 
              size="lg"
              className="h-14 px-8 text-lg font-bold border-2 border-red-400 text-red-600 hover:bg-red-50"
              onClick={onCancel}
            >
              ❌ HỦY BỎ
            </Button>
          )}
        </div>

      </form>
    </FormProvider>
  );
}
