/**
 * OutsourceOrder Statistics API Route
 * Generated by enhanced entity generator script V4 (improved)
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import { getOutsourceOrderStats } from '@/libs/queries/outsourceOrder';

// GET /api/outsourceOrders/stats
export async function GET(_request: NextRequest) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized', code: 'AUTH_REQUIRED' },
        { status: 401 },
      );
    }

    // Use orgId for organization outsource orders, fallback to userId for personal outsource orders
    const ownerId = orgId || userId;

    const stats = await getOutsourceOrderStats(ownerId, userId);

    return NextResponse.json({
      success: true,
      data: stats,
    });
  } catch (error) {
    console.error('GET /api/outsourceOrders/stats error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Internal server error',
        code: 'INTERNAL_ERROR',
      },
      { status: 500 },
    );
  }
}
