/**
 * OutsourceOrder Relation Options API Route
 * Generated by enhanced entity generator script V4 (improved)
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import { db } from '@/libs/db';
import { userSyncSchema } from '@/models/Schema';

// GET /api/outsourceOrders/relations/options
export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized', code: 'AUTH_REQUIRED' },
        { status: 401 },
      );
    }

    const { searchParams } = new URL(request.url);
    const limit = Math.min(Number(searchParams.get('limit')) || 50, 100);

    const userSyncs = await db
      .select({
        userId: userSyncSchema.userId,
        fullName: userSyncSchema.fullName,
      })
      .from(userSyncSchema)
      .limit(limit);

    return NextResponse.json({
      success: true,
      data: {
        userSyncs,
      },
    });
  } catch (error) {
    console.error('GET /api/outsourceOrders/relations/options error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Internal server error',
        code: 'INTERNAL_ERROR',
      },
      { status: 500 },
    );
  }
}
