/**
 * OutsourceOrder Relation Options API Route
 * Generated by enhanced entity generator script V4 (improved)
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import { db } from '@/libs/DB';
import { planSchema, userSyncSchema } from '@/models/Schema';

// GET /api/outsourceOrders/relations/options
export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json(
        { success: false, error: 'Unauthorized', code: 'AUTH_REQUIRED' },
        { status: 401 },
      );
    }

    const { searchParams } = new URL(request.url);
    const limit = Math.min(Number(searchParams.get('limit')) || 50, 100);

    // Load user syncs for assignment
    const userSyncs = await db
      .select({
        id: userSyncSchema.userId,
        fullName: userSyncSchema.fullName,
      })
      .from(userSyncSchema)
      .limit(limit);

    // Load plans for selection
    const plans = await db
      .select({
        id: planSchema.id,
        planCode: planSchema.planCode,
        planName: planSchema.planName,
      })
      .from(planSchema)
      .limit(limit);

    // Apply retail price options
    const applyRetailPriceOptions = [
      { value: 2, label: 'Normal Price' },
      { value: 3, label: 'Retail Price' },
    ];

    return NextResponse.json({
      success: true,
      data: {
        userSyncs,
        plans,
        applyRetailPriceOptions,
      },
    });
  } catch (error) {
    console.error('GET /api/outsourceOrders/relations/options error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Internal server error',
        code: 'INTERNAL_ERROR',
      },
      { status: 500 },
    );
  }
}
