/**
 * EmployeeSalaryEntry Individual Entity API Routes with Enhanced Features
 * Generated by enhanced entity generator script V4
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import {
  deleteEmployeeSalaryEntry,
  getEmployeeSalaryEntryByIdRaw,
  getEmployeeSalaryEntryByIdWithRelations,
  updateEmployeeSalaryEntry,
} from '@/libs/queries/employeeSalaryEntry';
import {
  validateEmployeeSalaryEntryId,
  validateUpdateEmployeeSalaryEntry,
} from '@/libs/validations/employeeSalaryEntry';

// GET /api/employeeSalaryEntries/[id]
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = validateEmployeeSalaryEntryId({ id: params.id });
    const { searchParams } = new URL(request.url);
    const includeRelations = searchParams.get('includeRelations') === 'true';

    let employeeSalaryEntry;
    if (includeRelations) {
      employeeSalaryEntry = await getEmployeeSalaryEntryByIdWithRelations(id, orgId || userId);
    } else {
      employeeSalaryEntry = await getEmployeeSalaryEntryByIdRaw(id, orgId || userId);
    }

    if (!employeeSalaryEntry) {
      return NextResponse.json(
        { error: 'EmployeeSalaryEntry not found' },
        { status: 404 },
      );
    }

    return NextResponse.json({
      success: true,
      data: employeeSalaryEntry,
    });
  } catch (error) {
    console.error('Error fetching employeeSalaryEntry:', error);
    return NextResponse.json(
      { error: 'Failed to fetch employeeSalaryEntry' },
      { status: 500 },
    );
  }
}

// PUT /api/employeeSalaryEntries/[id]
export async function PUT(
  request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = validateEmployeeSalaryEntryId({ id: params.id });
    const body = await request.json();
    const validatedData = validateUpdateEmployeeSalaryEntry(body);

    const updatedEmployeeSalaryEntry = await updateEmployeeSalaryEntry(id, orgId || userId, validatedData);

    return NextResponse.json({
      success: true,
      data: updatedEmployeeSalaryEntry,
      message: 'EmployeeSalaryEntry updated successfully',
    });
  } catch (error) {
    console.error('Error updating employeeSalaryEntry:', error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to update employeeSalaryEntry',
        code: 'UPDATE_ERROR',
      },
      { status: 400 },
    );
  }
}

// DELETE /api/employeeSalaryEntries/[id]
export async function DELETE(
  _request: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const { userId, orgId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = validateEmployeeSalaryEntryId({ id: params.id });

    await deleteEmployeeSalaryEntry(id, orgId || userId);

    return NextResponse.json({
      success: true,
      message: 'EmployeeSalaryEntry deleted successfully',
    });
  } catch (error) {
    console.error('Error deleting employeeSalaryEntry:', error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to delete employeeSalaryEntry',
        code: 'DELETE_ERROR',
      },
      { status: 400 },
    );
  }
}
