/**
 * PlanDetail Relation Options API Route
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { auth } from '@clerk/nextjs/server';
import { asc, isNotNull } from 'drizzle-orm';
import { NextResponse } from 'next/server';

import { db } from '@/libs/DB';
import { planSchema, productSchema, productSubSchema, workTableSchema } from '@/models/Schema';

// GET /api/plandetails/relations/options
export async function GET() {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get plans
    const planOptions = await db.select({
      id: planSchema.id,
      planCode: planSchema.planCode,
    }).from(planSchema).orderBy(asc(planSchema.planCode));

    // Get products
    const productOptions = await db.select({
      id: productSchema.id,
      productCode: productSchema.productCode,
      productName: productSchema.productName,
    }).from(productSchema).orderBy(asc(productSchema.productCode));

    // Get location codes from work tables
    const locationOptions = await db.select({
      locationCode: workTableSchema.locationCode,
      tableName: workTableSchema.tableName,
    }).from(workTableSchema)
      .where(isNotNull(workTableSchema.locationCode))
      .orderBy(asc(workTableSchema.locationCode));

    // Fallback: Use table_code as location if location_code is empty
    const alternativeLocationOptions = await db.select({
      locationCode: workTableSchema.tableCode, // Use table_code as locationCode
      tableName: workTableSchema.tableName,
    }).from(workTableSchema)
      .where(isNotNull(workTableSchema.tableCode))
      .orderBy(asc(workTableSchema.tableCode));

    // Create a comprehensive location map starting with defaults 1-12
    const defaultLocations = [
      { locationCode: '1', tableName: 'Bàn 1' },
      { locationCode: '2', tableName: 'Bàn 2' },
      { locationCode: '3', tableName: 'Bàn 3' },
      { locationCode: '4', tableName: 'Bàn 4' },
      { locationCode: '5', tableName: 'Bàn 5' },
      { locationCode: '6', tableName: 'Bàn 6' },
      { locationCode: '7', tableName: 'Bàn 7' },
      { locationCode: '8', tableName: 'Bàn 8' },
      { locationCode: '9', tableName: 'Bàn 9' },
      { locationCode: '10', tableName: 'Bàn 10' },
      { locationCode: '11', tableName: 'Bàn 11' },
      { locationCode: '12', tableName: 'Bàn 12' },
    ];

    // Start with default locations
    const locationMap = new Map<string, { locationCode: string; tableName: string }>();
    defaultLocations.forEach((item) => {
      locationMap.set(item.locationCode, item);
    });

    // Override with database data if available
    type LocationItem = { locationCode: string | null; tableName: string | null };

    // Use primary locationOptions first, fallback to alternative if empty
    const primaryDataUsed = locationOptions.length > 0;
    const dataToUse = primaryDataUsed ? locationOptions : alternativeLocationOptions;

    (dataToUse as LocationItem[]).forEach((item) => {
      if (item.locationCode && item.tableName) {
        locationMap.set(item.locationCode, {
          locationCode: item.locationCode,
          tableName: item.tableName,
        });
      }
    });

    const filteredLocationOptions = Array.from(locationMap.values()).sort((a, b) => {
      // Sort numerically for number codes, then alphabetically
      const aNum = Number.parseInt(a.locationCode);
      const bNum = Number.parseInt(b.locationCode);
      if (!Number.isNaN(aNum) && !Number.isNaN(bNum)) {
        return aNum - bNum;
      }
      return a.locationCode.localeCompare(b.locationCode);
    });

    // Get product sub codes
    const productSubOptions = await db.select({
      productSubCode: productSubSchema.productSubCode,
      productSubDetail: productSubSchema.productSubDetail,
      productCode: productSubSchema.productCode,
    }).from(productSubSchema).orderBy(asc(productSubSchema.productSubCode));

    const relationOptions = {
      plans: planOptions,
      products: productOptions,
      locationCodes: filteredLocationOptions,
      productSubCodes: productSubOptions,
    };

    return NextResponse.json({
      success: true,
      data: relationOptions,
    });
  } catch (error) {
    console.error('Error fetching relation options:', error);
    return NextResponse.json(
      { error: 'Failed to fetch relation options' },
      { status: 500 },
    );
  }
}
