/**
 * PlanDetail Relation Options API Route
 * Generated by enhanced entity generator script V3 (configurable)
 */

import { auth } from '@clerk/nextjs/server';
import { asc, isNotNull } from 'drizzle-orm';
import { NextResponse } from 'next/server';

import { db } from '@/libs/DB';
import { planSchema, productSchema, productSubSchema, workTableSchema } from '@/models/Schema';

// GET /api/plandetails/relations/options
export async function GET() {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get plans
    const planOptions = await db.select({
      id: planSchema.id,
      planCode: planSchema.planCode,
    }).from(planSchema).orderBy(asc(planSchema.planCode));

    // Get products
    const productOptions = await db.select({
      id: productSchema.id,
      productCode: productSchema.productCode,
      productName: productSchema.productName,
    }).from(productSchema).orderBy(asc(productSchema.productCode));

    // Get location codes from work tables
    const locationOptions = await db.select({
      locationCode: workTableSchema.locationCode,
      tableName: workTableSchema.tableName,
    }).from(workTableSchema)
      .where(isNotNull(workTableSchema.locationCode))
      .orderBy(asc(workTableSchema.locationCode));

    // Remove duplicates manually
    type LocationItem = { locationCode: string | null; tableName: string | null };
    const uniqueLocationMap = new Map<string, LocationItem>();
    (locationOptions as LocationItem[]).forEach(item => {
      if (item.locationCode && !uniqueLocationMap.has(item.locationCode)) {
        uniqueLocationMap.set(item.locationCode, item);
      }
    });
    let filteredLocationOptions = Array.from(uniqueLocationMap.values());
    
    // If no location codes found, create some default options based on common location patterns
    if (filteredLocationOptions.length === 0) {
      filteredLocationOptions = [
        { locationCode: '1', tableName: 'Bàn 1' },
        { locationCode: '2', tableName: 'Bàn 2' },
        { locationCode: '3', tableName: 'Bàn 3' },
        { locationCode: '4', tableName: 'Bàn 4' },
        { locationCode: '5', tableName: 'Bàn 5' },
        { locationCode: 'B01', tableName: 'Bàn B01' },
        { locationCode: 'B02', tableName: 'Bàn B02' },
        { locationCode: 'B03', tableName: 'Bàn B03' },
      ];
    }
    

    // Get product sub codes
    const productSubOptions = await db.select({
      productSubCode: productSubSchema.productSubCode,
      productSubDetail: productSubSchema.productSubDetail,
      productCode: productSubSchema.productCode,
    }).from(productSubSchema).orderBy(asc(productSubSchema.productSubCode));

    const relationOptions = {
      plans: planOptions,
      products: productOptions,
      locationCodes: filteredLocationOptions,
      productSubCodes: productSubOptions,
    };

    return NextResponse.json({
      success: true,
      data: relationOptions,
    });
  } catch (error) {
    console.error('Error fetching relation options:', error);
    return NextResponse.json(
      { error: 'Failed to fetch relation options' },
      { status: 500 },
    );
  }
}
