/**
 * EmployeeSalaryEntry Enhanced API Routes with Complex Features
 * Generated by enhanced entity generator script V4
 * 🆕 Features: Text FK Support, Enhanced Filtering, Batch Operations
 */

import { auth } from '@clerk/nextjs/server';
import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

import {
  batchEmployeeSalaryEntryOperations,
  createEmployeeSalaryEntry,
  getEmployeeSalaryEntries,
} from '@/libs/queries/employeeSalaryEntry';
import {
  validateCreateEmployeeSalaryEntry,
  validateEmployeeSalaryEntryBatch,
  validateEmployeeSalaryEntryListParams,
} from '@/libs/validations/employeeSalaryEntry';

// GET /api/employeeSalaryEntries
export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);

    // 🆕 V4: Enhanced parameter parsing with complex filters
    const params = validateEmployeeSalaryEntryListParams({
      page: Number(searchParams.get('page')) || 1,
      limit: Number(searchParams.get('limit')) || 10,
      search: searchParams.get('search') || undefined,
      sortBy: searchParams.get('sortBy') || 'createdAt',
      sortOrder: searchParams.get('sortOrder') || 'desc',
      includeRelations: searchParams.get('includeRelations') === 'true',
      status: searchParams.get('status') || undefined,

      dateFrom: searchParams.get('dateFrom') || undefined,
      dateTo: searchParams.get('dateTo') || undefined,
      userId: searchParams.get('userId') || undefined,
      productionStepDetailId: searchParams.get('productionStepDetailId') ? Number(searchParams.get('productionStepDetailId')) : undefined,
      planId: searchParams.get('planId') ? Number(searchParams.get('planId')) : undefined,
      productId: searchParams.get('productId') ? Number(searchParams.get('productId')) : undefined, // 🆕 Add productId parameter
    });

    const employeeSalaryEntries = await getEmployeeSalaryEntries({
      ...params,
      owner_id: userId,
    });


    // Get total count for pagination (performance optimized)
    const totalCountParams = { ...params, page: 1, limit: 999999 };
    const totalResults = await getEmployeeSalaryEntries({
      ...totalCountParams,
      owner_id: userId,
    });

    const total = Array.isArray(totalResults) ? totalResults.length : 0;
    const hasMore = Array.isArray(employeeSalaryEntries) ? employeeSalaryEntries.length === params.limit : false;

    return NextResponse.json({
      success: true,
      data: employeeSalaryEntries,
      pagination: {
        page: params.page,
        limit: params.limit,
        total,
        hasMore,
      },
      // 🆕 V4: Include filter metadata
      filters: {
        applied: {
          status: params.status,
          dateFrom: params.dateFrom,
          dateTo: params.dateTo,
          userId: params.userId,
          productionStepDetailId: params.productionStepDetailId,
          planId: params.planId,
        },
      },
    });
  } catch (error) {
    console.error('Error fetching employeeSalaryEntries:', error);
    return NextResponse.json(
      {
        error: 'Failed to fetch employeeSalaryEntries',
        code: 'FETCH_ERROR',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    );
  }
}

// POST /api/employeeSalaryEntries
export async function POST(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    console.log('📨 Received POST body:', JSON.stringify(body, null, 2));

    // 🆕 V4: Enhanced validation with detailed error messages
    const dataToValidate = {
      ...body,
      ownerId: userId, // Add ownerId from auth
    };
    
    console.log('🔍 Data to validate:', JSON.stringify(dataToValidate, null, 2));

    const validatedData = validateCreateEmployeeSalaryEntry(dataToValidate);
    console.log('✅ Validated data:', JSON.stringify(validatedData, null, 2));

    const employeeSalaryEntry = await createEmployeeSalaryEntry(validatedData);

    return NextResponse.json({
      success: true,
      data: employeeSalaryEntry,
      message: 'EmployeeSalaryEntry created successfully',
      // 🆕 V4: Include metadata for client-side calculations
      metadata: {
        calculations: {
          totalAmount: employeeSalaryEntry.total_amount,
          unitPrice: employeeSalaryEntry.unit_price,
        },
      },
    });
  } catch (error) {
    console.error('❌ Error creating employeeSalaryEntry:', error);

    // 🆕 V4: Enhanced error handling with validation details
    if (error instanceof Error && error.message.includes('validation')) {
      console.error('🔍 Validation error details:', error);
      return NextResponse.json(
        {
          error: 'Validation failed',
          code: 'VALIDATION_ERROR',
          details: error.message,
          validationErrors: error, // Include full error object for debugging
        },
        { status: 400 },
      );
    }

    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to create employeeSalaryEntry',
        code: 'CREATE_ERROR',
        details: error instanceof Error ? error.stack : undefined,
      },
      { status: 400 },
    );
  }
}

// 🆕 V4: PATCH /api/employeeSalaryEntries/batch - Batch operations
export async function PATCH(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const validatedData = validateEmployeeSalaryEntryBatch(body);

    const result = await batchEmployeeSalaryEntryOperations(validatedData, userId);

    return NextResponse.json({
      success: result.success,
      data: result,
      message: `Batch operation completed. ${result.processed} processed, ${result.failed} failed.`,
    });
  } catch (error) {
    console.error('Error in batch operation:', error);
    return NextResponse.json(
      {
        error: 'Batch operation failed',
        code: 'BATCH_ERROR',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    );
  }
}
